#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 13
#define STATE_COUNT 120
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 47
#define ALIAS_COUNT 0
#define TOKEN_COUNT 29
#define EXTERNAL_TOKEN_COUNT 9
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define PRODUCTION_ID_COUNT 1

enum {
  anon_sym_LT_BANG = 1,
  aux_sym_doctype_token1 = 2,
  anon_sym_GT = 3,
  anon_sym_LT_BANG_LBRACKCDATA_LBRACK = 4,
  aux_sym_cdata_token1 = 5,
  anon_sym_RBRACK_RBRACK_GT = 6,
  sym__doctype = 7,
  anon_sym_LT = 8,
  anon_sym_SLASH_GT = 9,
  anon_sym_LT_QMARK = 10,
  anon_sym_QMARK_GT = 11,
  anon_sym_LT_SLASH = 12,
  anon_sym_EQ = 13,
  sym_attribute_name = 14,
  sym_attribute_value = 15,
  anon_sym_SQUOTE = 16,
  aux_sym_quoted_attribute_value_token1 = 17,
  anon_sym_DQUOTE = 18,
  aux_sym_quoted_attribute_value_token2 = 19,
  sym_text = 20,
  sym__start_tag_name = 21,
  sym__script_start_tag_name = 22,
  sym__style_start_tag_name = 23,
  sym__end_tag_name = 24,
  sym_erroneous_end_tag_name = 25,
  sym__implicit_end_tag = 26,
  sym_raw_text = 27,
  sym_comment = 28,
  sym_fragment = 29,
  sym_doctype = 30,
  sym_cdata = 31,
  sym__node = 32,
  sym_element = 33,
  sym_script_element = 34,
  sym_style_element = 35,
  sym_start_tag = 36,
  sym_script_start_tag = 37,
  sym_style_start_tag = 38,
  sym_self_closing_tag = 39,
  sym_declaration_tag = 40,
  sym_end_tag = 41,
  sym_erroneous_end_tag = 42,
  sym_attribute = 43,
  sym_quoted_attribute_value = 44,
  aux_sym_fragment_repeat1 = 45,
  aux_sym_start_tag_repeat1 = 46,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LT_BANG] = "<!",
  [aux_sym_doctype_token1] = "doctype_token1",
  [anon_sym_GT] = ">",
  [anon_sym_LT_BANG_LBRACKCDATA_LBRACK] = "<![CDATA[",
  [aux_sym_cdata_token1] = "cdata_token1",
  [anon_sym_RBRACK_RBRACK_GT] = "]]>",
  [sym__doctype] = "doctype",
  [anon_sym_LT] = "<",
  [anon_sym_SLASH_GT] = "/>",
  [anon_sym_LT_QMARK] = "<\?",
  [anon_sym_QMARK_GT] = "\?>",
  [anon_sym_LT_SLASH] = "</",
  [anon_sym_EQ] = "=",
  [sym_attribute_name] = "attribute_name",
  [sym_attribute_value] = "attribute_value",
  [anon_sym_SQUOTE] = "'",
  [aux_sym_quoted_attribute_value_token1] = "attribute_value",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_quoted_attribute_value_token2] = "attribute_value",
  [sym_text] = "text",
  [sym__start_tag_name] = "tag_name",
  [sym__script_start_tag_name] = "tag_name",
  [sym__style_start_tag_name] = "tag_name",
  [sym__end_tag_name] = "tag_name",
  [sym_erroneous_end_tag_name] = "erroneous_end_tag_name",
  [sym__implicit_end_tag] = "_implicit_end_tag",
  [sym_raw_text] = "raw_text",
  [sym_comment] = "comment",
  [sym_fragment] = "fragment",
  [sym_doctype] = "doctype",
  [sym_cdata] = "cdata",
  [sym__node] = "_node",
  [sym_element] = "element",
  [sym_script_element] = "script_element",
  [sym_style_element] = "style_element",
  [sym_start_tag] = "start_tag",
  [sym_script_start_tag] = "start_tag",
  [sym_style_start_tag] = "start_tag",
  [sym_self_closing_tag] = "self_closing_tag",
  [sym_declaration_tag] = "declaration_tag",
  [sym_end_tag] = "end_tag",
  [sym_erroneous_end_tag] = "erroneous_end_tag",
  [sym_attribute] = "attribute",
  [sym_quoted_attribute_value] = "quoted_attribute_value",
  [aux_sym_fragment_repeat1] = "fragment_repeat1",
  [aux_sym_start_tag_repeat1] = "start_tag_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LT_BANG] = anon_sym_LT_BANG,
  [aux_sym_doctype_token1] = aux_sym_doctype_token1,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_LT_BANG_LBRACKCDATA_LBRACK] = anon_sym_LT_BANG_LBRACKCDATA_LBRACK,
  [aux_sym_cdata_token1] = aux_sym_cdata_token1,
  [anon_sym_RBRACK_RBRACK_GT] = anon_sym_RBRACK_RBRACK_GT,
  [sym__doctype] = sym__doctype,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_SLASH_GT] = anon_sym_SLASH_GT,
  [anon_sym_LT_QMARK] = anon_sym_LT_QMARK,
  [anon_sym_QMARK_GT] = anon_sym_QMARK_GT,
  [anon_sym_LT_SLASH] = anon_sym_LT_SLASH,
  [anon_sym_EQ] = anon_sym_EQ,
  [sym_attribute_name] = sym_attribute_name,
  [sym_attribute_value] = sym_attribute_value,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [aux_sym_quoted_attribute_value_token1] = sym_attribute_value,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_quoted_attribute_value_token2] = sym_attribute_value,
  [sym_text] = sym_text,
  [sym__start_tag_name] = sym__start_tag_name,
  [sym__script_start_tag_name] = sym__start_tag_name,
  [sym__style_start_tag_name] = sym__start_tag_name,
  [sym__end_tag_name] = sym__start_tag_name,
  [sym_erroneous_end_tag_name] = sym_erroneous_end_tag_name,
  [sym__implicit_end_tag] = sym__implicit_end_tag,
  [sym_raw_text] = sym_raw_text,
  [sym_comment] = sym_comment,
  [sym_fragment] = sym_fragment,
  [sym_doctype] = sym_doctype,
  [sym_cdata] = sym_cdata,
  [sym__node] = sym__node,
  [sym_element] = sym_element,
  [sym_script_element] = sym_script_element,
  [sym_style_element] = sym_style_element,
  [sym_start_tag] = sym_start_tag,
  [sym_script_start_tag] = sym_start_tag,
  [sym_style_start_tag] = sym_start_tag,
  [sym_self_closing_tag] = sym_self_closing_tag,
  [sym_declaration_tag] = sym_declaration_tag,
  [sym_end_tag] = sym_end_tag,
  [sym_erroneous_end_tag] = sym_erroneous_end_tag,
  [sym_attribute] = sym_attribute,
  [sym_quoted_attribute_value] = sym_quoted_attribute_value,
  [aux_sym_fragment_repeat1] = aux_sym_fragment_repeat1,
  [aux_sym_start_tag_repeat1] = aux_sym_start_tag_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LT_BANG] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_doctype_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_BANG_LBRACKCDATA_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_cdata_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_RBRACK_RBRACK_GT] = {
    .visible = true,
    .named = false,
  },
  [sym__doctype] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_QMARK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_QMARK_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [sym_attribute_name] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute_value] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_quoted_attribute_value_token1] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_quoted_attribute_value_token2] = {
    .visible = true,
    .named = true,
  },
  [sym_text] = {
    .visible = true,
    .named = true,
  },
  [sym__start_tag_name] = {
    .visible = true,
    .named = true,
  },
  [sym__script_start_tag_name] = {
    .visible = true,
    .named = true,
  },
  [sym__style_start_tag_name] = {
    .visible = true,
    .named = true,
  },
  [sym__end_tag_name] = {
    .visible = true,
    .named = true,
  },
  [sym_erroneous_end_tag_name] = {
    .visible = true,
    .named = true,
  },
  [sym__implicit_end_tag] = {
    .visible = false,
    .named = true,
  },
  [sym_raw_text] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_fragment] = {
    .visible = true,
    .named = true,
  },
  [sym_doctype] = {
    .visible = true,
    .named = true,
  },
  [sym_cdata] = {
    .visible = true,
    .named = true,
  },
  [sym__node] = {
    .visible = false,
    .named = true,
  },
  [sym_element] = {
    .visible = true,
    .named = true,
  },
  [sym_script_element] = {
    .visible = true,
    .named = true,
  },
  [sym_style_element] = {
    .visible = true,
    .named = true,
  },
  [sym_start_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_script_start_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_style_start_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_self_closing_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_declaration_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_end_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_erroneous_end_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute] = {
    .visible = true,
    .named = true,
  },
  [sym_quoted_attribute_value] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_fragment_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_start_tag_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(25);
      if (lookahead == '"') ADVANCE(47);
      if (lookahead == '\'') ADVANCE(44);
      if (lookahead == '/') ADVANCE(6);
      if (lookahead == '<') ADVANCE(35);
      if (lookahead == '=') ADVANCE(40);
      if (lookahead == '>') ADVANCE(29);
      if (lookahead == '?') ADVANCE(7);
      if (lookahead == ']') ADVANCE(15);
      if (lookahead == 'D' ||
          lookahead == 'd') ADVANCE(18);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(47);
      if (lookahead == '\'') ADVANCE(44);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(1)
      if (lookahead != 0 &&
          (lookahead < '<' || '>' < lookahead)) ADVANCE(43);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(47);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(48);
      if (lookahead != 0) ADVANCE(49);
      END_STATE();
    case 3:
      if (lookahead == '\'') ADVANCE(44);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(45);
      if (lookahead != 0) ADVANCE(46);
      END_STATE();
    case 4:
      if (lookahead == '/') ADVANCE(6);
      if (lookahead == '=') ADVANCE(40);
      if (lookahead == '>') ADVANCE(29);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(4)
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\'' &&
          lookahead != '<') ADVANCE(42);
      END_STATE();
    case 5:
      if (lookahead == '=') ADVANCE(40);
      if (lookahead == '?') ADVANCE(41);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(5)
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\'' &&
          lookahead != '/' &&
          (lookahead < '<' || '>' < lookahead)) ADVANCE(42);
      END_STATE();
    case 6:
      if (lookahead == '>') ADVANCE(36);
      END_STATE();
    case 7:
      if (lookahead == '>') ADVANCE(38);
      END_STATE();
    case 8:
      if (lookahead == '>') ADVANCE(33);
      END_STATE();
    case 9:
      if (lookahead == 'A') ADVANCE(13);
      END_STATE();
    case 10:
      if (lookahead == 'A') ADVANCE(14);
      END_STATE();
    case 11:
      if (lookahead == 'C') ADVANCE(12);
      END_STATE();
    case 12:
      if (lookahead == 'D') ADVANCE(9);
      END_STATE();
    case 13:
      if (lookahead == 'T') ADVANCE(10);
      END_STATE();
    case 14:
      if (lookahead == '[') ADVANCE(30);
      END_STATE();
    case 15:
      if (lookahead == ']') ADVANCE(8);
      END_STATE();
    case 16:
      if (lookahead == 'C' ||
          lookahead == 'c') ADVANCE(20);
      END_STATE();
    case 17:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(34);
      END_STATE();
    case 18:
      if (lookahead == 'O' ||
          lookahead == 'o') ADVANCE(16);
      END_STATE();
    case 19:
      if (lookahead == 'P' ||
          lookahead == 'p') ADVANCE(17);
      END_STATE();
    case 20:
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(21);
      END_STATE();
    case 21:
      if (lookahead == 'Y' ||
          lookahead == 'y') ADVANCE(19);
      END_STATE();
    case 22:
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(27);
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(28);
      END_STATE();
    case 23:
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(31);
      if (lookahead != 0 &&
          lookahead != ']') ADVANCE(32);
      END_STATE();
    case 24:
      if (eof) ADVANCE(25);
      if (lookahead == '<') ADVANCE(35);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(50);
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(51);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_LT_BANG);
      if (lookahead == '[') ADVANCE(11);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(aux_sym_doctype_token1);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(27);
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(28);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(aux_sym_doctype_token1);
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(28);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_LT_BANG_LBRACKCDATA_LBRACK);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(aux_sym_cdata_token1);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(31);
      if (lookahead != 0 &&
          lookahead != ']') ADVANCE(32);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(aux_sym_cdata_token1);
      if (lookahead != 0 &&
          lookahead != ']') ADVANCE(32);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_RBRACK_RBRACK_GT);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym__doctype);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '!') ADVANCE(26);
      if (lookahead == '/') ADVANCE(39);
      if (lookahead == '?') ADVANCE(37);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_SLASH_GT);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_LT_QMARK);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_QMARK_GT);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_LT_SLASH);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_attribute_name);
      if (lookahead == '>') ADVANCE(38);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '\'' &&
          lookahead != '/' &&
          lookahead != '<' &&
          lookahead != '=') ADVANCE(42);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_attribute_name);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '\'' &&
          lookahead != '/' &&
          (lookahead < '<' || '>' < lookahead)) ADVANCE(42);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_attribute_value);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '\'' &&
          (lookahead < '<' || '>' < lookahead)) ADVANCE(43);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(aux_sym_quoted_attribute_value_token1);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(45);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(46);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(aux_sym_quoted_attribute_value_token1);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(46);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(aux_sym_quoted_attribute_value_token2);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(48);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(49);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(aux_sym_quoted_attribute_value_token2);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(49);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(50);
      if (lookahead != 0 &&
          lookahead != '<' &&
          lookahead != '>') ADVANCE(51);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_text);
      if (lookahead != 0 &&
          lookahead != '<' &&
          lookahead != '>') ADVANCE(51);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 24, .external_lex_state = 2},
  [2] = {.lex_state = 24, .external_lex_state = 3},
  [3] = {.lex_state = 24, .external_lex_state = 3},
  [4] = {.lex_state = 24, .external_lex_state = 3},
  [5] = {.lex_state = 24, .external_lex_state = 3},
  [6] = {.lex_state = 24, .external_lex_state = 3},
  [7] = {.lex_state = 24, .external_lex_state = 2},
  [8] = {.lex_state = 24, .external_lex_state = 2},
  [9] = {.lex_state = 24, .external_lex_state = 2},
  [10] = {.lex_state = 24, .external_lex_state = 2},
  [11] = {.lex_state = 24, .external_lex_state = 3},
  [12] = {.lex_state = 24, .external_lex_state = 3},
  [13] = {.lex_state = 24, .external_lex_state = 3},
  [14] = {.lex_state = 24, .external_lex_state = 3},
  [15] = {.lex_state = 24, .external_lex_state = 2},
  [16] = {.lex_state = 24, .external_lex_state = 2},
  [17] = {.lex_state = 24, .external_lex_state = 2},
  [18] = {.lex_state = 24, .external_lex_state = 3},
  [19] = {.lex_state = 24, .external_lex_state = 3},
  [20] = {.lex_state = 24, .external_lex_state = 2},
  [21] = {.lex_state = 24, .external_lex_state = 3},
  [22] = {.lex_state = 24, .external_lex_state = 2},
  [23] = {.lex_state = 24, .external_lex_state = 3},
  [24] = {.lex_state = 24, .external_lex_state = 3},
  [25] = {.lex_state = 24, .external_lex_state = 3},
  [26] = {.lex_state = 24, .external_lex_state = 2},
  [27] = {.lex_state = 24, .external_lex_state = 3},
  [28] = {.lex_state = 24, .external_lex_state = 2},
  [29] = {.lex_state = 24, .external_lex_state = 3},
  [30] = {.lex_state = 24, .external_lex_state = 2},
  [31] = {.lex_state = 24, .external_lex_state = 3},
  [32] = {.lex_state = 24, .external_lex_state = 2},
  [33] = {.lex_state = 24, .external_lex_state = 3},
  [34] = {.lex_state = 24, .external_lex_state = 2},
  [35] = {.lex_state = 24, .external_lex_state = 3},
  [36] = {.lex_state = 24, .external_lex_state = 2},
  [37] = {.lex_state = 24, .external_lex_state = 3},
  [38] = {.lex_state = 24, .external_lex_state = 3},
  [39] = {.lex_state = 24, .external_lex_state = 2},
  [40] = {.lex_state = 24, .external_lex_state = 2},
  [41] = {.lex_state = 4, .external_lex_state = 4},
  [42] = {.lex_state = 4, .external_lex_state = 4},
  [43] = {.lex_state = 4, .external_lex_state = 4},
  [44] = {.lex_state = 4, .external_lex_state = 4},
  [45] = {.lex_state = 4, .external_lex_state = 4},
  [46] = {.lex_state = 5, .external_lex_state = 2},
  [47] = {.lex_state = 4, .external_lex_state = 2},
  [48] = {.lex_state = 4, .external_lex_state = 2},
  [49] = {.lex_state = 4, .external_lex_state = 4},
  [50] = {.lex_state = 1, .external_lex_state = 2},
  [51] = {.lex_state = 1, .external_lex_state = 2},
  [52] = {.lex_state = 4, .external_lex_state = 2},
  [53] = {.lex_state = 5, .external_lex_state = 2},
  [54] = {.lex_state = 4, .external_lex_state = 2},
  [55] = {.lex_state = 4, .external_lex_state = 2},
  [56] = {.lex_state = 5, .external_lex_state = 2},
  [57] = {.lex_state = 5, .external_lex_state = 2},
  [58] = {.lex_state = 5, .external_lex_state = 2},
  [59] = {.lex_state = 1, .external_lex_state = 2},
  [60] = {.lex_state = 0, .external_lex_state = 5},
  [61] = {.lex_state = 5, .external_lex_state = 2},
  [62] = {.lex_state = 4, .external_lex_state = 4},
  [63] = {.lex_state = 0, .external_lex_state = 6},
  [64] = {.lex_state = 4, .external_lex_state = 4},
  [65] = {.lex_state = 4, .external_lex_state = 4},
  [66] = {.lex_state = 0, .external_lex_state = 6},
  [67] = {.lex_state = 0, .external_lex_state = 5},
  [68] = {.lex_state = 0, .external_lex_state = 5},
  [69] = {.lex_state = 4, .external_lex_state = 2},
  [70] = {.lex_state = 0, .external_lex_state = 5},
  [71] = {.lex_state = 3, .external_lex_state = 2},
  [72] = {.lex_state = 3, .external_lex_state = 2},
  [73] = {.lex_state = 0, .external_lex_state = 7},
  [74] = {.lex_state = 0, .external_lex_state = 5},
  [75] = {.lex_state = 0, .external_lex_state = 5},
  [76] = {.lex_state = 2, .external_lex_state = 2},
  [77] = {.lex_state = 0, .external_lex_state = 2},
  [78] = {.lex_state = 2, .external_lex_state = 2},
  [79] = {.lex_state = 0, .external_lex_state = 2},
  [80] = {.lex_state = 0, .external_lex_state = 7},
  [81] = {.lex_state = 4, .external_lex_state = 2},
  [82] = {.lex_state = 4, .external_lex_state = 2},
  [83] = {.lex_state = 4, .external_lex_state = 2},
  [84] = {.lex_state = 0, .external_lex_state = 5},
  [85] = {.lex_state = 5, .external_lex_state = 2},
  [86] = {.lex_state = 5, .external_lex_state = 2},
  [87] = {.lex_state = 5, .external_lex_state = 2},
  [88] = {.lex_state = 2, .external_lex_state = 2},
  [89] = {.lex_state = 3, .external_lex_state = 2},
  [90] = {.lex_state = 0, .external_lex_state = 2},
  [91] = {.lex_state = 0, .external_lex_state = 2},
  [92] = {.lex_state = 0, .external_lex_state = 5},
  [93] = {.lex_state = 0, .external_lex_state = 2},
  [94] = {.lex_state = 0, .external_lex_state = 8},
  [95] = {.lex_state = 0, .external_lex_state = 2},
  [96] = {.lex_state = 0, .external_lex_state = 2},
  [97] = {.lex_state = 22, .external_lex_state = 2},
  [98] = {.lex_state = 0, .external_lex_state = 2},
  [99] = {.lex_state = 0, .external_lex_state = 9},
  [100] = {.lex_state = 0, .external_lex_state = 2},
  [101] = {.lex_state = 0, .external_lex_state = 2},
  [102] = {.lex_state = 0, .external_lex_state = 2},
  [103] = {.lex_state = 0, .external_lex_state = 2},
  [104] = {.lex_state = 0, .external_lex_state = 2},
  [105] = {.lex_state = 23, .external_lex_state = 2},
  [106] = {.lex_state = 0, .external_lex_state = 2},
  [107] = {.lex_state = 0, .external_lex_state = 2},
  [108] = {.lex_state = 0, .external_lex_state = 2},
  [109] = {.lex_state = 0, .external_lex_state = 10},
  [110] = {.lex_state = 0, .external_lex_state = 2},
  [111] = {.lex_state = 0, .external_lex_state = 2},
  [112] = {.lex_state = 23, .external_lex_state = 2},
  [113] = {.lex_state = 0, .external_lex_state = 2},
  [114] = {.lex_state = 0, .external_lex_state = 8},
  [115] = {.lex_state = 0, .external_lex_state = 9},
  [116] = {.lex_state = 22, .external_lex_state = 2},
  [117] = {.lex_state = 0, .external_lex_state = 2},
  [118] = {.lex_state = 0, .external_lex_state = 10},
  [119] = {.lex_state = 0, .external_lex_state = 2},
};

enum {
  ts_external_token__start_tag_name = 0,
  ts_external_token__script_start_tag_name = 1,
  ts_external_token__style_start_tag_name = 2,
  ts_external_token__end_tag_name = 3,
  ts_external_token_erroneous_end_tag_name = 4,
  ts_external_token_SLASH_GT = 5,
  ts_external_token__implicit_end_tag = 6,
  ts_external_token_raw_text = 7,
  ts_external_token_comment = 8,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token__start_tag_name] = sym__start_tag_name,
  [ts_external_token__script_start_tag_name] = sym__script_start_tag_name,
  [ts_external_token__style_start_tag_name] = sym__style_start_tag_name,
  [ts_external_token__end_tag_name] = sym__end_tag_name,
  [ts_external_token_erroneous_end_tag_name] = sym_erroneous_end_tag_name,
  [ts_external_token_SLASH_GT] = anon_sym_SLASH_GT,
  [ts_external_token__implicit_end_tag] = sym__implicit_end_tag,
  [ts_external_token_raw_text] = sym_raw_text,
  [ts_external_token_comment] = sym_comment,
};

static const bool ts_external_scanner_states[11][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token__start_tag_name] = true,
    [ts_external_token__script_start_tag_name] = true,
    [ts_external_token__style_start_tag_name] = true,
    [ts_external_token__end_tag_name] = true,
    [ts_external_token_erroneous_end_tag_name] = true,
    [ts_external_token_SLASH_GT] = true,
    [ts_external_token__implicit_end_tag] = true,
    [ts_external_token_raw_text] = true,
    [ts_external_token_comment] = true,
  },
  [2] = {
    [ts_external_token_comment] = true,
  },
  [3] = {
    [ts_external_token__implicit_end_tag] = true,
    [ts_external_token_comment] = true,
  },
  [4] = {
    [ts_external_token_SLASH_GT] = true,
    [ts_external_token_comment] = true,
  },
  [5] = {
    [ts_external_token_raw_text] = true,
    [ts_external_token_comment] = true,
  },
  [6] = {
    [ts_external_token__start_tag_name] = true,
    [ts_external_token__script_start_tag_name] = true,
    [ts_external_token__style_start_tag_name] = true,
    [ts_external_token_comment] = true,
  },
  [7] = {
    [ts_external_token__end_tag_name] = true,
    [ts_external_token_erroneous_end_tag_name] = true,
    [ts_external_token_comment] = true,
  },
  [8] = {
    [ts_external_token__start_tag_name] = true,
    [ts_external_token_comment] = true,
  },
  [9] = {
    [ts_external_token_erroneous_end_tag_name] = true,
    [ts_external_token_comment] = true,
  },
  [10] = {
    [ts_external_token__end_tag_name] = true,
    [ts_external_token_comment] = true,
  },
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LT_BANG] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_LT_BANG_LBRACKCDATA_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK_RBRACK_GT] = ACTIONS(1),
    [sym__doctype] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_SLASH_GT] = ACTIONS(1),
    [anon_sym_LT_QMARK] = ACTIONS(1),
    [anon_sym_QMARK_GT] = ACTIONS(1),
    [anon_sym_LT_SLASH] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [sym__start_tag_name] = ACTIONS(1),
    [sym__script_start_tag_name] = ACTIONS(1),
    [sym__style_start_tag_name] = ACTIONS(1),
    [sym__end_tag_name] = ACTIONS(1),
    [sym_erroneous_end_tag_name] = ACTIONS(1),
    [sym__implicit_end_tag] = ACTIONS(1),
    [sym_raw_text] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
  },
  [1] = {
    [sym_fragment] = STATE(95),
    [sym_doctype] = STATE(8),
    [sym_cdata] = STATE(8),
    [sym__node] = STATE(8),
    [sym_element] = STATE(8),
    [sym_script_element] = STATE(8),
    [sym_style_element] = STATE(8),
    [sym_start_tag] = STATE(5),
    [sym_script_start_tag] = STATE(67),
    [sym_style_start_tag] = STATE(68),
    [sym_self_closing_tag] = STATE(15),
    [sym_declaration_tag] = STATE(15),
    [sym_erroneous_end_tag] = STATE(8),
    [aux_sym_fragment_repeat1] = STATE(8),
    [ts_builtin_sym_end] = ACTIONS(5),
    [anon_sym_LT_BANG] = ACTIONS(7),
    [anon_sym_LT_BANG_LBRACKCDATA_LBRACK] = ACTIONS(9),
    [anon_sym_LT] = ACTIONS(11),
    [anon_sym_LT_QMARK] = ACTIONS(13),
    [anon_sym_LT_SLASH] = ACTIONS(15),
    [sym_text] = ACTIONS(17),
    [sym_comment] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 14,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(19), 1,
      anon_sym_LT_BANG,
    ACTIONS(21), 1,
      anon_sym_LT_BANG_LBRACKCDATA_LBRACK,
    ACTIONS(23), 1,
      anon_sym_LT,
    ACTIONS(25), 1,
      anon_sym_LT_QMARK,
    ACTIONS(27), 1,
      anon_sym_LT_SLASH,
    ACTIONS(29), 1,
      sym_text,
    ACTIONS(31), 1,
      sym__implicit_end_tag,
    STATE(4), 1,
      sym_start_tag,
    STATE(36), 1,
      sym_end_tag,
    STATE(60), 1,
      sym_style_start_tag,
    STATE(70), 1,
      sym_script_start_tag,
    STATE(14), 2,
      sym_self_closing_tag,
      sym_declaration_tag,
    STATE(6), 8,
      sym_doctype,
      sym_cdata,
      sym__node,
      sym_element,
      sym_script_element,
      sym_style_element,
      sym_erroneous_end_tag,
      aux_sym_fragment_repeat1,
  [51] = 14,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(19), 1,
      anon_sym_LT_BANG,
    ACTIONS(21), 1,
      anon_sym_LT_BANG_LBRACKCDATA_LBRACK,
    ACTIONS(23), 1,
      anon_sym_LT,
    ACTIONS(25), 1,
      anon_sym_LT_QMARK,
    ACTIONS(29), 1,
      sym_text,
    ACTIONS(33), 1,
      anon_sym_LT_SLASH,
    ACTIONS(35), 1,
      sym__implicit_end_tag,
    STATE(4), 1,
      sym_start_tag,
    STATE(37), 1,
      sym_end_tag,
    STATE(60), 1,
      sym_style_start_tag,
    STATE(70), 1,
      sym_script_start_tag,
    STATE(14), 2,
      sym_self_closing_tag,
      sym_declaration_tag,
    STATE(6), 8,
      sym_doctype,
      sym_cdata,
      sym__node,
      sym_element,
      sym_script_element,
      sym_style_element,
      sym_erroneous_end_tag,
      aux_sym_fragment_repeat1,
  [102] = 14,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(19), 1,
      anon_sym_LT_BANG,
    ACTIONS(21), 1,
      anon_sym_LT_BANG_LBRACKCDATA_LBRACK,
    ACTIONS(23), 1,
      anon_sym_LT,
    ACTIONS(25), 1,
      anon_sym_LT_QMARK,
    ACTIONS(33), 1,
      anon_sym_LT_SLASH,
    ACTIONS(37), 1,
      sym_text,
    ACTIONS(39), 1,
      sym__implicit_end_tag,
    STATE(4), 1,
      sym_start_tag,
    STATE(13), 1,
      sym_end_tag,
    STATE(60), 1,
      sym_style_start_tag,
    STATE(70), 1,
      sym_script_start_tag,
    STATE(14), 2,
      sym_self_closing_tag,
      sym_declaration_tag,
    STATE(3), 8,
      sym_doctype,
      sym_cdata,
      sym__node,
      sym_element,
      sym_script_element,
      sym_style_element,
      sym_erroneous_end_tag,
      aux_sym_fragment_repeat1,
  [153] = 14,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(19), 1,
      anon_sym_LT_BANG,
    ACTIONS(21), 1,
      anon_sym_LT_BANG_LBRACKCDATA_LBRACK,
    ACTIONS(23), 1,
      anon_sym_LT,
    ACTIONS(25), 1,
      anon_sym_LT_QMARK,
    ACTIONS(27), 1,
      anon_sym_LT_SLASH,
    ACTIONS(41), 1,
      sym_text,
    ACTIONS(43), 1,
      sym__implicit_end_tag,
    STATE(4), 1,
      sym_start_tag,
    STATE(22), 1,
      sym_end_tag,
    STATE(60), 1,
      sym_style_start_tag,
    STATE(70), 1,
      sym_script_start_tag,
    STATE(14), 2,
      sym_self_closing_tag,
      sym_declaration_tag,
    STATE(2), 8,
      sym_doctype,
      sym_cdata,
      sym__node,
      sym_element,
      sym_script_element,
      sym_style_element,
      sym_erroneous_end_tag,
      aux_sym_fragment_repeat1,
  [204] = 13,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(45), 1,
      anon_sym_LT_BANG,
    ACTIONS(48), 1,
      anon_sym_LT_BANG_LBRACKCDATA_LBRACK,
    ACTIONS(51), 1,
      anon_sym_LT,
    ACTIONS(54), 1,
      anon_sym_LT_QMARK,
    ACTIONS(57), 1,
      anon_sym_LT_SLASH,
    ACTIONS(60), 1,
      sym_text,
    ACTIONS(63), 1,
      sym__implicit_end_tag,
    STATE(4), 1,
      sym_start_tag,
    STATE(60), 1,
      sym_style_start_tag,
    STATE(70), 1,
      sym_script_start_tag,
    STATE(14), 2,
      sym_self_closing_tag,
      sym_declaration_tag,
    STATE(6), 8,
      sym_doctype,
      sym_cdata,
      sym__node,
      sym_element,
      sym_script_element,
      sym_style_element,
      sym_erroneous_end_tag,
      aux_sym_fragment_repeat1,
  [252] = 13,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(63), 1,
      ts_builtin_sym_end,
    ACTIONS(65), 1,
      anon_sym_LT_BANG,
    ACTIONS(68), 1,
      anon_sym_LT_BANG_LBRACKCDATA_LBRACK,
    ACTIONS(71), 1,
      anon_sym_LT,
    ACTIONS(74), 1,
      anon_sym_LT_QMARK,
    ACTIONS(77), 1,
      anon_sym_LT_SLASH,
    ACTIONS(80), 1,
      sym_text,
    STATE(5), 1,
      sym_start_tag,
    STATE(67), 1,
      sym_script_start_tag,
    STATE(68), 1,
      sym_style_start_tag,
    STATE(15), 2,
      sym_self_closing_tag,
      sym_declaration_tag,
    STATE(7), 8,
      sym_doctype,
      sym_cdata,
      sym__node,
      sym_element,
      sym_script_element,
      sym_style_element,
      sym_erroneous_end_tag,
      aux_sym_fragment_repeat1,
  [300] = 13,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_LT_BANG,
    ACTIONS(9), 1,
      anon_sym_LT_BANG_LBRACKCDATA_LBRACK,
    ACTIONS(11), 1,
      anon_sym_LT,
    ACTIONS(13), 1,
      anon_sym_LT_QMARK,
    ACTIONS(15), 1,
      anon_sym_LT_SLASH,
    ACTIONS(83), 1,
      ts_builtin_sym_end,
    ACTIONS(85), 1,
      sym_text,
    STATE(5), 1,
      sym_start_tag,
    STATE(67), 1,
      sym_script_start_tag,
    STATE(68), 1,
      sym_style_start_tag,
    STATE(15), 2,
      sym_self_closing_tag,
      sym_declaration_tag,
    STATE(7), 8,
      sym_doctype,
      sym_cdata,
      sym__node,
      sym_element,
      sym_script_element,
      sym_style_element,
      sym_erroneous_end_tag,
      aux_sym_fragment_repeat1,
  [348] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(87), 2,
      ts_builtin_sym_end,
      sym_text,
    ACTIONS(89), 5,
      anon_sym_LT_BANG,
      anon_sym_LT_BANG_LBRACKCDATA_LBRACK,
      anon_sym_LT,
      anon_sym_LT_QMARK,
      anon_sym_LT_SLASH,
  [363] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(91), 2,
      ts_builtin_sym_end,
      sym_text,
    ACTIONS(93), 5,
      anon_sym_LT_BANG,
      anon_sym_LT_BANG_LBRACKCDATA_LBRACK,
      anon_sym_LT,
      anon_sym_LT_QMARK,
      anon_sym_LT_SLASH,
  [378] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(97), 2,
      sym__implicit_end_tag,
      sym_text,
    ACTIONS(95), 5,
      anon_sym_LT_BANG,
      anon_sym_LT_BANG_LBRACKCDATA_LBRACK,
      anon_sym_LT,
      anon_sym_LT_QMARK,
      anon_sym_LT_SLASH,
  [393] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(101), 2,
      sym__implicit_end_tag,
      sym_text,
    ACTIONS(99), 5,
      anon_sym_LT_BANG,
      anon_sym_LT_BANG_LBRACKCDATA_LBRACK,
      anon_sym_LT,
      anon_sym_LT_QMARK,
      anon_sym_LT_SLASH,
  [408] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(105), 2,
      sym__implicit_end_tag,
      sym_text,
    ACTIONS(103), 5,
      anon_sym_LT_BANG,
      anon_sym_LT_BANG_LBRACKCDATA_LBRACK,
      anon_sym_LT,
      anon_sym_LT_QMARK,
      anon_sym_LT_SLASH,
  [423] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(109), 2,
      sym__implicit_end_tag,
      sym_text,
    ACTIONS(107), 5,
      anon_sym_LT_BANG,
      anon_sym_LT_BANG_LBRACKCDATA_LBRACK,
      anon_sym_LT,
      anon_sym_LT_QMARK,
      anon_sym_LT_SLASH,
  [438] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(109), 2,
      ts_builtin_sym_end,
      sym_text,
    ACTIONS(107), 5,
      anon_sym_LT_BANG,
      anon_sym_LT_BANG_LBRACKCDATA_LBRACK,
      anon_sym_LT,
      anon_sym_LT_QMARK,
      anon_sym_LT_SLASH,
  [453] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(111), 2,
      ts_builtin_sym_end,
      sym_text,
    ACTIONS(113), 5,
      anon_sym_LT_BANG,
      anon_sym_LT_BANG_LBRACKCDATA_LBRACK,
      anon_sym_LT,
      anon_sym_LT_QMARK,
      anon_sym_LT_SLASH,
  [468] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(115), 2,
      ts_builtin_sym_end,
      sym_text,
    ACTIONS(117), 5,
      anon_sym_LT_BANG,
      anon_sym_LT_BANG_LBRACKCDATA_LBRACK,
      anon_sym_LT,
      anon_sym_LT_QMARK,
      anon_sym_LT_SLASH,
  [483] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(121), 2,
      sym__implicit_end_tag,
      sym_text,
    ACTIONS(119), 5,
      anon_sym_LT_BANG,
      anon_sym_LT_BANG_LBRACKCDATA_LBRACK,
      anon_sym_LT,
      anon_sym_LT_QMARK,
      anon_sym_LT_SLASH,
  [498] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(125), 2,
      sym__implicit_end_tag,
      sym_text,
    ACTIONS(123), 5,
      anon_sym_LT_BANG,
      anon_sym_LT_BANG_LBRACKCDATA_LBRACK,
      anon_sym_LT,
      anon_sym_LT_QMARK,
      anon_sym_LT_SLASH,
  [513] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(127), 2,
      ts_builtin_sym_end,
      sym_text,
    ACTIONS(129), 5,
      anon_sym_LT_BANG,
      anon_sym_LT_BANG_LBRACKCDATA_LBRACK,
      anon_sym_LT,
      anon_sym_LT_QMARK,
      anon_sym_LT_SLASH,
  [528] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(111), 2,
      sym__implicit_end_tag,
      sym_text,
    ACTIONS(113), 5,
      anon_sym_LT_BANG,
      anon_sym_LT_BANG_LBRACKCDATA_LBRACK,
      anon_sym_LT,
      anon_sym_LT_QMARK,
      anon_sym_LT_SLASH,
  [543] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(105), 2,
      ts_builtin_sym_end,
      sym_text,
    ACTIONS(103), 5,
      anon_sym_LT_BANG,
      anon_sym_LT_BANG_LBRACKCDATA_LBRACK,
      anon_sym_LT,
      anon_sym_LT_QMARK,
      anon_sym_LT_SLASH,
  [558] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(115), 2,
      sym__implicit_end_tag,
      sym_text,
    ACTIONS(117), 5,
      anon_sym_LT_BANG,
      anon_sym_LT_BANG_LBRACKCDATA_LBRACK,
      anon_sym_LT,
      anon_sym_LT_QMARK,
      anon_sym_LT_SLASH,
  [573] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(133), 2,
      sym__implicit_end_tag,
      sym_text,
    ACTIONS(131), 5,
      anon_sym_LT_BANG,
      anon_sym_LT_BANG_LBRACKCDATA_LBRACK,
      anon_sym_LT,
      anon_sym_LT_QMARK,
      anon_sym_LT_SLASH,
  [588] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(127), 2,
      sym__implicit_end_tag,
      sym_text,
    ACTIONS(129), 5,
      anon_sym_LT_BANG,
      anon_sym_LT_BANG_LBRACKCDATA_LBRACK,
      anon_sym_LT,
      anon_sym_LT_QMARK,
      anon_sym_LT_SLASH,
  [603] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(101), 2,
      ts_builtin_sym_end,
      sym_text,
    ACTIONS(99), 5,
      anon_sym_LT_BANG,
      anon_sym_LT_BANG_LBRACKCDATA_LBRACK,
      anon_sym_LT,
      anon_sym_LT_QMARK,
      anon_sym_LT_SLASH,
  [618] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(91), 2,
      sym__implicit_end_tag,
      sym_text,
    ACTIONS(93), 5,
      anon_sym_LT_BANG,
      anon_sym_LT_BANG_LBRACKCDATA_LBRACK,
      anon_sym_LT,
      anon_sym_LT_QMARK,
      anon_sym_LT_SLASH,
  [633] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(97), 2,
      ts_builtin_sym_end,
      sym_text,
    ACTIONS(95), 5,
      anon_sym_LT_BANG,
      anon_sym_LT_BANG_LBRACKCDATA_LBRACK,
      anon_sym_LT,
      anon_sym_LT_QMARK,
      anon_sym_LT_SLASH,
  [648] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(87), 2,
      sym__implicit_end_tag,
      sym_text,
    ACTIONS(89), 5,
      anon_sym_LT_BANG,
      anon_sym_LT_BANG_LBRACKCDATA_LBRACK,
      anon_sym_LT,
      anon_sym_LT_QMARK,
      anon_sym_LT_SLASH,
  [663] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(135), 2,
      ts_builtin_sym_end,
      sym_text,
    ACTIONS(137), 5,
      anon_sym_LT_BANG,
      anon_sym_LT_BANG_LBRACKCDATA_LBRACK,
      anon_sym_LT,
      anon_sym_LT_QMARK,
      anon_sym_LT_SLASH,
  [678] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(141), 2,
      sym__implicit_end_tag,
      sym_text,
    ACTIONS(139), 5,
      anon_sym_LT_BANG,
      anon_sym_LT_BANG_LBRACKCDATA_LBRACK,
      anon_sym_LT,
      anon_sym_LT_QMARK,
      anon_sym_LT_SLASH,
  [693] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(121), 2,
      ts_builtin_sym_end,
      sym_text,
    ACTIONS(119), 5,
      anon_sym_LT_BANG,
      anon_sym_LT_BANG_LBRACKCDATA_LBRACK,
      anon_sym_LT,
      anon_sym_LT_QMARK,
      anon_sym_LT_SLASH,
  [708] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(135), 2,
      sym__implicit_end_tag,
      sym_text,
    ACTIONS(137), 5,
      anon_sym_LT_BANG,
      anon_sym_LT_BANG_LBRACKCDATA_LBRACK,
      anon_sym_LT,
      anon_sym_LT_QMARK,
      anon_sym_LT_SLASH,
  [723] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(143), 2,
      ts_builtin_sym_end,
      sym_text,
    ACTIONS(145), 5,
      anon_sym_LT_BANG,
      anon_sym_LT_BANG_LBRACKCDATA_LBRACK,
      anon_sym_LT,
      anon_sym_LT_QMARK,
      anon_sym_LT_SLASH,
  [738] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(143), 2,
      sym__implicit_end_tag,
      sym_text,
    ACTIONS(145), 5,
      anon_sym_LT_BANG,
      anon_sym_LT_BANG_LBRACKCDATA_LBRACK,
      anon_sym_LT,
      anon_sym_LT_QMARK,
      anon_sym_LT_SLASH,
  [753] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(147), 2,
      ts_builtin_sym_end,
      sym_text,
    ACTIONS(149), 5,
      anon_sym_LT_BANG,
      anon_sym_LT_BANG_LBRACKCDATA_LBRACK,
      anon_sym_LT,
      anon_sym_LT_QMARK,
      anon_sym_LT_SLASH,
  [768] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(147), 2,
      sym__implicit_end_tag,
      sym_text,
    ACTIONS(149), 5,
      anon_sym_LT_BANG,
      anon_sym_LT_BANG_LBRACKCDATA_LBRACK,
      anon_sym_LT,
      anon_sym_LT_QMARK,
      anon_sym_LT_SLASH,
  [783] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(153), 2,
      sym__implicit_end_tag,
      sym_text,
    ACTIONS(151), 5,
      anon_sym_LT_BANG,
      anon_sym_LT_BANG_LBRACKCDATA_LBRACK,
      anon_sym_LT,
      anon_sym_LT_QMARK,
      anon_sym_LT_SLASH,
  [798] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(125), 2,
      ts_builtin_sym_end,
      sym_text,
    ACTIONS(123), 5,
      anon_sym_LT_BANG,
      anon_sym_LT_BANG_LBRACKCDATA_LBRACK,
      anon_sym_LT,
      anon_sym_LT_QMARK,
      anon_sym_LT_SLASH,
  [813] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(153), 2,
      ts_builtin_sym_end,
      sym_text,
    ACTIONS(151), 5,
      anon_sym_LT_BANG,
      anon_sym_LT_BANG_LBRACKCDATA_LBRACK,
      anon_sym_LT,
      anon_sym_LT_QMARK,
      anon_sym_LT_SLASH,
  [828] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(155), 1,
      anon_sym_GT,
    ACTIONS(157), 1,
      anon_sym_SLASH_GT,
    ACTIONS(159), 1,
      sym_attribute_name,
    STATE(42), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [845] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(163), 1,
      sym_attribute_name,
    ACTIONS(161), 2,
      anon_sym_GT,
      anon_sym_SLASH_GT,
    STATE(42), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [860] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(159), 1,
      sym_attribute_name,
    ACTIONS(166), 1,
      anon_sym_GT,
    ACTIONS(168), 1,
      anon_sym_SLASH_GT,
    STATE(41), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [877] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(159), 1,
      sym_attribute_name,
    ACTIONS(166), 1,
      anon_sym_GT,
    ACTIONS(170), 1,
      anon_sym_SLASH_GT,
    STATE(45), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [894] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(155), 1,
      anon_sym_GT,
    ACTIONS(159), 1,
      sym_attribute_name,
    ACTIONS(172), 1,
      anon_sym_SLASH_GT,
    STATE(42), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [911] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(174), 1,
      anon_sym_QMARK_GT,
    ACTIONS(176), 1,
      sym_attribute_name,
    STATE(56), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [925] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(178), 1,
      anon_sym_GT,
    ACTIONS(180), 1,
      sym_attribute_name,
    STATE(52), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [939] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(180), 1,
      sym_attribute_name,
    ACTIONS(182), 1,
      anon_sym_GT,
    STATE(52), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [953] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(186), 1,
      anon_sym_EQ,
    ACTIONS(184), 3,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      sym_attribute_name,
  [965] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(188), 1,
      sym_attribute_value,
    ACTIONS(190), 1,
      anon_sym_SQUOTE,
    ACTIONS(192), 1,
      anon_sym_DQUOTE,
    STATE(81), 1,
      sym_quoted_attribute_value,
  [981] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(194), 1,
      sym_attribute_value,
    ACTIONS(196), 1,
      anon_sym_SQUOTE,
    ACTIONS(198), 1,
      anon_sym_DQUOTE,
    STATE(62), 1,
      sym_quoted_attribute_value,
  [997] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(161), 1,
      anon_sym_GT,
    ACTIONS(200), 1,
      sym_attribute_name,
    STATE(52), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [1011] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(176), 1,
      sym_attribute_name,
    ACTIONS(203), 1,
      anon_sym_QMARK_GT,
    STATE(46), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [1025] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(180), 1,
      sym_attribute_name,
    ACTIONS(205), 1,
      anon_sym_GT,
    STATE(47), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [1039] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(180), 1,
      sym_attribute_name,
    ACTIONS(207), 1,
      anon_sym_GT,
    STATE(48), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [1053] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(161), 1,
      anon_sym_QMARK_GT,
    ACTIONS(209), 1,
      sym_attribute_name,
    STATE(56), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [1067] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(176), 1,
      sym_attribute_name,
    ACTIONS(212), 1,
      anon_sym_QMARK_GT,
    STATE(58), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [1081] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(176), 1,
      sym_attribute_name,
    ACTIONS(214), 1,
      anon_sym_QMARK_GT,
    STATE(56), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [1095] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(216), 1,
      sym_attribute_value,
    ACTIONS(218), 1,
      anon_sym_SQUOTE,
    ACTIONS(220), 1,
      anon_sym_DQUOTE,
    STATE(85), 1,
      sym_quoted_attribute_value,
  [1111] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(222), 1,
      anon_sym_LT_SLASH,
    ACTIONS(224), 1,
      sym_raw_text,
    STATE(11), 1,
      sym_end_tag,
  [1124] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(184), 1,
      anon_sym_QMARK_GT,
    ACTIONS(226), 1,
      anon_sym_EQ,
    ACTIONS(228), 1,
      sym_attribute_name,
  [1137] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(230), 3,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      sym_attribute_name,
  [1146] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(232), 1,
      sym__start_tag_name,
    ACTIONS(234), 1,
      sym__script_start_tag_name,
    ACTIONS(236), 1,
      sym__style_start_tag_name,
  [1159] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(238), 3,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      sym_attribute_name,
  [1168] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(240), 3,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      sym_attribute_name,
  [1177] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(234), 1,
      sym__script_start_tag_name,
    ACTIONS(236), 1,
      sym__style_start_tag_name,
    ACTIONS(242), 1,
      sym__start_tag_name,
  [1190] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(244), 1,
      anon_sym_LT_SLASH,
    ACTIONS(246), 1,
      sym_raw_text,
    STATE(26), 1,
      sym_end_tag,
  [1203] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(244), 1,
      anon_sym_LT_SLASH,
    ACTIONS(248), 1,
      sym_raw_text,
    STATE(28), 1,
      sym_end_tag,
  [1216] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(250), 1,
      anon_sym_EQ,
    ACTIONS(184), 2,
      anon_sym_GT,
      sym_attribute_name,
  [1227] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(222), 1,
      anon_sym_LT_SLASH,
    ACTIONS(252), 1,
      sym_raw_text,
    STATE(12), 1,
      sym_end_tag,
  [1240] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(254), 1,
      anon_sym_SQUOTE,
    ACTIONS(256), 1,
      aux_sym_quoted_attribute_value_token1,
  [1250] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(258), 1,
      anon_sym_SQUOTE,
    ACTIONS(260), 1,
      aux_sym_quoted_attribute_value_token1,
  [1260] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(262), 1,
      sym__end_tag_name,
    ACTIONS(264), 1,
      sym_erroneous_end_tag_name,
  [1270] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(266), 2,
      sym_raw_text,
      anon_sym_LT_SLASH,
  [1278] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(268), 2,
      sym_raw_text,
      anon_sym_LT_SLASH,
  [1286] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(270), 1,
      anon_sym_DQUOTE,
    ACTIONS(272), 1,
      aux_sym_quoted_attribute_value_token2,
  [1296] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(244), 1,
      anon_sym_LT_SLASH,
    STATE(9), 1,
      sym_end_tag,
  [1306] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(258), 1,
      anon_sym_DQUOTE,
    ACTIONS(274), 1,
      aux_sym_quoted_attribute_value_token2,
  [1316] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(244), 1,
      anon_sym_LT_SLASH,
    STATE(34), 1,
      sym_end_tag,
  [1326] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(264), 1,
      sym_erroneous_end_tag_name,
    ACTIONS(276), 1,
      sym__end_tag_name,
  [1336] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(230), 2,
      anon_sym_GT,
      sym_attribute_name,
  [1344] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(240), 2,
      anon_sym_GT,
      sym_attribute_name,
  [1352] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(238), 2,
      anon_sym_GT,
      sym_attribute_name,
  [1360] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(278), 2,
      sym_raw_text,
      anon_sym_LT_SLASH,
  [1368] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(230), 1,
      anon_sym_QMARK_GT,
    ACTIONS(280), 1,
      sym_attribute_name,
  [1378] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(240), 1,
      anon_sym_QMARK_GT,
    ACTIONS(282), 1,
      sym_attribute_name,
  [1388] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(238), 1,
      anon_sym_QMARK_GT,
    ACTIONS(284), 1,
      sym_attribute_name,
  [1398] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(254), 1,
      anon_sym_DQUOTE,
    ACTIONS(286), 1,
      aux_sym_quoted_attribute_value_token2,
  [1408] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(270), 1,
      anon_sym_SQUOTE,
    ACTIONS(288), 1,
      aux_sym_quoted_attribute_value_token1,
  [1418] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(222), 1,
      anon_sym_LT_SLASH,
    STATE(29), 1,
      sym_end_tag,
  [1428] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(222), 1,
      anon_sym_LT_SLASH,
    STATE(35), 1,
      sym_end_tag,
  [1438] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(290), 2,
      sym_raw_text,
      anon_sym_LT_SLASH,
  [1446] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(292), 1,
      anon_sym_SQUOTE,
  [1453] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(294), 1,
      sym__start_tag_name,
  [1460] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(296), 1,
      ts_builtin_sym_end,
  [1467] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(298), 1,
      anon_sym_RBRACK_RBRACK_GT,
  [1474] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(300), 1,
      aux_sym_doctype_token1,
  [1481] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(302), 1,
      anon_sym_GT,
  [1488] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(304), 1,
      sym_erroneous_end_tag_name,
  [1495] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(292), 1,
      anon_sym_DQUOTE,
  [1502] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(306), 1,
      anon_sym_GT,
  [1509] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(308), 1,
      anon_sym_DQUOTE,
  [1516] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(308), 1,
      anon_sym_SQUOTE,
  [1523] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(310), 1,
      anon_sym_RBRACK_RBRACK_GT,
  [1530] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(312), 1,
      aux_sym_cdata_token1,
  [1537] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(314), 1,
      anon_sym_GT,
  [1544] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(316), 1,
      sym__doctype,
  [1551] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(318), 1,
      anon_sym_GT,
  [1558] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(276), 1,
      sym__end_tag_name,
  [1565] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(320), 1,
      anon_sym_SQUOTE,
  [1572] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(320), 1,
      anon_sym_DQUOTE,
  [1579] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(322), 1,
      aux_sym_cdata_token1,
  [1586] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(324), 1,
      anon_sym_GT,
  [1593] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(326), 1,
      sym__start_tag_name,
  [1600] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(264), 1,
      sym_erroneous_end_tag_name,
  [1607] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(328), 1,
      aux_sym_doctype_token1,
  [1614] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(330), 1,
      anon_sym_GT,
  [1621] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(262), 1,
      sym__end_tag_name,
  [1628] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(332), 1,
      sym__doctype,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 51,
  [SMALL_STATE(4)] = 102,
  [SMALL_STATE(5)] = 153,
  [SMALL_STATE(6)] = 204,
  [SMALL_STATE(7)] = 252,
  [SMALL_STATE(8)] = 300,
  [SMALL_STATE(9)] = 348,
  [SMALL_STATE(10)] = 363,
  [SMALL_STATE(11)] = 378,
  [SMALL_STATE(12)] = 393,
  [SMALL_STATE(13)] = 408,
  [SMALL_STATE(14)] = 423,
  [SMALL_STATE(15)] = 438,
  [SMALL_STATE(16)] = 453,
  [SMALL_STATE(17)] = 468,
  [SMALL_STATE(18)] = 483,
  [SMALL_STATE(19)] = 498,
  [SMALL_STATE(20)] = 513,
  [SMALL_STATE(21)] = 528,
  [SMALL_STATE(22)] = 543,
  [SMALL_STATE(23)] = 558,
  [SMALL_STATE(24)] = 573,
  [SMALL_STATE(25)] = 588,
  [SMALL_STATE(26)] = 603,
  [SMALL_STATE(27)] = 618,
  [SMALL_STATE(28)] = 633,
  [SMALL_STATE(29)] = 648,
  [SMALL_STATE(30)] = 663,
  [SMALL_STATE(31)] = 678,
  [SMALL_STATE(32)] = 693,
  [SMALL_STATE(33)] = 708,
  [SMALL_STATE(34)] = 723,
  [SMALL_STATE(35)] = 738,
  [SMALL_STATE(36)] = 753,
  [SMALL_STATE(37)] = 768,
  [SMALL_STATE(38)] = 783,
  [SMALL_STATE(39)] = 798,
  [SMALL_STATE(40)] = 813,
  [SMALL_STATE(41)] = 828,
  [SMALL_STATE(42)] = 845,
  [SMALL_STATE(43)] = 860,
  [SMALL_STATE(44)] = 877,
  [SMALL_STATE(45)] = 894,
  [SMALL_STATE(46)] = 911,
  [SMALL_STATE(47)] = 925,
  [SMALL_STATE(48)] = 939,
  [SMALL_STATE(49)] = 953,
  [SMALL_STATE(50)] = 965,
  [SMALL_STATE(51)] = 981,
  [SMALL_STATE(52)] = 997,
  [SMALL_STATE(53)] = 1011,
  [SMALL_STATE(54)] = 1025,
  [SMALL_STATE(55)] = 1039,
  [SMALL_STATE(56)] = 1053,
  [SMALL_STATE(57)] = 1067,
  [SMALL_STATE(58)] = 1081,
  [SMALL_STATE(59)] = 1095,
  [SMALL_STATE(60)] = 1111,
  [SMALL_STATE(61)] = 1124,
  [SMALL_STATE(62)] = 1137,
  [SMALL_STATE(63)] = 1146,
  [SMALL_STATE(64)] = 1159,
  [SMALL_STATE(65)] = 1168,
  [SMALL_STATE(66)] = 1177,
  [SMALL_STATE(67)] = 1190,
  [SMALL_STATE(68)] = 1203,
  [SMALL_STATE(69)] = 1216,
  [SMALL_STATE(70)] = 1227,
  [SMALL_STATE(71)] = 1240,
  [SMALL_STATE(72)] = 1250,
  [SMALL_STATE(73)] = 1260,
  [SMALL_STATE(74)] = 1270,
  [SMALL_STATE(75)] = 1278,
  [SMALL_STATE(76)] = 1286,
  [SMALL_STATE(77)] = 1296,
  [SMALL_STATE(78)] = 1306,
  [SMALL_STATE(79)] = 1316,
  [SMALL_STATE(80)] = 1326,
  [SMALL_STATE(81)] = 1336,
  [SMALL_STATE(82)] = 1344,
  [SMALL_STATE(83)] = 1352,
  [SMALL_STATE(84)] = 1360,
  [SMALL_STATE(85)] = 1368,
  [SMALL_STATE(86)] = 1378,
  [SMALL_STATE(87)] = 1388,
  [SMALL_STATE(88)] = 1398,
  [SMALL_STATE(89)] = 1408,
  [SMALL_STATE(90)] = 1418,
  [SMALL_STATE(91)] = 1428,
  [SMALL_STATE(92)] = 1438,
  [SMALL_STATE(93)] = 1446,
  [SMALL_STATE(94)] = 1453,
  [SMALL_STATE(95)] = 1460,
  [SMALL_STATE(96)] = 1467,
  [SMALL_STATE(97)] = 1474,
  [SMALL_STATE(98)] = 1481,
  [SMALL_STATE(99)] = 1488,
  [SMALL_STATE(100)] = 1495,
  [SMALL_STATE(101)] = 1502,
  [SMALL_STATE(102)] = 1509,
  [SMALL_STATE(103)] = 1516,
  [SMALL_STATE(104)] = 1523,
  [SMALL_STATE(105)] = 1530,
  [SMALL_STATE(106)] = 1537,
  [SMALL_STATE(107)] = 1544,
  [SMALL_STATE(108)] = 1551,
  [SMALL_STATE(109)] = 1558,
  [SMALL_STATE(110)] = 1565,
  [SMALL_STATE(111)] = 1572,
  [SMALL_STATE(112)] = 1579,
  [SMALL_STATE(113)] = 1586,
  [SMALL_STATE(114)] = 1593,
  [SMALL_STATE(115)] = 1600,
  [SMALL_STATE(116)] = 1607,
  [SMALL_STATE(117)] = 1614,
  [SMALL_STATE(118)] = 1621,
  [SMALL_STATE(119)] = 1628,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fragment, 0),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(119),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(105),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(66),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(94),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(99),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(107),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(112),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(63),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(114),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(80),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [33] = {.entry = {.count = 1, .reusable = false}}, SHIFT(73),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [45] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_fragment_repeat1, 2), SHIFT_REPEAT(107),
  [48] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_fragment_repeat1, 2), SHIFT_REPEAT(112),
  [51] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_fragment_repeat1, 2), SHIFT_REPEAT(63),
  [54] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_fragment_repeat1, 2), SHIFT_REPEAT(114),
  [57] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_fragment_repeat1, 2), SHIFT_REPEAT(115),
  [60] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_fragment_repeat1, 2), SHIFT_REPEAT(6),
  [63] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_fragment_repeat1, 2),
  [65] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_fragment_repeat1, 2), SHIFT_REPEAT(119),
  [68] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_fragment_repeat1, 2), SHIFT_REPEAT(105),
  [71] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_fragment_repeat1, 2), SHIFT_REPEAT(66),
  [74] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_fragment_repeat1, 2), SHIFT_REPEAT(94),
  [77] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_fragment_repeat1, 2), SHIFT_REPEAT(99),
  [80] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_fragment_repeat1, 2), SHIFT_REPEAT(7),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fragment, 1),
  [85] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_style_element, 3),
  [89] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_style_element, 3),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_doctype, 4),
  [93] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_doctype, 4),
  [95] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_style_element, 2),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_style_element, 2),
  [99] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_script_element, 2),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_script_element, 2),
  [103] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_element, 2),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_element, 2),
  [107] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_element, 1),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_element, 1),
  [111] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_end_tag, 3),
  [113] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_end_tag, 3),
  [115] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_declaration_tag, 4),
  [117] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_declaration_tag, 4),
  [119] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_self_closing_tag, 3),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_self_closing_tag, 3),
  [123] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_declaration_tag, 3),
  [125] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_declaration_tag, 3),
  [127] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_self_closing_tag, 4),
  [129] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_self_closing_tag, 4),
  [131] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_start_tag, 4),
  [133] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_start_tag, 4),
  [135] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_cdata, 3),
  [137] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_cdata, 3),
  [139] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_start_tag, 3),
  [141] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_start_tag, 3),
  [143] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_script_element, 3),
  [145] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_script_element, 3),
  [147] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_element, 3),
  [149] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_element, 3),
  [151] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_erroneous_end_tag, 3),
  [153] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_erroneous_end_tag, 3),
  [155] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [157] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [159] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [161] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_start_tag_repeat1, 2),
  [163] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_start_tag_repeat1, 2), SHIFT_REPEAT(49),
  [166] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [168] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [170] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [172] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [174] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [176] = {.entry = {.count = 1, .reusable = false}}, SHIFT(61),
  [178] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [180] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [182] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [184] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute, 1),
  [186] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [188] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [190] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [192] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [194] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [196] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [198] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [200] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_start_tag_repeat1, 2), SHIFT_REPEAT(69),
  [203] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [205] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [207] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [209] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_start_tag_repeat1, 2), SHIFT_REPEAT(61),
  [212] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [214] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [216] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [218] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [220] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [222] = {.entry = {.count = 1, .reusable = true}}, SHIFT(118),
  [224] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [226] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [228] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_attribute, 1),
  [230] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute, 3),
  [232] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [234] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [236] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [238] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_attribute_value, 3),
  [240] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_attribute_value, 2),
  [242] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [244] = {.entry = {.count = 1, .reusable = true}}, SHIFT(109),
  [246] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [248] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [250] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [252] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [254] = {.entry = {.count = 1, .reusable = false}}, SHIFT(82),
  [256] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [258] = {.entry = {.count = 1, .reusable = false}}, SHIFT(86),
  [260] = {.entry = {.count = 1, .reusable = true}}, SHIFT(110),
  [262] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [264] = {.entry = {.count = 1, .reusable = true}}, SHIFT(106),
  [266] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_style_start_tag, 3),
  [268] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_script_start_tag, 3),
  [270] = {.entry = {.count = 1, .reusable = false}}, SHIFT(65),
  [272] = {.entry = {.count = 1, .reusable = true}}, SHIFT(102),
  [274] = {.entry = {.count = 1, .reusable = true}}, SHIFT(111),
  [276] = {.entry = {.count = 1, .reusable = true}}, SHIFT(117),
  [278] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_script_start_tag, 4),
  [280] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_attribute, 3),
  [282] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_quoted_attribute_value, 2),
  [284] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_quoted_attribute_value, 3),
  [286] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [288] = {.entry = {.count = 1, .reusable = true}}, SHIFT(103),
  [290] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_style_start_tag, 4),
  [292] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [294] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [296] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [298] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [300] = {.entry = {.count = 1, .reusable = true}}, SHIFT(113),
  [302] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [304] = {.entry = {.count = 1, .reusable = true}}, SHIFT(108),
  [306] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [308] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [310] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [312] = {.entry = {.count = 1, .reusable = true}}, SHIFT(104),
  [314] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [316] = {.entry = {.count = 1, .reusable = true}}, SHIFT(116),
  [318] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [320] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [322] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [324] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [326] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [328] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [330] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [332] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_html_external_scanner_create(void);
void tree_sitter_html_external_scanner_destroy(void *);
bool tree_sitter_html_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_html_external_scanner_serialize(void *, char *);
void tree_sitter_html_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_html(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_html_external_scanner_create,
      tree_sitter_html_external_scanner_destroy,
      tree_sitter_html_external_scanner_scan,
      tree_sitter_html_external_scanner_serialize,
      tree_sitter_html_external_scanner_deserialize,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
