#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 13
#define STATE_COUNT 126
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 48
#define ALIAS_COUNT 0
#define TOKEN_COUNT 29
#define EXTERNAL_TOKEN_COUNT 9
#define FIELD_COUNT 7
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define PRODUCTION_ID_COUNT 8

enum {
  anon_sym_LT_BANG = 1,
  aux_sym_doctype_token1 = 2,
  anon_sym_GT = 3,
  anon_sym_LT_BANG_LBRACKCDATA_LBRACK = 4,
  aux_sym_cdata_token1 = 5,
  anon_sym_RBRACK_RBRACK_GT = 6,
  sym_doctype_ = 7,
  anon_sym_LT = 8,
  anon_sym_SLASH_GT = 9,
  anon_sym_LT_QMARK = 10,
  anon_sym_QMARK_GT = 11,
  anon_sym_LT_SLASH = 12,
  anon_sym_EQ = 13,
  sym_markup_attribute_name = 14,
  sym_attribute_value = 15,
  anon_sym_SQUOTE = 16,
  aux_sym_quoted_attribute_value_token1 = 17,
  anon_sym_DQUOTE = 18,
  aux_sym_quoted_attribute_value_token2 = 19,
  sym_text_ = 20,
  sym_start_tag_name = 21,
  sym_script_start_tag_name = 22,
  sym_style_start_tag_name = 23,
  sym_end_tag_name = 24,
  sym_erroneous_end_tag_name = 25,
  sym_implicit_end_tag = 26,
  sym_raw_text = 27,
  sym_comment = 28,
  sym_fragment = 29,
  sym_doctype = 30,
  sym_cdata = 31,
  sym_markup_content = 32,
  sym_standard_markup_element = 33,
  sym_element = 34,
  sym_script_element = 35,
  sym_style_element = 36,
  sym_markup_opening_tag = 37,
  sym_script_start_tag = 38,
  sym_style_start_tag = 39,
  sym_markup_singleton_tag = 40,
  sym_declaration_tag = 41,
  sym_markup_closing_tag = 42,
  sym_erroneous_end_tag = 43,
  sym_markup_attribute = 44,
  sym_quoted_attribute_value = 45,
  aux_sym_fragment_repeat1 = 46,
  aux_sym_markup_opening_tag_repeat1 = 47,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LT_BANG] = "<!",
  [aux_sym_doctype_token1] = "doctype_pattern",
  [anon_sym_GT] = ">",
  [anon_sym_LT_BANG_LBRACKCDATA_LBRACK] = "<![CDATA[",
  [aux_sym_cdata_token1] = "cdata_pattern",
  [anon_sym_RBRACK_RBRACK_GT] = "]]>",
  [sym_doctype_] = "doctype_",
  [anon_sym_LT] = "<",
  [anon_sym_SLASH_GT] = "/>",
  [anon_sym_LT_QMARK] = "<\?",
  [anon_sym_QMARK_GT] = "\?>",
  [anon_sym_LT_SLASH] = "</",
  [anon_sym_EQ] = "=",
  [sym_markup_attribute_name] = "markup_attribute_name",
  [sym_attribute_value] = "attribute_value",
  [anon_sym_SQUOTE] = "'",
  [aux_sym_quoted_attribute_value_token1] = "single_quote",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_quoted_attribute_value_token2] = "double_quote",
  [sym_text_] = "text_",
  [sym_start_tag_name] = "start_tag_name",
  [sym_script_start_tag_name] = "script_start_tag_name",
  [sym_style_start_tag_name] = "style_start_tag_name",
  [sym_end_tag_name] = "end_tag_name",
  [sym_erroneous_end_tag_name] = "identifier",
  [sym_implicit_end_tag] = "implicit_end_tag",
  [sym_raw_text] = "raw_text",
  [sym_comment] = "comment",
  [sym_fragment] = "fragment",
  [sym_doctype] = "doctype",
  [sym_cdata] = "cdata",
  [sym_markup_content] = "markup_content",
  [sym_standard_markup_element] = "standard_markup_element",
  [sym_element] = "element",
  [sym_script_element] = "script_element",
  [sym_style_element] = "style_element",
  [sym_markup_opening_tag] = "markup_opening_tag",
  [sym_script_start_tag] = "markup_opening_tag",
  [sym_style_start_tag] = "markup_opening_tag",
  [sym_markup_singleton_tag] = "markup_singleton_tag",
  [sym_declaration_tag] = "declaration_tag",
  [sym_markup_closing_tag] = "markup_closing_tag",
  [sym_erroneous_end_tag] = "erroneous_end_tag",
  [sym_markup_attribute] = "markup_attribute",
  [sym_quoted_attribute_value] = "quoted_attribute_value",
  [aux_sym_fragment_repeat1] = "fragment_repeat1",
  [aux_sym_markup_opening_tag_repeat1] = "markup_opening_tag_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LT_BANG] = anon_sym_LT_BANG,
  [aux_sym_doctype_token1] = aux_sym_doctype_token1,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_LT_BANG_LBRACKCDATA_LBRACK] = anon_sym_LT_BANG_LBRACKCDATA_LBRACK,
  [aux_sym_cdata_token1] = aux_sym_cdata_token1,
  [anon_sym_RBRACK_RBRACK_GT] = anon_sym_RBRACK_RBRACK_GT,
  [sym_doctype_] = sym_doctype_,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_SLASH_GT] = anon_sym_SLASH_GT,
  [anon_sym_LT_QMARK] = anon_sym_LT_QMARK,
  [anon_sym_QMARK_GT] = anon_sym_QMARK_GT,
  [anon_sym_LT_SLASH] = anon_sym_LT_SLASH,
  [anon_sym_EQ] = anon_sym_EQ,
  [sym_markup_attribute_name] = sym_markup_attribute_name,
  [sym_attribute_value] = sym_attribute_value,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [aux_sym_quoted_attribute_value_token1] = aux_sym_quoted_attribute_value_token1,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_quoted_attribute_value_token2] = aux_sym_quoted_attribute_value_token2,
  [sym_text_] = sym_text_,
  [sym_start_tag_name] = sym_start_tag_name,
  [sym_script_start_tag_name] = sym_script_start_tag_name,
  [sym_style_start_tag_name] = sym_style_start_tag_name,
  [sym_end_tag_name] = sym_end_tag_name,
  [sym_erroneous_end_tag_name] = sym_erroneous_end_tag_name,
  [sym_implicit_end_tag] = sym_implicit_end_tag,
  [sym_raw_text] = sym_raw_text,
  [sym_comment] = sym_comment,
  [sym_fragment] = sym_fragment,
  [sym_doctype] = sym_doctype,
  [sym_cdata] = sym_cdata,
  [sym_markup_content] = sym_markup_content,
  [sym_standard_markup_element] = sym_standard_markup_element,
  [sym_element] = sym_element,
  [sym_script_element] = sym_script_element,
  [sym_style_element] = sym_style_element,
  [sym_markup_opening_tag] = sym_markup_opening_tag,
  [sym_script_start_tag] = sym_markup_opening_tag,
  [sym_style_start_tag] = sym_markup_opening_tag,
  [sym_markup_singleton_tag] = sym_markup_singleton_tag,
  [sym_declaration_tag] = sym_declaration_tag,
  [sym_markup_closing_tag] = sym_markup_closing_tag,
  [sym_erroneous_end_tag] = sym_erroneous_end_tag,
  [sym_markup_attribute] = sym_markup_attribute,
  [sym_quoted_attribute_value] = sym_quoted_attribute_value,
  [aux_sym_fragment_repeat1] = aux_sym_fragment_repeat1,
  [aux_sym_markup_opening_tag_repeat1] = aux_sym_markup_opening_tag_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LT_BANG] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_doctype_token1] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_BANG_LBRACKCDATA_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_cdata_token1] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_RBRACK_RBRACK_GT] = {
    .visible = true,
    .named = false,
  },
  [sym_doctype_] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_QMARK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_QMARK_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [sym_markup_attribute_name] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute_value] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_quoted_attribute_value_token1] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_quoted_attribute_value_token2] = {
    .visible = true,
    .named = true,
  },
  [sym_text_] = {
    .visible = true,
    .named = true,
  },
  [sym_start_tag_name] = {
    .visible = true,
    .named = true,
  },
  [sym_script_start_tag_name] = {
    .visible = true,
    .named = true,
  },
  [sym_style_start_tag_name] = {
    .visible = true,
    .named = true,
  },
  [sym_end_tag_name] = {
    .visible = true,
    .named = true,
  },
  [sym_erroneous_end_tag_name] = {
    .visible = true,
    .named = true,
  },
  [sym_implicit_end_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_raw_text] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_fragment] = {
    .visible = true,
    .named = true,
  },
  [sym_doctype] = {
    .visible = true,
    .named = true,
  },
  [sym_cdata] = {
    .visible = true,
    .named = true,
  },
  [sym_markup_content] = {
    .visible = true,
    .named = true,
  },
  [sym_standard_markup_element] = {
    .visible = true,
    .named = true,
  },
  [sym_element] = {
    .visible = true,
    .named = true,
  },
  [sym_script_element] = {
    .visible = true,
    .named = true,
  },
  [sym_style_element] = {
    .visible = true,
    .named = true,
  },
  [sym_markup_opening_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_script_start_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_style_start_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_markup_singleton_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_declaration_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_markup_closing_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_erroneous_end_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_markup_attribute] = {
    .visible = true,
    .named = true,
  },
  [sym_quoted_attribute_value] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_fragment_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_markup_opening_tag_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum {
  field_identifier = 1,
  field_markup_attribute_list = 2,
  field_markup_attribute_value = 3,
  field_markup_closing_tag = 4,
  field_markup_content_list = 5,
  field_markup_element = 6,
  field_text_markup_element = 7,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_identifier] = "identifier",
  [field_markup_attribute_list] = "markup_attribute_list",
  [field_markup_attribute_value] = "markup_attribute_value",
  [field_markup_closing_tag] = "markup_closing_tag",
  [field_markup_content_list] = "markup_content_list",
  [field_markup_element] = "markup_element",
  [field_text_markup_element] = "text_markup_element",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 1},
  [4] = {.index = 3, .length = 3},
  [5] = {.index = 6, .length = 1},
  [6] = {.index = 7, .length = 2},
  [7] = {.index = 9, .length = 1},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_text_markup_element, 0},
  [1] =
    {field_markup_element, 0},
  [2] =
    {field_identifier, 1},
  [3] =
    {field_markup_closing_tag, 0},
    {field_markup_closing_tag, 1},
    {field_markup_closing_tag, 2},
  [6] =
    {field_markup_content_list, 1},
  [7] =
    {field_identifier, 1},
    {field_markup_attribute_list, 2},
  [9] =
    {field_markup_attribute_value, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(25);
      if (lookahead == '"') ADVANCE(47);
      if (lookahead == '\'') ADVANCE(44);
      if (lookahead == '/') ADVANCE(6);
      if (lookahead == '<') ADVANCE(35);
      if (lookahead == '=') ADVANCE(40);
      if (lookahead == '>') ADVANCE(29);
      if (lookahead == '?') ADVANCE(7);
      if (lookahead == ']') ADVANCE(15);
      if (lookahead == 'D' ||
          lookahead == 'd') ADVANCE(18);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(47);
      if (lookahead == '\'') ADVANCE(44);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(1)
      if (lookahead != 0 &&
          (lookahead < '<' || '>' < lookahead)) ADVANCE(43);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(47);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(48);
      if (lookahead != 0) ADVANCE(49);
      END_STATE();
    case 3:
      if (lookahead == '\'') ADVANCE(44);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(45);
      if (lookahead != 0) ADVANCE(46);
      END_STATE();
    case 4:
      if (lookahead == '/') ADVANCE(6);
      if (lookahead == '=') ADVANCE(40);
      if (lookahead == '>') ADVANCE(29);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(4)
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\'' &&
          lookahead != '<') ADVANCE(42);
      END_STATE();
    case 5:
      if (lookahead == '=') ADVANCE(40);
      if (lookahead == '?') ADVANCE(41);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(5)
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\'' &&
          lookahead != '/' &&
          (lookahead < '<' || '>' < lookahead)) ADVANCE(42);
      END_STATE();
    case 6:
      if (lookahead == '>') ADVANCE(36);
      END_STATE();
    case 7:
      if (lookahead == '>') ADVANCE(38);
      END_STATE();
    case 8:
      if (lookahead == '>') ADVANCE(33);
      END_STATE();
    case 9:
      if (lookahead == 'A') ADVANCE(13);
      END_STATE();
    case 10:
      if (lookahead == 'A') ADVANCE(14);
      END_STATE();
    case 11:
      if (lookahead == 'C') ADVANCE(12);
      END_STATE();
    case 12:
      if (lookahead == 'D') ADVANCE(9);
      END_STATE();
    case 13:
      if (lookahead == 'T') ADVANCE(10);
      END_STATE();
    case 14:
      if (lookahead == '[') ADVANCE(30);
      END_STATE();
    case 15:
      if (lookahead == ']') ADVANCE(8);
      END_STATE();
    case 16:
      if (lookahead == 'C' ||
          lookahead == 'c') ADVANCE(20);
      END_STATE();
    case 17:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(34);
      END_STATE();
    case 18:
      if (lookahead == 'O' ||
          lookahead == 'o') ADVANCE(16);
      END_STATE();
    case 19:
      if (lookahead == 'P' ||
          lookahead == 'p') ADVANCE(17);
      END_STATE();
    case 20:
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(21);
      END_STATE();
    case 21:
      if (lookahead == 'Y' ||
          lookahead == 'y') ADVANCE(19);
      END_STATE();
    case 22:
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(27);
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(28);
      END_STATE();
    case 23:
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(31);
      if (lookahead != 0 &&
          lookahead != ']') ADVANCE(32);
      END_STATE();
    case 24:
      if (eof) ADVANCE(25);
      if (lookahead == '<') ADVANCE(35);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(50);
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(51);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_LT_BANG);
      if (lookahead == '[') ADVANCE(11);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(aux_sym_doctype_token1);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(27);
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(28);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(aux_sym_doctype_token1);
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(28);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_LT_BANG_LBRACKCDATA_LBRACK);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(aux_sym_cdata_token1);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(31);
      if (lookahead != 0 &&
          lookahead != ']') ADVANCE(32);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(aux_sym_cdata_token1);
      if (lookahead != 0 &&
          lookahead != ']') ADVANCE(32);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_RBRACK_RBRACK_GT);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_doctype_);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '!') ADVANCE(26);
      if (lookahead == '/') ADVANCE(39);
      if (lookahead == '?') ADVANCE(37);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_SLASH_GT);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_LT_QMARK);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_QMARK_GT);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_LT_SLASH);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_markup_attribute_name);
      if (lookahead == '>') ADVANCE(38);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '\'' &&
          lookahead != '/' &&
          lookahead != '<' &&
          lookahead != '=') ADVANCE(42);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_markup_attribute_name);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '\'' &&
          lookahead != '/' &&
          (lookahead < '<' || '>' < lookahead)) ADVANCE(42);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_attribute_value);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '\'' &&
          (lookahead < '<' || '>' < lookahead)) ADVANCE(43);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(aux_sym_quoted_attribute_value_token1);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(45);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(46);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(aux_sym_quoted_attribute_value_token1);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(46);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(aux_sym_quoted_attribute_value_token2);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(48);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(49);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(aux_sym_quoted_attribute_value_token2);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(49);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_text_);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(50);
      if (lookahead != 0 &&
          lookahead != '<' &&
          lookahead != '>') ADVANCE(51);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_text_);
      if (lookahead != 0 &&
          lookahead != '<' &&
          lookahead != '>') ADVANCE(51);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 24, .external_lex_state = 2},
  [2] = {.lex_state = 24, .external_lex_state = 3},
  [3] = {.lex_state = 24, .external_lex_state = 3},
  [4] = {.lex_state = 24, .external_lex_state = 3},
  [5] = {.lex_state = 24, .external_lex_state = 3},
  [6] = {.lex_state = 24, .external_lex_state = 2},
  [7] = {.lex_state = 24, .external_lex_state = 2},
  [8] = {.lex_state = 24, .external_lex_state = 3},
  [9] = {.lex_state = 24, .external_lex_state = 3},
  [10] = {.lex_state = 24, .external_lex_state = 2},
  [11] = {.lex_state = 24, .external_lex_state = 2},
  [12] = {.lex_state = 24, .external_lex_state = 2},
  [13] = {.lex_state = 24, .external_lex_state = 2},
  [14] = {.lex_state = 24, .external_lex_state = 2},
  [15] = {.lex_state = 24, .external_lex_state = 2},
  [16] = {.lex_state = 24, .external_lex_state = 2},
  [17] = {.lex_state = 24, .external_lex_state = 3},
  [18] = {.lex_state = 24, .external_lex_state = 3},
  [19] = {.lex_state = 24, .external_lex_state = 3},
  [20] = {.lex_state = 24, .external_lex_state = 3},
  [21] = {.lex_state = 24, .external_lex_state = 3},
  [22] = {.lex_state = 24, .external_lex_state = 2},
  [23] = {.lex_state = 24, .external_lex_state = 2},
  [24] = {.lex_state = 24, .external_lex_state = 3},
  [25] = {.lex_state = 24, .external_lex_state = 3},
  [26] = {.lex_state = 24, .external_lex_state = 3},
  [27] = {.lex_state = 24, .external_lex_state = 3},
  [28] = {.lex_state = 24, .external_lex_state = 2},
  [29] = {.lex_state = 24, .external_lex_state = 3},
  [30] = {.lex_state = 24, .external_lex_state = 3},
  [31] = {.lex_state = 24, .external_lex_state = 3},
  [32] = {.lex_state = 24, .external_lex_state = 3},
  [33] = {.lex_state = 24, .external_lex_state = 2},
  [34] = {.lex_state = 24, .external_lex_state = 3},
  [35] = {.lex_state = 24, .external_lex_state = 2},
  [36] = {.lex_state = 24, .external_lex_state = 3},
  [37] = {.lex_state = 24, .external_lex_state = 3},
  [38] = {.lex_state = 24, .external_lex_state = 3},
  [39] = {.lex_state = 24, .external_lex_state = 3},
  [40] = {.lex_state = 24, .external_lex_state = 2},
  [41] = {.lex_state = 24, .external_lex_state = 2},
  [42] = {.lex_state = 24, .external_lex_state = 3},
  [43] = {.lex_state = 24, .external_lex_state = 2},
  [44] = {.lex_state = 24, .external_lex_state = 2},
  [45] = {.lex_state = 24, .external_lex_state = 2},
  [46] = {.lex_state = 24, .external_lex_state = 2},
  [47] = {.lex_state = 4, .external_lex_state = 4},
  [48] = {.lex_state = 4, .external_lex_state = 4},
  [49] = {.lex_state = 4, .external_lex_state = 4},
  [50] = {.lex_state = 4, .external_lex_state = 4},
  [51] = {.lex_state = 4, .external_lex_state = 4},
  [52] = {.lex_state = 4, .external_lex_state = 2},
  [53] = {.lex_state = 5, .external_lex_state = 2},
  [54] = {.lex_state = 4, .external_lex_state = 2},
  [55] = {.lex_state = 1, .external_lex_state = 2},
  [56] = {.lex_state = 4, .external_lex_state = 2},
  [57] = {.lex_state = 4, .external_lex_state = 2},
  [58] = {.lex_state = 1, .external_lex_state = 2},
  [59] = {.lex_state = 1, .external_lex_state = 2},
  [60] = {.lex_state = 5, .external_lex_state = 2},
  [61] = {.lex_state = 5, .external_lex_state = 2},
  [62] = {.lex_state = 4, .external_lex_state = 2},
  [63] = {.lex_state = 4, .external_lex_state = 4},
  [64] = {.lex_state = 5, .external_lex_state = 2},
  [65] = {.lex_state = 5, .external_lex_state = 2},
  [66] = {.lex_state = 0, .external_lex_state = 5},
  [67] = {.lex_state = 4, .external_lex_state = 4},
  [68] = {.lex_state = 0, .external_lex_state = 5},
  [69] = {.lex_state = 4, .external_lex_state = 4},
  [70] = {.lex_state = 0, .external_lex_state = 5},
  [71] = {.lex_state = 0, .external_lex_state = 5},
  [72] = {.lex_state = 4, .external_lex_state = 4},
  [73] = {.lex_state = 4, .external_lex_state = 2},
  [74] = {.lex_state = 5, .external_lex_state = 2},
  [75] = {.lex_state = 0, .external_lex_state = 6},
  [76] = {.lex_state = 0, .external_lex_state = 6},
  [77] = {.lex_state = 5, .external_lex_state = 2},
  [78] = {.lex_state = 0, .external_lex_state = 2},
  [79] = {.lex_state = 0, .external_lex_state = 7},
  [80] = {.lex_state = 2, .external_lex_state = 2},
  [81] = {.lex_state = 2, .external_lex_state = 2},
  [82] = {.lex_state = 3, .external_lex_state = 2},
  [83] = {.lex_state = 0, .external_lex_state = 5},
  [84] = {.lex_state = 0, .external_lex_state = 5},
  [85] = {.lex_state = 3, .external_lex_state = 2},
  [86] = {.lex_state = 4, .external_lex_state = 2},
  [87] = {.lex_state = 4, .external_lex_state = 2},
  [88] = {.lex_state = 4, .external_lex_state = 2},
  [89] = {.lex_state = 0, .external_lex_state = 5},
  [90] = {.lex_state = 0, .external_lex_state = 5},
  [91] = {.lex_state = 5, .external_lex_state = 2},
  [92] = {.lex_state = 2, .external_lex_state = 2},
  [93] = {.lex_state = 5, .external_lex_state = 2},
  [94] = {.lex_state = 0, .external_lex_state = 2},
  [95] = {.lex_state = 3, .external_lex_state = 2},
  [96] = {.lex_state = 0, .external_lex_state = 2},
  [97] = {.lex_state = 0, .external_lex_state = 2},
  [98] = {.lex_state = 0, .external_lex_state = 7},
  [99] = {.lex_state = 0, .external_lex_state = 2},
  [100] = {.lex_state = 0, .external_lex_state = 2},
  [101] = {.lex_state = 0, .external_lex_state = 2},
  [102] = {.lex_state = 0, .external_lex_state = 2},
  [103] = {.lex_state = 0, .external_lex_state = 2},
  [104] = {.lex_state = 0, .external_lex_state = 2},
  [105] = {.lex_state = 22, .external_lex_state = 2},
  [106] = {.lex_state = 0, .external_lex_state = 2},
  [107] = {.lex_state = 0, .external_lex_state = 2},
  [108] = {.lex_state = 0, .external_lex_state = 8},
  [109] = {.lex_state = 0, .external_lex_state = 9},
  [110] = {.lex_state = 0, .external_lex_state = 2},
  [111] = {.lex_state = 0, .external_lex_state = 2},
  [112] = {.lex_state = 0, .external_lex_state = 2},
  [113] = {.lex_state = 0, .external_lex_state = 10},
  [114] = {.lex_state = 0, .external_lex_state = 2},
  [115] = {.lex_state = 0, .external_lex_state = 2},
  [116] = {.lex_state = 0, .external_lex_state = 2},
  [117] = {.lex_state = 0, .external_lex_state = 2},
  [118] = {.lex_state = 23, .external_lex_state = 2},
  [119] = {.lex_state = 23, .external_lex_state = 2},
  [120] = {.lex_state = 0, .external_lex_state = 10},
  [121] = {.lex_state = 0, .external_lex_state = 8},
  [122] = {.lex_state = 22, .external_lex_state = 2},
  [123] = {.lex_state = 0, .external_lex_state = 2},
  [124] = {.lex_state = 0, .external_lex_state = 9},
  [125] = {.lex_state = 0, .external_lex_state = 2},
};

enum {
  ts_external_token_start_tag_name = 0,
  ts_external_token_script_start_tag_name = 1,
  ts_external_token_style_start_tag_name = 2,
  ts_external_token_end_tag_name = 3,
  ts_external_token_erroneous_end_tag_name = 4,
  ts_external_token_SLASH_GT = 5,
  ts_external_token_implicit_end_tag = 6,
  ts_external_token_raw_text = 7,
  ts_external_token_comment = 8,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token_start_tag_name] = sym_start_tag_name,
  [ts_external_token_script_start_tag_name] = sym_script_start_tag_name,
  [ts_external_token_style_start_tag_name] = sym_style_start_tag_name,
  [ts_external_token_end_tag_name] = sym_end_tag_name,
  [ts_external_token_erroneous_end_tag_name] = sym_erroneous_end_tag_name,
  [ts_external_token_SLASH_GT] = anon_sym_SLASH_GT,
  [ts_external_token_implicit_end_tag] = sym_implicit_end_tag,
  [ts_external_token_raw_text] = sym_raw_text,
  [ts_external_token_comment] = sym_comment,
};

static const bool ts_external_scanner_states[11][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token_start_tag_name] = true,
    [ts_external_token_script_start_tag_name] = true,
    [ts_external_token_style_start_tag_name] = true,
    [ts_external_token_end_tag_name] = true,
    [ts_external_token_erroneous_end_tag_name] = true,
    [ts_external_token_SLASH_GT] = true,
    [ts_external_token_implicit_end_tag] = true,
    [ts_external_token_raw_text] = true,
    [ts_external_token_comment] = true,
  },
  [2] = {
    [ts_external_token_comment] = true,
  },
  [3] = {
    [ts_external_token_implicit_end_tag] = true,
    [ts_external_token_comment] = true,
  },
  [4] = {
    [ts_external_token_SLASH_GT] = true,
    [ts_external_token_comment] = true,
  },
  [5] = {
    [ts_external_token_raw_text] = true,
    [ts_external_token_comment] = true,
  },
  [6] = {
    [ts_external_token_start_tag_name] = true,
    [ts_external_token_script_start_tag_name] = true,
    [ts_external_token_style_start_tag_name] = true,
    [ts_external_token_comment] = true,
  },
  [7] = {
    [ts_external_token_end_tag_name] = true,
    [ts_external_token_erroneous_end_tag_name] = true,
    [ts_external_token_comment] = true,
  },
  [8] = {
    [ts_external_token_erroneous_end_tag_name] = true,
    [ts_external_token_comment] = true,
  },
  [9] = {
    [ts_external_token_end_tag_name] = true,
    [ts_external_token_comment] = true,
  },
  [10] = {
    [ts_external_token_start_tag_name] = true,
    [ts_external_token_comment] = true,
  },
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LT_BANG] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_LT_BANG_LBRACKCDATA_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK_RBRACK_GT] = ACTIONS(1),
    [sym_doctype_] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_SLASH_GT] = ACTIONS(1),
    [anon_sym_LT_QMARK] = ACTIONS(1),
    [anon_sym_QMARK_GT] = ACTIONS(1),
    [anon_sym_LT_SLASH] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [sym_start_tag_name] = ACTIONS(1),
    [sym_script_start_tag_name] = ACTIONS(1),
    [sym_style_start_tag_name] = ACTIONS(1),
    [sym_end_tag_name] = ACTIONS(1),
    [sym_erroneous_end_tag_name] = ACTIONS(1),
    [sym_implicit_end_tag] = ACTIONS(1),
    [sym_raw_text] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
  },
  [1] = {
    [sym_fragment] = STATE(106),
    [sym_doctype] = STATE(13),
    [sym_cdata] = STATE(13),
    [sym_markup_content] = STATE(6),
    [sym_standard_markup_element] = STATE(13),
    [sym_element] = STATE(14),
    [sym_script_element] = STATE(14),
    [sym_style_element] = STATE(14),
    [sym_markup_opening_tag] = STATE(5),
    [sym_script_start_tag] = STATE(71),
    [sym_style_start_tag] = STATE(70),
    [sym_markup_singleton_tag] = STATE(16),
    [sym_declaration_tag] = STATE(16),
    [sym_erroneous_end_tag] = STATE(13),
    [aux_sym_fragment_repeat1] = STATE(6),
    [ts_builtin_sym_end] = ACTIONS(5),
    [anon_sym_LT_BANG] = ACTIONS(7),
    [anon_sym_LT_BANG_LBRACKCDATA_LBRACK] = ACTIONS(9),
    [anon_sym_LT] = ACTIONS(11),
    [anon_sym_LT_QMARK] = ACTIONS(13),
    [anon_sym_LT_SLASH] = ACTIONS(15),
    [sym_text_] = ACTIONS(17),
    [sym_comment] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 16,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(19), 1,
      anon_sym_LT_BANG,
    ACTIONS(21), 1,
      anon_sym_LT_BANG_LBRACKCDATA_LBRACK,
    ACTIONS(23), 1,
      anon_sym_LT,
    ACTIONS(25), 1,
      anon_sym_LT_QMARK,
    ACTIONS(27), 1,
      anon_sym_LT_SLASH,
    ACTIONS(29), 1,
      sym_text_,
    ACTIONS(31), 1,
      sym_implicit_end_tag,
    STATE(2), 1,
      sym_markup_opening_tag,
    STATE(20), 1,
      sym_markup_closing_tag,
    STATE(66), 1,
      sym_script_start_tag,
    STATE(68), 1,
      sym_style_start_tag,
    STATE(4), 2,
      sym_markup_content,
      aux_sym_fragment_repeat1,
    STATE(21), 2,
      sym_markup_singleton_tag,
      sym_declaration_tag,
    STATE(24), 3,
      sym_element,
      sym_script_element,
      sym_style_element,
    STATE(26), 4,
      sym_doctype,
      sym_cdata,
      sym_standard_markup_element,
      sym_erroneous_end_tag,
  [56] = 16,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(19), 1,
      anon_sym_LT_BANG,
    ACTIONS(21), 1,
      anon_sym_LT_BANG_LBRACKCDATA_LBRACK,
    ACTIONS(23), 1,
      anon_sym_LT,
    ACTIONS(25), 1,
      anon_sym_LT_QMARK,
    ACTIONS(29), 1,
      sym_text_,
    ACTIONS(33), 1,
      anon_sym_LT_SLASH,
    ACTIONS(35), 1,
      sym_implicit_end_tag,
    STATE(2), 1,
      sym_markup_opening_tag,
    STATE(43), 1,
      sym_markup_closing_tag,
    STATE(66), 1,
      sym_script_start_tag,
    STATE(68), 1,
      sym_style_start_tag,
    STATE(8), 2,
      sym_markup_content,
      aux_sym_fragment_repeat1,
    STATE(21), 2,
      sym_markup_singleton_tag,
      sym_declaration_tag,
    STATE(24), 3,
      sym_element,
      sym_script_element,
      sym_style_element,
    STATE(26), 4,
      sym_doctype,
      sym_cdata,
      sym_standard_markup_element,
      sym_erroneous_end_tag,
  [112] = 16,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(19), 1,
      anon_sym_LT_BANG,
    ACTIONS(21), 1,
      anon_sym_LT_BANG_LBRACKCDATA_LBRACK,
    ACTIONS(23), 1,
      anon_sym_LT,
    ACTIONS(25), 1,
      anon_sym_LT_QMARK,
    ACTIONS(27), 1,
      anon_sym_LT_SLASH,
    ACTIONS(29), 1,
      sym_text_,
    ACTIONS(37), 1,
      sym_implicit_end_tag,
    STATE(2), 1,
      sym_markup_opening_tag,
    STATE(25), 1,
      sym_markup_closing_tag,
    STATE(66), 1,
      sym_script_start_tag,
    STATE(68), 1,
      sym_style_start_tag,
    STATE(8), 2,
      sym_markup_content,
      aux_sym_fragment_repeat1,
    STATE(21), 2,
      sym_markup_singleton_tag,
      sym_declaration_tag,
    STATE(24), 3,
      sym_element,
      sym_script_element,
      sym_style_element,
    STATE(26), 4,
      sym_doctype,
      sym_cdata,
      sym_standard_markup_element,
      sym_erroneous_end_tag,
  [168] = 16,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(19), 1,
      anon_sym_LT_BANG,
    ACTIONS(21), 1,
      anon_sym_LT_BANG_LBRACKCDATA_LBRACK,
    ACTIONS(23), 1,
      anon_sym_LT,
    ACTIONS(25), 1,
      anon_sym_LT_QMARK,
    ACTIONS(29), 1,
      sym_text_,
    ACTIONS(33), 1,
      anon_sym_LT_SLASH,
    ACTIONS(39), 1,
      sym_implicit_end_tag,
    STATE(2), 1,
      sym_markup_opening_tag,
    STATE(23), 1,
      sym_markup_closing_tag,
    STATE(66), 1,
      sym_script_start_tag,
    STATE(68), 1,
      sym_style_start_tag,
    STATE(3), 2,
      sym_markup_content,
      aux_sym_fragment_repeat1,
    STATE(21), 2,
      sym_markup_singleton_tag,
      sym_declaration_tag,
    STATE(24), 3,
      sym_element,
      sym_script_element,
      sym_style_element,
    STATE(26), 4,
      sym_doctype,
      sym_cdata,
      sym_standard_markup_element,
      sym_erroneous_end_tag,
  [224] = 15,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_LT_BANG,
    ACTIONS(9), 1,
      anon_sym_LT_BANG_LBRACKCDATA_LBRACK,
    ACTIONS(11), 1,
      anon_sym_LT,
    ACTIONS(13), 1,
      anon_sym_LT_QMARK,
    ACTIONS(15), 1,
      anon_sym_LT_SLASH,
    ACTIONS(17), 1,
      sym_text_,
    ACTIONS(41), 1,
      ts_builtin_sym_end,
    STATE(5), 1,
      sym_markup_opening_tag,
    STATE(70), 1,
      sym_style_start_tag,
    STATE(71), 1,
      sym_script_start_tag,
    STATE(7), 2,
      sym_markup_content,
      aux_sym_fragment_repeat1,
    STATE(16), 2,
      sym_markup_singleton_tag,
      sym_declaration_tag,
    STATE(14), 3,
      sym_element,
      sym_script_element,
      sym_style_element,
    STATE(13), 4,
      sym_doctype,
      sym_cdata,
      sym_standard_markup_element,
      sym_erroneous_end_tag,
  [277] = 15,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(43), 1,
      ts_builtin_sym_end,
    ACTIONS(45), 1,
      anon_sym_LT_BANG,
    ACTIONS(48), 1,
      anon_sym_LT_BANG_LBRACKCDATA_LBRACK,
    ACTIONS(51), 1,
      anon_sym_LT,
    ACTIONS(54), 1,
      anon_sym_LT_QMARK,
    ACTIONS(57), 1,
      anon_sym_LT_SLASH,
    ACTIONS(60), 1,
      sym_text_,
    STATE(5), 1,
      sym_markup_opening_tag,
    STATE(70), 1,
      sym_style_start_tag,
    STATE(71), 1,
      sym_script_start_tag,
    STATE(7), 2,
      sym_markup_content,
      aux_sym_fragment_repeat1,
    STATE(16), 2,
      sym_markup_singleton_tag,
      sym_declaration_tag,
    STATE(14), 3,
      sym_element,
      sym_script_element,
      sym_style_element,
    STATE(13), 4,
      sym_doctype,
      sym_cdata,
      sym_standard_markup_element,
      sym_erroneous_end_tag,
  [330] = 15,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(43), 1,
      sym_implicit_end_tag,
    ACTIONS(63), 1,
      anon_sym_LT_BANG,
    ACTIONS(66), 1,
      anon_sym_LT_BANG_LBRACKCDATA_LBRACK,
    ACTIONS(69), 1,
      anon_sym_LT,
    ACTIONS(72), 1,
      anon_sym_LT_QMARK,
    ACTIONS(75), 1,
      anon_sym_LT_SLASH,
    ACTIONS(78), 1,
      sym_text_,
    STATE(2), 1,
      sym_markup_opening_tag,
    STATE(66), 1,
      sym_script_start_tag,
    STATE(68), 1,
      sym_style_start_tag,
    STATE(8), 2,
      sym_markup_content,
      aux_sym_fragment_repeat1,
    STATE(21), 2,
      sym_markup_singleton_tag,
      sym_declaration_tag,
    STATE(24), 3,
      sym_element,
      sym_script_element,
      sym_style_element,
    STATE(26), 4,
      sym_doctype,
      sym_cdata,
      sym_standard_markup_element,
      sym_erroneous_end_tag,
  [383] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(83), 2,
      sym_implicit_end_tag,
      sym_text_,
    ACTIONS(81), 5,
      anon_sym_LT_BANG,
      anon_sym_LT_BANG_LBRACKCDATA_LBRACK,
      anon_sym_LT,
      anon_sym_LT_QMARK,
      anon_sym_LT_SLASH,
  [398] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(83), 2,
      ts_builtin_sym_end,
      sym_text_,
    ACTIONS(81), 5,
      anon_sym_LT_BANG,
      anon_sym_LT_BANG_LBRACKCDATA_LBRACK,
      anon_sym_LT,
      anon_sym_LT_QMARK,
      anon_sym_LT_SLASH,
  [413] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(85), 2,
      ts_builtin_sym_end,
      sym_text_,
    ACTIONS(87), 5,
      anon_sym_LT_BANG,
      anon_sym_LT_BANG_LBRACKCDATA_LBRACK,
      anon_sym_LT,
      anon_sym_LT_QMARK,
      anon_sym_LT_SLASH,
  [428] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(89), 2,
      ts_builtin_sym_end,
      sym_text_,
    ACTIONS(91), 5,
      anon_sym_LT_BANG,
      anon_sym_LT_BANG_LBRACKCDATA_LBRACK,
      anon_sym_LT,
      anon_sym_LT_QMARK,
      anon_sym_LT_SLASH,
  [443] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(93), 2,
      ts_builtin_sym_end,
      sym_text_,
    ACTIONS(95), 5,
      anon_sym_LT_BANG,
      anon_sym_LT_BANG_LBRACKCDATA_LBRACK,
      anon_sym_LT,
      anon_sym_LT_QMARK,
      anon_sym_LT_SLASH,
  [458] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(97), 2,
      ts_builtin_sym_end,
      sym_text_,
    ACTIONS(99), 5,
      anon_sym_LT_BANG,
      anon_sym_LT_BANG_LBRACKCDATA_LBRACK,
      anon_sym_LT,
      anon_sym_LT_QMARK,
      anon_sym_LT_SLASH,
  [473] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(101), 2,
      ts_builtin_sym_end,
      sym_text_,
    ACTIONS(103), 5,
      anon_sym_LT_BANG,
      anon_sym_LT_BANG_LBRACKCDATA_LBRACK,
      anon_sym_LT,
      anon_sym_LT_QMARK,
      anon_sym_LT_SLASH,
  [488] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(105), 2,
      ts_builtin_sym_end,
      sym_text_,
    ACTIONS(107), 5,
      anon_sym_LT_BANG,
      anon_sym_LT_BANG_LBRACKCDATA_LBRACK,
      anon_sym_LT,
      anon_sym_LT_QMARK,
      anon_sym_LT_SLASH,
  [503] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(111), 2,
      sym_implicit_end_tag,
      sym_text_,
    ACTIONS(109), 5,
      anon_sym_LT_BANG,
      anon_sym_LT_BANG_LBRACKCDATA_LBRACK,
      anon_sym_LT,
      anon_sym_LT_QMARK,
      anon_sym_LT_SLASH,
  [518] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(115), 2,
      sym_implicit_end_tag,
      sym_text_,
    ACTIONS(113), 5,
      anon_sym_LT_BANG,
      anon_sym_LT_BANG_LBRACKCDATA_LBRACK,
      anon_sym_LT,
      anon_sym_LT_QMARK,
      anon_sym_LT_SLASH,
  [533] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(119), 2,
      sym_implicit_end_tag,
      sym_text_,
    ACTIONS(117), 5,
      anon_sym_LT_BANG,
      anon_sym_LT_BANG_LBRACKCDATA_LBRACK,
      anon_sym_LT,
      anon_sym_LT_QMARK,
      anon_sym_LT_SLASH,
  [548] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(123), 2,
      sym_implicit_end_tag,
      sym_text_,
    ACTIONS(121), 5,
      anon_sym_LT_BANG,
      anon_sym_LT_BANG_LBRACKCDATA_LBRACK,
      anon_sym_LT,
      anon_sym_LT_QMARK,
      anon_sym_LT_SLASH,
  [563] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(105), 2,
      sym_implicit_end_tag,
      sym_text_,
    ACTIONS(107), 5,
      anon_sym_LT_BANG,
      anon_sym_LT_BANG_LBRACKCDATA_LBRACK,
      anon_sym_LT,
      anon_sym_LT_QMARK,
      anon_sym_LT_SLASH,
  [578] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(115), 2,
      ts_builtin_sym_end,
      sym_text_,
    ACTIONS(113), 5,
      anon_sym_LT_BANG,
      anon_sym_LT_BANG_LBRACKCDATA_LBRACK,
      anon_sym_LT,
      anon_sym_LT_QMARK,
      anon_sym_LT_SLASH,
  [593] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(123), 2,
      ts_builtin_sym_end,
      sym_text_,
    ACTIONS(121), 5,
      anon_sym_LT_BANG,
      anon_sym_LT_BANG_LBRACKCDATA_LBRACK,
      anon_sym_LT,
      anon_sym_LT_QMARK,
      anon_sym_LT_SLASH,
  [608] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(97), 2,
      sym_implicit_end_tag,
      sym_text_,
    ACTIONS(99), 5,
      anon_sym_LT_BANG,
      anon_sym_LT_BANG_LBRACKCDATA_LBRACK,
      anon_sym_LT,
      anon_sym_LT_QMARK,
      anon_sym_LT_SLASH,
  [623] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(127), 2,
      sym_implicit_end_tag,
      sym_text_,
    ACTIONS(125), 5,
      anon_sym_LT_BANG,
      anon_sym_LT_BANG_LBRACKCDATA_LBRACK,
      anon_sym_LT,
      anon_sym_LT_QMARK,
      anon_sym_LT_SLASH,
  [638] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(93), 2,
      sym_implicit_end_tag,
      sym_text_,
    ACTIONS(95), 5,
      anon_sym_LT_BANG,
      anon_sym_LT_BANG_LBRACKCDATA_LBRACK,
      anon_sym_LT,
      anon_sym_LT_QMARK,
      anon_sym_LT_SLASH,
  [653] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(131), 2,
      sym_implicit_end_tag,
      sym_text_,
    ACTIONS(129), 5,
      anon_sym_LT_BANG,
      anon_sym_LT_BANG_LBRACKCDATA_LBRACK,
      anon_sym_LT,
      anon_sym_LT_QMARK,
      anon_sym_LT_SLASH,
  [668] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(111), 2,
      ts_builtin_sym_end,
      sym_text_,
    ACTIONS(109), 5,
      anon_sym_LT_BANG,
      anon_sym_LT_BANG_LBRACKCDATA_LBRACK,
      anon_sym_LT,
      anon_sym_LT_QMARK,
      anon_sym_LT_SLASH,
  [683] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(135), 2,
      sym_implicit_end_tag,
      sym_text_,
    ACTIONS(133), 5,
      anon_sym_LT_BANG,
      anon_sym_LT_BANG_LBRACKCDATA_LBRACK,
      anon_sym_LT,
      anon_sym_LT_QMARK,
      anon_sym_LT_SLASH,
  [698] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(139), 2,
      sym_implicit_end_tag,
      sym_text_,
    ACTIONS(137), 5,
      anon_sym_LT_BANG,
      anon_sym_LT_BANG_LBRACKCDATA_LBRACK,
      anon_sym_LT,
      anon_sym_LT_QMARK,
      anon_sym_LT_SLASH,
  [713] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(143), 2,
      sym_implicit_end_tag,
      sym_text_,
    ACTIONS(141), 5,
      anon_sym_LT_BANG,
      anon_sym_LT_BANG_LBRACKCDATA_LBRACK,
      anon_sym_LT,
      anon_sym_LT_QMARK,
      anon_sym_LT_SLASH,
  [728] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(85), 2,
      sym_implicit_end_tag,
      sym_text_,
    ACTIONS(87), 5,
      anon_sym_LT_BANG,
      anon_sym_LT_BANG_LBRACKCDATA_LBRACK,
      anon_sym_LT,
      anon_sym_LT_QMARK,
      anon_sym_LT_SLASH,
  [743] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(139), 2,
      ts_builtin_sym_end,
      sym_text_,
    ACTIONS(137), 5,
      anon_sym_LT_BANG,
      anon_sym_LT_BANG_LBRACKCDATA_LBRACK,
      anon_sym_LT,
      anon_sym_LT_QMARK,
      anon_sym_LT_SLASH,
  [758] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(147), 2,
      sym_implicit_end_tag,
      sym_text_,
    ACTIONS(145), 5,
      anon_sym_LT_BANG,
      anon_sym_LT_BANG_LBRACKCDATA_LBRACK,
      anon_sym_LT,
      anon_sym_LT_QMARK,
      anon_sym_LT_SLASH,
  [773] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(131), 2,
      ts_builtin_sym_end,
      sym_text_,
    ACTIONS(129), 5,
      anon_sym_LT_BANG,
      anon_sym_LT_BANG_LBRACKCDATA_LBRACK,
      anon_sym_LT,
      anon_sym_LT_QMARK,
      anon_sym_LT_SLASH,
  [788] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(151), 2,
      sym_implicit_end_tag,
      sym_text_,
    ACTIONS(149), 5,
      anon_sym_LT_BANG,
      anon_sym_LT_BANG_LBRACKCDATA_LBRACK,
      anon_sym_LT,
      anon_sym_LT_QMARK,
      anon_sym_LT_SLASH,
  [803] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(155), 2,
      sym_implicit_end_tag,
      sym_text_,
    ACTIONS(153), 5,
      anon_sym_LT_BANG,
      anon_sym_LT_BANG_LBRACKCDATA_LBRACK,
      anon_sym_LT,
      anon_sym_LT_QMARK,
      anon_sym_LT_SLASH,
  [818] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(159), 2,
      sym_implicit_end_tag,
      sym_text_,
    ACTIONS(157), 5,
      anon_sym_LT_BANG,
      anon_sym_LT_BANG_LBRACKCDATA_LBRACK,
      anon_sym_LT,
      anon_sym_LT_QMARK,
      anon_sym_LT_SLASH,
  [833] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(101), 2,
      sym_implicit_end_tag,
      sym_text_,
    ACTIONS(103), 5,
      anon_sym_LT_BANG,
      anon_sym_LT_BANG_LBRACKCDATA_LBRACK,
      anon_sym_LT,
      anon_sym_LT_QMARK,
      anon_sym_LT_SLASH,
  [848] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(135), 2,
      ts_builtin_sym_end,
      sym_text_,
    ACTIONS(133), 5,
      anon_sym_LT_BANG,
      anon_sym_LT_BANG_LBRACKCDATA_LBRACK,
      anon_sym_LT,
      anon_sym_LT_QMARK,
      anon_sym_LT_SLASH,
  [863] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(143), 2,
      ts_builtin_sym_end,
      sym_text_,
    ACTIONS(141), 5,
      anon_sym_LT_BANG,
      anon_sym_LT_BANG_LBRACKCDATA_LBRACK,
      anon_sym_LT,
      anon_sym_LT_QMARK,
      anon_sym_LT_SLASH,
  [878] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(89), 2,
      sym_implicit_end_tag,
      sym_text_,
    ACTIONS(91), 5,
      anon_sym_LT_BANG,
      anon_sym_LT_BANG_LBRACKCDATA_LBRACK,
      anon_sym_LT,
      anon_sym_LT_QMARK,
      anon_sym_LT_SLASH,
  [893] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(127), 2,
      ts_builtin_sym_end,
      sym_text_,
    ACTIONS(125), 5,
      anon_sym_LT_BANG,
      anon_sym_LT_BANG_LBRACKCDATA_LBRACK,
      anon_sym_LT,
      anon_sym_LT_QMARK,
      anon_sym_LT_SLASH,
  [908] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(119), 2,
      ts_builtin_sym_end,
      sym_text_,
    ACTIONS(117), 5,
      anon_sym_LT_BANG,
      anon_sym_LT_BANG_LBRACKCDATA_LBRACK,
      anon_sym_LT,
      anon_sym_LT_QMARK,
      anon_sym_LT_SLASH,
  [923] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(151), 2,
      ts_builtin_sym_end,
      sym_text_,
    ACTIONS(149), 5,
      anon_sym_LT_BANG,
      anon_sym_LT_BANG_LBRACKCDATA_LBRACK,
      anon_sym_LT,
      anon_sym_LT_QMARK,
      anon_sym_LT_SLASH,
  [938] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(159), 2,
      ts_builtin_sym_end,
      sym_text_,
    ACTIONS(157), 5,
      anon_sym_LT_BANG,
      anon_sym_LT_BANG_LBRACKCDATA_LBRACK,
      anon_sym_LT,
      anon_sym_LT_QMARK,
      anon_sym_LT_SLASH,
  [953] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(161), 1,
      anon_sym_GT,
    ACTIONS(163), 1,
      anon_sym_SLASH_GT,
    ACTIONS(165), 1,
      sym_markup_attribute_name,
    STATE(49), 2,
      sym_markup_attribute,
      aux_sym_markup_opening_tag_repeat1,
  [970] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(165), 1,
      sym_markup_attribute_name,
    ACTIONS(167), 1,
      anon_sym_GT,
    ACTIONS(169), 1,
      anon_sym_SLASH_GT,
    STATE(51), 2,
      sym_markup_attribute,
      aux_sym_markup_opening_tag_repeat1,
  [987] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(173), 1,
      sym_markup_attribute_name,
    ACTIONS(171), 2,
      anon_sym_GT,
      anon_sym_SLASH_GT,
    STATE(49), 2,
      sym_markup_attribute,
      aux_sym_markup_opening_tag_repeat1,
  [1002] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(165), 1,
      sym_markup_attribute_name,
    ACTIONS(167), 1,
      anon_sym_GT,
    ACTIONS(176), 1,
      anon_sym_SLASH_GT,
    STATE(47), 2,
      sym_markup_attribute,
      aux_sym_markup_opening_tag_repeat1,
  [1019] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(161), 1,
      anon_sym_GT,
    ACTIONS(165), 1,
      sym_markup_attribute_name,
    ACTIONS(178), 1,
      anon_sym_SLASH_GT,
    STATE(49), 2,
      sym_markup_attribute,
      aux_sym_markup_opening_tag_repeat1,
  [1036] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(180), 1,
      anon_sym_GT,
    ACTIONS(182), 1,
      sym_markup_attribute_name,
    STATE(57), 2,
      sym_markup_attribute,
      aux_sym_markup_opening_tag_repeat1,
  [1050] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(184), 1,
      anon_sym_QMARK_GT,
    ACTIONS(186), 1,
      sym_markup_attribute_name,
    STATE(65), 2,
      sym_markup_attribute,
      aux_sym_markup_opening_tag_repeat1,
  [1064] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(171), 1,
      anon_sym_GT,
    ACTIONS(188), 1,
      sym_markup_attribute_name,
    STATE(54), 2,
      sym_markup_attribute,
      aux_sym_markup_opening_tag_repeat1,
  [1078] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(191), 1,
      sym_attribute_value,
    ACTIONS(193), 1,
      anon_sym_SQUOTE,
    ACTIONS(195), 1,
      anon_sym_DQUOTE,
    STATE(67), 1,
      sym_quoted_attribute_value,
  [1094] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(182), 1,
      sym_markup_attribute_name,
    ACTIONS(197), 1,
      anon_sym_GT,
    STATE(54), 2,
      sym_markup_attribute,
      aux_sym_markup_opening_tag_repeat1,
  [1108] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(182), 1,
      sym_markup_attribute_name,
    ACTIONS(199), 1,
      anon_sym_GT,
    STATE(54), 2,
      sym_markup_attribute,
      aux_sym_markup_opening_tag_repeat1,
  [1122] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(201), 1,
      sym_attribute_value,
    ACTIONS(203), 1,
      anon_sym_SQUOTE,
    ACTIONS(205), 1,
      anon_sym_DQUOTE,
    STATE(91), 1,
      sym_quoted_attribute_value,
  [1138] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(207), 1,
      sym_attribute_value,
    ACTIONS(209), 1,
      anon_sym_SQUOTE,
    ACTIONS(211), 1,
      anon_sym_DQUOTE,
    STATE(86), 1,
      sym_quoted_attribute_value,
  [1154] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(186), 1,
      sym_markup_attribute_name,
    ACTIONS(213), 1,
      anon_sym_QMARK_GT,
    STATE(64), 2,
      sym_markup_attribute,
      aux_sym_markup_opening_tag_repeat1,
  [1168] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(186), 1,
      sym_markup_attribute_name,
    ACTIONS(215), 1,
      anon_sym_QMARK_GT,
    STATE(60), 2,
      sym_markup_attribute,
      aux_sym_markup_opening_tag_repeat1,
  [1182] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(182), 1,
      sym_markup_attribute_name,
    ACTIONS(217), 1,
      anon_sym_GT,
    STATE(56), 2,
      sym_markup_attribute,
      aux_sym_markup_opening_tag_repeat1,
  [1196] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(221), 1,
      anon_sym_EQ,
    ACTIONS(219), 3,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      sym_markup_attribute_name,
  [1208] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(171), 1,
      anon_sym_QMARK_GT,
    ACTIONS(223), 1,
      sym_markup_attribute_name,
    STATE(64), 2,
      sym_markup_attribute,
      aux_sym_markup_opening_tag_repeat1,
  [1222] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(186), 1,
      sym_markup_attribute_name,
    ACTIONS(226), 1,
      anon_sym_QMARK_GT,
    STATE(64), 2,
      sym_markup_attribute,
      aux_sym_markup_opening_tag_repeat1,
  [1236] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(228), 1,
      anon_sym_LT_SLASH,
    ACTIONS(230), 1,
      sym_raw_text,
    STATE(17), 1,
      sym_markup_closing_tag,
  [1249] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(232), 3,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      sym_markup_attribute_name,
  [1258] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(228), 1,
      anon_sym_LT_SLASH,
    ACTIONS(234), 1,
      sym_raw_text,
    STATE(9), 1,
      sym_markup_closing_tag,
  [1271] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(236), 3,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      sym_markup_attribute_name,
  [1280] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(238), 1,
      anon_sym_LT_SLASH,
    ACTIONS(240), 1,
      sym_raw_text,
    STATE(10), 1,
      sym_markup_closing_tag,
  [1293] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(238), 1,
      anon_sym_LT_SLASH,
    ACTIONS(242), 1,
      sym_raw_text,
    STATE(28), 1,
      sym_markup_closing_tag,
  [1306] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(244), 3,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      sym_markup_attribute_name,
  [1315] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(246), 1,
      anon_sym_EQ,
    ACTIONS(219), 2,
      anon_sym_GT,
      sym_markup_attribute_name,
  [1326] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(219), 1,
      anon_sym_QMARK_GT,
    ACTIONS(248), 1,
      anon_sym_EQ,
    ACTIONS(250), 1,
      sym_markup_attribute_name,
  [1339] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(252), 1,
      sym_start_tag_name,
    ACTIONS(254), 1,
      sym_script_start_tag_name,
    ACTIONS(256), 1,
      sym_style_start_tag_name,
  [1352] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(254), 1,
      sym_script_start_tag_name,
    ACTIONS(256), 1,
      sym_style_start_tag_name,
    ACTIONS(258), 1,
      sym_start_tag_name,
  [1365] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(244), 1,
      anon_sym_QMARK_GT,
    ACTIONS(260), 1,
      sym_markup_attribute_name,
  [1375] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(228), 1,
      anon_sym_LT_SLASH,
    STATE(19), 1,
      sym_markup_closing_tag,
  [1385] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(262), 1,
      sym_end_tag_name,
    ACTIONS(264), 1,
      sym_erroneous_end_tag_name,
  [1395] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(266), 1,
      anon_sym_DQUOTE,
    ACTIONS(268), 1,
      aux_sym_quoted_attribute_value_token2,
  [1405] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(270), 1,
      anon_sym_DQUOTE,
    ACTIONS(272), 1,
      aux_sym_quoted_attribute_value_token2,
  [1415] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(270), 1,
      anon_sym_SQUOTE,
    ACTIONS(274), 1,
      aux_sym_quoted_attribute_value_token1,
  [1425] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(276), 2,
      sym_raw_text,
      anon_sym_LT_SLASH,
  [1433] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(278), 2,
      sym_raw_text,
      anon_sym_LT_SLASH,
  [1441] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(266), 1,
      anon_sym_SQUOTE,
    ACTIONS(280), 1,
      aux_sym_quoted_attribute_value_token1,
  [1451] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(232), 2,
      anon_sym_GT,
      sym_markup_attribute_name,
  [1459] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(244), 2,
      anon_sym_GT,
      sym_markup_attribute_name,
  [1467] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(236), 2,
      anon_sym_GT,
      sym_markup_attribute_name,
  [1475] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(282), 2,
      sym_raw_text,
      anon_sym_LT_SLASH,
  [1483] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(284), 2,
      sym_raw_text,
      anon_sym_LT_SLASH,
  [1491] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(232), 1,
      anon_sym_QMARK_GT,
    ACTIONS(286), 1,
      sym_markup_attribute_name,
  [1501] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(288), 1,
      anon_sym_DQUOTE,
    ACTIONS(290), 1,
      aux_sym_quoted_attribute_value_token2,
  [1511] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(236), 1,
      anon_sym_QMARK_GT,
    ACTIONS(292), 1,
      sym_markup_attribute_name,
  [1521] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(238), 1,
      anon_sym_LT_SLASH,
    STATE(45), 1,
      sym_markup_closing_tag,
  [1531] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(288), 1,
      anon_sym_SQUOTE,
    ACTIONS(294), 1,
      aux_sym_quoted_attribute_value_token1,
  [1541] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(238), 1,
      anon_sym_LT_SLASH,
    STATE(44), 1,
      sym_markup_closing_tag,
  [1551] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(228), 1,
      anon_sym_LT_SLASH,
    STATE(36), 1,
      sym_markup_closing_tag,
  [1561] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(264), 1,
      sym_erroneous_end_tag_name,
    ACTIONS(296), 1,
      sym_end_tag_name,
  [1571] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(298), 1,
      anon_sym_GT,
  [1578] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(300), 1,
      anon_sym_GT,
  [1585] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(302), 1,
      anon_sym_RBRACK_RBRACK_GT,
  [1592] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(304), 1,
      anon_sym_SQUOTE,
  [1599] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(306), 1,
      anon_sym_RBRACK_RBRACK_GT,
  [1606] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(308), 1,
      anon_sym_GT,
  [1613] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(310), 1,
      aux_sym_doctype_token1,
  [1620] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(312), 1,
      ts_builtin_sym_end,
  [1627] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(314), 1,
      anon_sym_GT,
  [1634] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(316), 1,
      sym_erroneous_end_tag_name,
  [1641] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(296), 1,
      sym_end_tag_name,
  [1648] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(318), 1,
      anon_sym_GT,
  [1655] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(320), 1,
      anon_sym_SQUOTE,
  [1662] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(320), 1,
      anon_sym_DQUOTE,
  [1669] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(322), 1,
      sym_start_tag_name,
  [1676] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(324), 1,
      anon_sym_GT,
  [1683] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(326), 1,
      sym_doctype_,
  [1690] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(328), 1,
      anon_sym_SQUOTE,
  [1697] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(328), 1,
      anon_sym_DQUOTE,
  [1704] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(330), 1,
      aux_sym_cdata_token1,
  [1711] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(332), 1,
      aux_sym_cdata_token1,
  [1718] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(334), 1,
      sym_start_tag_name,
  [1725] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(264), 1,
      sym_erroneous_end_tag_name,
  [1732] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(336), 1,
      aux_sym_doctype_token1,
  [1739] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(304), 1,
      anon_sym_DQUOTE,
  [1746] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(262), 1,
      sym_end_tag_name,
  [1753] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(338), 1,
      sym_doctype_,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 56,
  [SMALL_STATE(4)] = 112,
  [SMALL_STATE(5)] = 168,
  [SMALL_STATE(6)] = 224,
  [SMALL_STATE(7)] = 277,
  [SMALL_STATE(8)] = 330,
  [SMALL_STATE(9)] = 383,
  [SMALL_STATE(10)] = 398,
  [SMALL_STATE(11)] = 413,
  [SMALL_STATE(12)] = 428,
  [SMALL_STATE(13)] = 443,
  [SMALL_STATE(14)] = 458,
  [SMALL_STATE(15)] = 473,
  [SMALL_STATE(16)] = 488,
  [SMALL_STATE(17)] = 503,
  [SMALL_STATE(18)] = 518,
  [SMALL_STATE(19)] = 533,
  [SMALL_STATE(20)] = 548,
  [SMALL_STATE(21)] = 563,
  [SMALL_STATE(22)] = 578,
  [SMALL_STATE(23)] = 593,
  [SMALL_STATE(24)] = 608,
  [SMALL_STATE(25)] = 623,
  [SMALL_STATE(26)] = 638,
  [SMALL_STATE(27)] = 653,
  [SMALL_STATE(28)] = 668,
  [SMALL_STATE(29)] = 683,
  [SMALL_STATE(30)] = 698,
  [SMALL_STATE(31)] = 713,
  [SMALL_STATE(32)] = 728,
  [SMALL_STATE(33)] = 743,
  [SMALL_STATE(34)] = 758,
  [SMALL_STATE(35)] = 773,
  [SMALL_STATE(36)] = 788,
  [SMALL_STATE(37)] = 803,
  [SMALL_STATE(38)] = 818,
  [SMALL_STATE(39)] = 833,
  [SMALL_STATE(40)] = 848,
  [SMALL_STATE(41)] = 863,
  [SMALL_STATE(42)] = 878,
  [SMALL_STATE(43)] = 893,
  [SMALL_STATE(44)] = 908,
  [SMALL_STATE(45)] = 923,
  [SMALL_STATE(46)] = 938,
  [SMALL_STATE(47)] = 953,
  [SMALL_STATE(48)] = 970,
  [SMALL_STATE(49)] = 987,
  [SMALL_STATE(50)] = 1002,
  [SMALL_STATE(51)] = 1019,
  [SMALL_STATE(52)] = 1036,
  [SMALL_STATE(53)] = 1050,
  [SMALL_STATE(54)] = 1064,
  [SMALL_STATE(55)] = 1078,
  [SMALL_STATE(56)] = 1094,
  [SMALL_STATE(57)] = 1108,
  [SMALL_STATE(58)] = 1122,
  [SMALL_STATE(59)] = 1138,
  [SMALL_STATE(60)] = 1154,
  [SMALL_STATE(61)] = 1168,
  [SMALL_STATE(62)] = 1182,
  [SMALL_STATE(63)] = 1196,
  [SMALL_STATE(64)] = 1208,
  [SMALL_STATE(65)] = 1222,
  [SMALL_STATE(66)] = 1236,
  [SMALL_STATE(67)] = 1249,
  [SMALL_STATE(68)] = 1258,
  [SMALL_STATE(69)] = 1271,
  [SMALL_STATE(70)] = 1280,
  [SMALL_STATE(71)] = 1293,
  [SMALL_STATE(72)] = 1306,
  [SMALL_STATE(73)] = 1315,
  [SMALL_STATE(74)] = 1326,
  [SMALL_STATE(75)] = 1339,
  [SMALL_STATE(76)] = 1352,
  [SMALL_STATE(77)] = 1365,
  [SMALL_STATE(78)] = 1375,
  [SMALL_STATE(79)] = 1385,
  [SMALL_STATE(80)] = 1395,
  [SMALL_STATE(81)] = 1405,
  [SMALL_STATE(82)] = 1415,
  [SMALL_STATE(83)] = 1425,
  [SMALL_STATE(84)] = 1433,
  [SMALL_STATE(85)] = 1441,
  [SMALL_STATE(86)] = 1451,
  [SMALL_STATE(87)] = 1459,
  [SMALL_STATE(88)] = 1467,
  [SMALL_STATE(89)] = 1475,
  [SMALL_STATE(90)] = 1483,
  [SMALL_STATE(91)] = 1491,
  [SMALL_STATE(92)] = 1501,
  [SMALL_STATE(93)] = 1511,
  [SMALL_STATE(94)] = 1521,
  [SMALL_STATE(95)] = 1531,
  [SMALL_STATE(96)] = 1541,
  [SMALL_STATE(97)] = 1551,
  [SMALL_STATE(98)] = 1561,
  [SMALL_STATE(99)] = 1571,
  [SMALL_STATE(100)] = 1578,
  [SMALL_STATE(101)] = 1585,
  [SMALL_STATE(102)] = 1592,
  [SMALL_STATE(103)] = 1599,
  [SMALL_STATE(104)] = 1606,
  [SMALL_STATE(105)] = 1613,
  [SMALL_STATE(106)] = 1620,
  [SMALL_STATE(107)] = 1627,
  [SMALL_STATE(108)] = 1634,
  [SMALL_STATE(109)] = 1641,
  [SMALL_STATE(110)] = 1648,
  [SMALL_STATE(111)] = 1655,
  [SMALL_STATE(112)] = 1662,
  [SMALL_STATE(113)] = 1669,
  [SMALL_STATE(114)] = 1676,
  [SMALL_STATE(115)] = 1683,
  [SMALL_STATE(116)] = 1690,
  [SMALL_STATE(117)] = 1697,
  [SMALL_STATE(118)] = 1704,
  [SMALL_STATE(119)] = 1711,
  [SMALL_STATE(120)] = 1718,
  [SMALL_STATE(121)] = 1725,
  [SMALL_STATE(122)] = 1732,
  [SMALL_STATE(123)] = 1739,
  [SMALL_STATE(124)] = 1746,
  [SMALL_STATE(125)] = 1753,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fragment, 0),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(115),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(119),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(75),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(113),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(108),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(125),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(118),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(76),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(120),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(79),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [33] = {.entry = {.count = 1, .reusable = false}}, SHIFT(98),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [41] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fragment, 1),
  [43] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_fragment_repeat1, 2),
  [45] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_fragment_repeat1, 2), SHIFT_REPEAT(115),
  [48] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_fragment_repeat1, 2), SHIFT_REPEAT(119),
  [51] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_fragment_repeat1, 2), SHIFT_REPEAT(75),
  [54] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_fragment_repeat1, 2), SHIFT_REPEAT(113),
  [57] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_fragment_repeat1, 2), SHIFT_REPEAT(108),
  [60] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_fragment_repeat1, 2), SHIFT_REPEAT(11),
  [63] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_fragment_repeat1, 2), SHIFT_REPEAT(125),
  [66] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_fragment_repeat1, 2), SHIFT_REPEAT(118),
  [69] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_fragment_repeat1, 2), SHIFT_REPEAT(76),
  [72] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_fragment_repeat1, 2), SHIFT_REPEAT(120),
  [75] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_fragment_repeat1, 2), SHIFT_REPEAT(121),
  [78] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_fragment_repeat1, 2), SHIFT_REPEAT(32),
  [81] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_style_element, 2),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_style_element, 2),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_markup_content, 1, .production_id = 1),
  [87] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_markup_content, 1, .production_id = 1),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_declaration_tag, 4, .production_id = 6),
  [91] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_declaration_tag, 4, .production_id = 6),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_markup_content, 1, .production_id = 2),
  [95] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_markup_content, 1, .production_id = 2),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_standard_markup_element, 1),
  [99] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_standard_markup_element, 1),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_markup_closing_tag, 3, .production_id = 3),
  [103] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_markup_closing_tag, 3, .production_id = 3),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_element, 1),
  [107] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_element, 1),
  [109] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_script_element, 2),
  [111] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_script_element, 2),
  [113] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_markup_singleton_tag, 4, .production_id = 6),
  [115] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_markup_singleton_tag, 4, .production_id = 6),
  [117] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_script_element, 3, .production_id = 5),
  [119] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_script_element, 3, .production_id = 5),
  [121] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_element, 2),
  [123] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_element, 2),
  [125] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_element, 3, .production_id = 5),
  [127] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_element, 3, .production_id = 5),
  [129] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_markup_singleton_tag, 3, .production_id = 3),
  [131] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_markup_singleton_tag, 3, .production_id = 3),
  [133] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_declaration_tag, 3, .production_id = 3),
  [135] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_declaration_tag, 3, .production_id = 3),
  [137] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_cdata, 3),
  [139] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_cdata, 3),
  [141] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_erroneous_end_tag, 3, .production_id = 4),
  [143] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_erroneous_end_tag, 3, .production_id = 4),
  [145] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_markup_opening_tag, 3, .production_id = 3),
  [147] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_markup_opening_tag, 3, .production_id = 3),
  [149] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_style_element, 3, .production_id = 5),
  [151] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_style_element, 3, .production_id = 5),
  [153] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_markup_opening_tag, 4, .production_id = 6),
  [155] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_markup_opening_tag, 4, .production_id = 6),
  [157] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_doctype, 4),
  [159] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_doctype, 4),
  [161] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [163] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [165] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [167] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [169] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [171] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_markup_opening_tag_repeat1, 2),
  [173] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_markup_opening_tag_repeat1, 2), SHIFT_REPEAT(63),
  [176] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [178] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [180] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [182] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [184] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [186] = {.entry = {.count = 1, .reusable = false}}, SHIFT(74),
  [188] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_markup_opening_tag_repeat1, 2), SHIFT_REPEAT(73),
  [191] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [193] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [195] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [197] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [199] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [201] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [203] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [205] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [207] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [209] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [211] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [213] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [215] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [217] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [219] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_markup_attribute, 1),
  [221] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [223] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_markup_opening_tag_repeat1, 2), SHIFT_REPEAT(74),
  [226] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [228] = {.entry = {.count = 1, .reusable = true}}, SHIFT(124),
  [230] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [232] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_markup_attribute, 3, .production_id = 7),
  [234] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [236] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_attribute_value, 3),
  [238] = {.entry = {.count = 1, .reusable = true}}, SHIFT(109),
  [240] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [242] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [244] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_attribute_value, 2),
  [246] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [248] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [250] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_markup_attribute, 1),
  [252] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [254] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [256] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [258] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [260] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_quoted_attribute_value, 2),
  [262] = {.entry = {.count = 1, .reusable = true}}, SHIFT(107),
  [264] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [266] = {.entry = {.count = 1, .reusable = false}}, SHIFT(77),
  [268] = {.entry = {.count = 1, .reusable = true}}, SHIFT(117),
  [270] = {.entry = {.count = 1, .reusable = false}}, SHIFT(72),
  [272] = {.entry = {.count = 1, .reusable = true}}, SHIFT(123),
  [274] = {.entry = {.count = 1, .reusable = true}}, SHIFT(102),
  [276] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_style_start_tag, 4, .production_id = 6),
  [278] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_script_start_tag, 4, .production_id = 6),
  [280] = {.entry = {.count = 1, .reusable = true}}, SHIFT(116),
  [282] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_style_start_tag, 3, .production_id = 3),
  [284] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_script_start_tag, 3, .production_id = 3),
  [286] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_markup_attribute, 3, .production_id = 7),
  [288] = {.entry = {.count = 1, .reusable = false}}, SHIFT(87),
  [290] = {.entry = {.count = 1, .reusable = true}}, SHIFT(112),
  [292] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_quoted_attribute_value, 3),
  [294] = {.entry = {.count = 1, .reusable = true}}, SHIFT(111),
  [296] = {.entry = {.count = 1, .reusable = true}}, SHIFT(114),
  [298] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [300] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [302] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [304] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [306] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [308] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [310] = {.entry = {.count = 1, .reusable = true}}, SHIFT(110),
  [312] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [314] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [316] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [318] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [320] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [322] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [324] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [326] = {.entry = {.count = 1, .reusable = true}}, SHIFT(105),
  [328] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [330] = {.entry = {.count = 1, .reusable = true}}, SHIFT(103),
  [332] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [334] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [336] = {.entry = {.count = 1, .reusable = true}}, SHIFT(104),
  [338] = {.entry = {.count = 1, .reusable = true}}, SHIFT(122),
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_html_external_scanner_create(void);
void tree_sitter_html_external_scanner_destroy(void *);
bool tree_sitter_html_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_html_external_scanner_serialize(void *, char *);
void tree_sitter_html_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_html(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_html_external_scanner_create,
      tree_sitter_html_external_scanner_destroy,
      tree_sitter_html_external_scanner_scan,
      tree_sitter_html_external_scanner_serialize,
      tree_sitter_html_external_scanner_deserialize,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
