#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 13
#define STATE_COUNT 122
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 48
#define ALIAS_COUNT 0
#define TOKEN_COUNT 29
#define EXTERNAL_TOKEN_COUNT 9
#define FIELD_COUNT 5
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define PRODUCTION_ID_COUNT 6

enum {
  anon_sym_LT_BANG = 1,
  aux_sym_doctype_token1 = 2,
  anon_sym_GT = 3,
  anon_sym_LT_BANG_LBRACKCDATA_LBRACK = 4,
  aux_sym_cdata_token1 = 5,
  anon_sym_RBRACK_RBRACK_GT = 6,
  sym__doctype = 7,
  anon_sym_LT = 8,
  anon_sym_SLASH_GT = 9,
  anon_sym_LT_QMARK = 10,
  anon_sym_QMARK_GT = 11,
  anon_sym_LT_SLASH = 12,
  anon_sym_EQ = 13,
  sym_markup_attribute_name = 14,
  sym_attribute_value = 15,
  anon_sym_SQUOTE = 16,
  aux_sym_quoted_attribute_value_token1 = 17,
  anon_sym_DQUOTE = 18,
  aux_sym_quoted_attribute_value_token2 = 19,
  sym_text_ = 20,
  sym_start_tag_name = 21,
  sym_script_start_tag_name = 22,
  sym_style_start_tag_name = 23,
  sym_end_tag_name = 24,
  sym_erroneous_end_tag_name = 25,
  sym_implicit_end_tag = 26,
  sym_raw_text = 27,
  sym_comment = 28,
  sym_fragment = 29,
  sym_doctype = 30,
  sym_cdata = 31,
  sym__node = 32,
  sym_markup_element = 33,
  sym_element = 34,
  sym_script_element = 35,
  sym_style_element = 36,
  sym_markup_opening_tag = 37,
  sym_script_start_tag = 38,
  sym_style_start_tag = 39,
  sym_markup_singleton_tag = 40,
  sym_declaration_tag = 41,
  sym_markup_closing_tag = 42,
  sym_erroneous_end_tag = 43,
  sym_markup_attribute = 44,
  sym_quoted_attribute_value = 45,
  aux_sym_fragment_repeat1 = 46,
  aux_sym_markup_opening_tag_repeat1 = 47,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LT_BANG] = "<!",
  [aux_sym_doctype_token1] = "doctype_token1",
  [anon_sym_GT] = ">",
  [anon_sym_LT_BANG_LBRACKCDATA_LBRACK] = "<![CDATA[",
  [aux_sym_cdata_token1] = "cdata_token1",
  [anon_sym_RBRACK_RBRACK_GT] = "]]>",
  [sym__doctype] = "doctype",
  [anon_sym_LT] = "<",
  [anon_sym_SLASH_GT] = "/>",
  [anon_sym_LT_QMARK] = "<\?",
  [anon_sym_QMARK_GT] = "\?>",
  [anon_sym_LT_SLASH] = "</",
  [anon_sym_EQ] = "=",
  [sym_markup_attribute_name] = "markup_attribute_name",
  [sym_attribute_value] = "attribute_value",
  [anon_sym_SQUOTE] = "'",
  [aux_sym_quoted_attribute_value_token1] = "attribute_value",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_quoted_attribute_value_token2] = "attribute_value",
  [sym_text_] = "text_",
  [sym_start_tag_name] = "start_tag_name",
  [sym_script_start_tag_name] = "script_start_tag_name",
  [sym_style_start_tag_name] = "style_start_tag_name",
  [sym_end_tag_name] = "end_tag_name",
  [sym_erroneous_end_tag_name] = "erroneous_end_tag_name",
  [sym_implicit_end_tag] = "implicit_end_tag",
  [sym_raw_text] = "raw_text",
  [sym_comment] = "comment",
  [sym_fragment] = "fragment",
  [sym_doctype] = "doctype",
  [sym_cdata] = "cdata",
  [sym__node] = "_node",
  [sym_markup_element] = "markup_element",
  [sym_element] = "element",
  [sym_script_element] = "script_element",
  [sym_style_element] = "style_element",
  [sym_markup_opening_tag] = "markup_opening_tag",
  [sym_script_start_tag] = "markup_opening_tag",
  [sym_style_start_tag] = "markup_opening_tag",
  [sym_markup_singleton_tag] = "markup_singleton_tag",
  [sym_declaration_tag] = "declaration_tag",
  [sym_markup_closing_tag] = "markup_closing_tag",
  [sym_erroneous_end_tag] = "erroneous_end_tag",
  [sym_markup_attribute] = "markup_attribute",
  [sym_quoted_attribute_value] = "quoted_attribute_value",
  [aux_sym_fragment_repeat1] = "fragment_repeat1",
  [aux_sym_markup_opening_tag_repeat1] = "markup_opening_tag_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LT_BANG] = anon_sym_LT_BANG,
  [aux_sym_doctype_token1] = aux_sym_doctype_token1,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_LT_BANG_LBRACKCDATA_LBRACK] = anon_sym_LT_BANG_LBRACKCDATA_LBRACK,
  [aux_sym_cdata_token1] = aux_sym_cdata_token1,
  [anon_sym_RBRACK_RBRACK_GT] = anon_sym_RBRACK_RBRACK_GT,
  [sym__doctype] = sym__doctype,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_SLASH_GT] = anon_sym_SLASH_GT,
  [anon_sym_LT_QMARK] = anon_sym_LT_QMARK,
  [anon_sym_QMARK_GT] = anon_sym_QMARK_GT,
  [anon_sym_LT_SLASH] = anon_sym_LT_SLASH,
  [anon_sym_EQ] = anon_sym_EQ,
  [sym_markup_attribute_name] = sym_markup_attribute_name,
  [sym_attribute_value] = sym_attribute_value,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [aux_sym_quoted_attribute_value_token1] = sym_attribute_value,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_quoted_attribute_value_token2] = sym_attribute_value,
  [sym_text_] = sym_text_,
  [sym_start_tag_name] = sym_start_tag_name,
  [sym_script_start_tag_name] = sym_script_start_tag_name,
  [sym_style_start_tag_name] = sym_style_start_tag_name,
  [sym_end_tag_name] = sym_end_tag_name,
  [sym_erroneous_end_tag_name] = sym_erroneous_end_tag_name,
  [sym_implicit_end_tag] = sym_implicit_end_tag,
  [sym_raw_text] = sym_raw_text,
  [sym_comment] = sym_comment,
  [sym_fragment] = sym_fragment,
  [sym_doctype] = sym_doctype,
  [sym_cdata] = sym_cdata,
  [sym__node] = sym__node,
  [sym_markup_element] = sym_markup_element,
  [sym_element] = sym_element,
  [sym_script_element] = sym_script_element,
  [sym_style_element] = sym_style_element,
  [sym_markup_opening_tag] = sym_markup_opening_tag,
  [sym_script_start_tag] = sym_markup_opening_tag,
  [sym_style_start_tag] = sym_markup_opening_tag,
  [sym_markup_singleton_tag] = sym_markup_singleton_tag,
  [sym_declaration_tag] = sym_declaration_tag,
  [sym_markup_closing_tag] = sym_markup_closing_tag,
  [sym_erroneous_end_tag] = sym_erroneous_end_tag,
  [sym_markup_attribute] = sym_markup_attribute,
  [sym_quoted_attribute_value] = sym_quoted_attribute_value,
  [aux_sym_fragment_repeat1] = aux_sym_fragment_repeat1,
  [aux_sym_markup_opening_tag_repeat1] = aux_sym_markup_opening_tag_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LT_BANG] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_doctype_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_BANG_LBRACKCDATA_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_cdata_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_RBRACK_RBRACK_GT] = {
    .visible = true,
    .named = false,
  },
  [sym__doctype] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_QMARK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_QMARK_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [sym_markup_attribute_name] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute_value] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_quoted_attribute_value_token1] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_quoted_attribute_value_token2] = {
    .visible = true,
    .named = true,
  },
  [sym_text_] = {
    .visible = true,
    .named = true,
  },
  [sym_start_tag_name] = {
    .visible = true,
    .named = true,
  },
  [sym_script_start_tag_name] = {
    .visible = true,
    .named = true,
  },
  [sym_style_start_tag_name] = {
    .visible = true,
    .named = true,
  },
  [sym_end_tag_name] = {
    .visible = true,
    .named = true,
  },
  [sym_erroneous_end_tag_name] = {
    .visible = true,
    .named = true,
  },
  [sym_implicit_end_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_raw_text] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_fragment] = {
    .visible = true,
    .named = true,
  },
  [sym_doctype] = {
    .visible = true,
    .named = true,
  },
  [sym_cdata] = {
    .visible = true,
    .named = true,
  },
  [sym__node] = {
    .visible = false,
    .named = true,
  },
  [sym_markup_element] = {
    .visible = true,
    .named = true,
  },
  [sym_element] = {
    .visible = true,
    .named = true,
  },
  [sym_script_element] = {
    .visible = true,
    .named = true,
  },
  [sym_style_element] = {
    .visible = true,
    .named = true,
  },
  [sym_markup_opening_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_script_start_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_style_start_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_markup_singleton_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_declaration_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_markup_closing_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_erroneous_end_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_markup_attribute] = {
    .visible = true,
    .named = true,
  },
  [sym_quoted_attribute_value] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_fragment_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_markup_opening_tag_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum {
  field_identifier = 1,
  field_markup_attribute_list = 2,
  field_markup_attribute_value = 3,
  field_markup_closing_tag = 4,
  field_markup_element_content = 5,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_identifier] = "identifier",
  [field_markup_attribute_list] = "markup_attribute_list",
  [field_markup_attribute_value] = "markup_attribute_value",
  [field_markup_closing_tag] = "markup_closing_tag",
  [field_markup_element_content] = "markup_element_content",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 3},
  [3] = {.index = 4, .length = 1},
  [4] = {.index = 5, .length = 2},
  [5] = {.index = 7, .length = 1},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_identifier, 1},
  [1] =
    {field_identifier, 1},
    {field_markup_closing_tag, 0},
    {field_markup_closing_tag, 2},
  [4] =
    {field_markup_element_content, 1},
  [5] =
    {field_identifier, 1},
    {field_markup_attribute_list, 2},
  [7] =
    {field_markup_attribute_value, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(25);
      if (lookahead == '"') ADVANCE(47);
      if (lookahead == '\'') ADVANCE(44);
      if (lookahead == '/') ADVANCE(6);
      if (lookahead == '<') ADVANCE(35);
      if (lookahead == '=') ADVANCE(40);
      if (lookahead == '>') ADVANCE(29);
      if (lookahead == '?') ADVANCE(7);
      if (lookahead == ']') ADVANCE(15);
      if (lookahead == 'D' ||
          lookahead == 'd') ADVANCE(18);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(47);
      if (lookahead == '\'') ADVANCE(44);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(1)
      if (lookahead != 0 &&
          (lookahead < '<' || '>' < lookahead)) ADVANCE(43);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(47);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(48);
      if (lookahead != 0) ADVANCE(49);
      END_STATE();
    case 3:
      if (lookahead == '\'') ADVANCE(44);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(45);
      if (lookahead != 0) ADVANCE(46);
      END_STATE();
    case 4:
      if (lookahead == '/') ADVANCE(6);
      if (lookahead == '=') ADVANCE(40);
      if (lookahead == '>') ADVANCE(29);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(4)
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\'' &&
          lookahead != '<') ADVANCE(42);
      END_STATE();
    case 5:
      if (lookahead == '=') ADVANCE(40);
      if (lookahead == '?') ADVANCE(41);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(5)
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\'' &&
          lookahead != '/' &&
          (lookahead < '<' || '>' < lookahead)) ADVANCE(42);
      END_STATE();
    case 6:
      if (lookahead == '>') ADVANCE(36);
      END_STATE();
    case 7:
      if (lookahead == '>') ADVANCE(38);
      END_STATE();
    case 8:
      if (lookahead == '>') ADVANCE(33);
      END_STATE();
    case 9:
      if (lookahead == 'A') ADVANCE(13);
      END_STATE();
    case 10:
      if (lookahead == 'A') ADVANCE(14);
      END_STATE();
    case 11:
      if (lookahead == 'C') ADVANCE(12);
      END_STATE();
    case 12:
      if (lookahead == 'D') ADVANCE(9);
      END_STATE();
    case 13:
      if (lookahead == 'T') ADVANCE(10);
      END_STATE();
    case 14:
      if (lookahead == '[') ADVANCE(30);
      END_STATE();
    case 15:
      if (lookahead == ']') ADVANCE(8);
      END_STATE();
    case 16:
      if (lookahead == 'C' ||
          lookahead == 'c') ADVANCE(20);
      END_STATE();
    case 17:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(34);
      END_STATE();
    case 18:
      if (lookahead == 'O' ||
          lookahead == 'o') ADVANCE(16);
      END_STATE();
    case 19:
      if (lookahead == 'P' ||
          lookahead == 'p') ADVANCE(17);
      END_STATE();
    case 20:
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(21);
      END_STATE();
    case 21:
      if (lookahead == 'Y' ||
          lookahead == 'y') ADVANCE(19);
      END_STATE();
    case 22:
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(27);
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(28);
      END_STATE();
    case 23:
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(31);
      if (lookahead != 0 &&
          lookahead != ']') ADVANCE(32);
      END_STATE();
    case 24:
      if (eof) ADVANCE(25);
      if (lookahead == '<') ADVANCE(35);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(50);
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(51);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_LT_BANG);
      if (lookahead == '[') ADVANCE(11);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(aux_sym_doctype_token1);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(27);
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(28);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(aux_sym_doctype_token1);
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(28);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_LT_BANG_LBRACKCDATA_LBRACK);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(aux_sym_cdata_token1);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(31);
      if (lookahead != 0 &&
          lookahead != ']') ADVANCE(32);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(aux_sym_cdata_token1);
      if (lookahead != 0 &&
          lookahead != ']') ADVANCE(32);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_RBRACK_RBRACK_GT);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym__doctype);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '!') ADVANCE(26);
      if (lookahead == '/') ADVANCE(39);
      if (lookahead == '?') ADVANCE(37);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_SLASH_GT);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_LT_QMARK);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_QMARK_GT);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_LT_SLASH);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_markup_attribute_name);
      if (lookahead == '>') ADVANCE(38);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '\'' &&
          lookahead != '/' &&
          lookahead != '<' &&
          lookahead != '=') ADVANCE(42);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_markup_attribute_name);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '\'' &&
          lookahead != '/' &&
          (lookahead < '<' || '>' < lookahead)) ADVANCE(42);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_attribute_value);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '\'' &&
          (lookahead < '<' || '>' < lookahead)) ADVANCE(43);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(aux_sym_quoted_attribute_value_token1);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(45);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(46);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(aux_sym_quoted_attribute_value_token1);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(46);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(aux_sym_quoted_attribute_value_token2);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(48);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(49);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(aux_sym_quoted_attribute_value_token2);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(49);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_text_);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(50);
      if (lookahead != 0 &&
          lookahead != '<' &&
          lookahead != '>') ADVANCE(51);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_text_);
      if (lookahead != 0 &&
          lookahead != '<' &&
          lookahead != '>') ADVANCE(51);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 24, .external_lex_state = 2},
  [2] = {.lex_state = 24, .external_lex_state = 3},
  [3] = {.lex_state = 24, .external_lex_state = 3},
  [4] = {.lex_state = 24, .external_lex_state = 3},
  [5] = {.lex_state = 24, .external_lex_state = 3},
  [6] = {.lex_state = 24, .external_lex_state = 3},
  [7] = {.lex_state = 24, .external_lex_state = 2},
  [8] = {.lex_state = 24, .external_lex_state = 2},
  [9] = {.lex_state = 24, .external_lex_state = 2},
  [10] = {.lex_state = 24, .external_lex_state = 2},
  [11] = {.lex_state = 24, .external_lex_state = 3},
  [12] = {.lex_state = 24, .external_lex_state = 3},
  [13] = {.lex_state = 24, .external_lex_state = 3},
  [14] = {.lex_state = 24, .external_lex_state = 2},
  [15] = {.lex_state = 24, .external_lex_state = 3},
  [16] = {.lex_state = 24, .external_lex_state = 2},
  [17] = {.lex_state = 24, .external_lex_state = 3},
  [18] = {.lex_state = 24, .external_lex_state = 2},
  [19] = {.lex_state = 24, .external_lex_state = 2},
  [20] = {.lex_state = 24, .external_lex_state = 3},
  [21] = {.lex_state = 24, .external_lex_state = 3},
  [22] = {.lex_state = 24, .external_lex_state = 3},
  [23] = {.lex_state = 24, .external_lex_state = 2},
  [24] = {.lex_state = 24, .external_lex_state = 3},
  [25] = {.lex_state = 24, .external_lex_state = 3},
  [26] = {.lex_state = 24, .external_lex_state = 3},
  [27] = {.lex_state = 24, .external_lex_state = 2},
  [28] = {.lex_state = 24, .external_lex_state = 3},
  [29] = {.lex_state = 24, .external_lex_state = 2},
  [30] = {.lex_state = 24, .external_lex_state = 3},
  [31] = {.lex_state = 24, .external_lex_state = 2},
  [32] = {.lex_state = 24, .external_lex_state = 3},
  [33] = {.lex_state = 24, .external_lex_state = 2},
  [34] = {.lex_state = 24, .external_lex_state = 2},
  [35] = {.lex_state = 24, .external_lex_state = 2},
  [36] = {.lex_state = 24, .external_lex_state = 3},
  [37] = {.lex_state = 24, .external_lex_state = 3},
  [38] = {.lex_state = 24, .external_lex_state = 3},
  [39] = {.lex_state = 24, .external_lex_state = 2},
  [40] = {.lex_state = 24, .external_lex_state = 2},
  [41] = {.lex_state = 24, .external_lex_state = 3},
  [42] = {.lex_state = 24, .external_lex_state = 2},
  [43] = {.lex_state = 4, .external_lex_state = 4},
  [44] = {.lex_state = 4, .external_lex_state = 4},
  [45] = {.lex_state = 4, .external_lex_state = 4},
  [46] = {.lex_state = 4, .external_lex_state = 4},
  [47] = {.lex_state = 4, .external_lex_state = 4},
  [48] = {.lex_state = 5, .external_lex_state = 2},
  [49] = {.lex_state = 4, .external_lex_state = 2},
  [50] = {.lex_state = 4, .external_lex_state = 2},
  [51] = {.lex_state = 4, .external_lex_state = 4},
  [52] = {.lex_state = 1, .external_lex_state = 2},
  [53] = {.lex_state = 4, .external_lex_state = 2},
  [54] = {.lex_state = 1, .external_lex_state = 2},
  [55] = {.lex_state = 5, .external_lex_state = 2},
  [56] = {.lex_state = 4, .external_lex_state = 2},
  [57] = {.lex_state = 4, .external_lex_state = 2},
  [58] = {.lex_state = 5, .external_lex_state = 2},
  [59] = {.lex_state = 5, .external_lex_state = 2},
  [60] = {.lex_state = 5, .external_lex_state = 2},
  [61] = {.lex_state = 1, .external_lex_state = 2},
  [62] = {.lex_state = 0, .external_lex_state = 5},
  [63] = {.lex_state = 5, .external_lex_state = 2},
  [64] = {.lex_state = 0, .external_lex_state = 6},
  [65] = {.lex_state = 4, .external_lex_state = 4},
  [66] = {.lex_state = 4, .external_lex_state = 4},
  [67] = {.lex_state = 0, .external_lex_state = 6},
  [68] = {.lex_state = 0, .external_lex_state = 5},
  [69] = {.lex_state = 4, .external_lex_state = 4},
  [70] = {.lex_state = 0, .external_lex_state = 5},
  [71] = {.lex_state = 4, .external_lex_state = 2},
  [72] = {.lex_state = 0, .external_lex_state = 5},
  [73] = {.lex_state = 3, .external_lex_state = 2},
  [74] = {.lex_state = 3, .external_lex_state = 2},
  [75] = {.lex_state = 0, .external_lex_state = 7},
  [76] = {.lex_state = 0, .external_lex_state = 5},
  [77] = {.lex_state = 0, .external_lex_state = 5},
  [78] = {.lex_state = 2, .external_lex_state = 2},
  [79] = {.lex_state = 0, .external_lex_state = 2},
  [80] = {.lex_state = 2, .external_lex_state = 2},
  [81] = {.lex_state = 0, .external_lex_state = 2},
  [82] = {.lex_state = 0, .external_lex_state = 7},
  [83] = {.lex_state = 4, .external_lex_state = 2},
  [84] = {.lex_state = 4, .external_lex_state = 2},
  [85] = {.lex_state = 4, .external_lex_state = 2},
  [86] = {.lex_state = 0, .external_lex_state = 5},
  [87] = {.lex_state = 5, .external_lex_state = 2},
  [88] = {.lex_state = 5, .external_lex_state = 2},
  [89] = {.lex_state = 5, .external_lex_state = 2},
  [90] = {.lex_state = 2, .external_lex_state = 2},
  [91] = {.lex_state = 0, .external_lex_state = 2},
  [92] = {.lex_state = 3, .external_lex_state = 2},
  [93] = {.lex_state = 0, .external_lex_state = 2},
  [94] = {.lex_state = 0, .external_lex_state = 5},
  [95] = {.lex_state = 0, .external_lex_state = 2},
  [96] = {.lex_state = 0, .external_lex_state = 8},
  [97] = {.lex_state = 0, .external_lex_state = 2},
  [98] = {.lex_state = 0, .external_lex_state = 2},
  [99] = {.lex_state = 22, .external_lex_state = 2},
  [100] = {.lex_state = 0, .external_lex_state = 2},
  [101] = {.lex_state = 0, .external_lex_state = 9},
  [102] = {.lex_state = 0, .external_lex_state = 2},
  [103] = {.lex_state = 0, .external_lex_state = 2},
  [104] = {.lex_state = 0, .external_lex_state = 2},
  [105] = {.lex_state = 0, .external_lex_state = 2},
  [106] = {.lex_state = 0, .external_lex_state = 2},
  [107] = {.lex_state = 23, .external_lex_state = 2},
  [108] = {.lex_state = 0, .external_lex_state = 2},
  [109] = {.lex_state = 0, .external_lex_state = 2},
  [110] = {.lex_state = 0, .external_lex_state = 2},
  [111] = {.lex_state = 0, .external_lex_state = 10},
  [112] = {.lex_state = 0, .external_lex_state = 2},
  [113] = {.lex_state = 0, .external_lex_state = 2},
  [114] = {.lex_state = 23, .external_lex_state = 2},
  [115] = {.lex_state = 0, .external_lex_state = 2},
  [116] = {.lex_state = 0, .external_lex_state = 8},
  [117] = {.lex_state = 0, .external_lex_state = 9},
  [118] = {.lex_state = 22, .external_lex_state = 2},
  [119] = {.lex_state = 0, .external_lex_state = 2},
  [120] = {.lex_state = 0, .external_lex_state = 10},
  [121] = {.lex_state = 0, .external_lex_state = 2},
};

enum {
  ts_external_token_start_tag_name = 0,
  ts_external_token_script_start_tag_name = 1,
  ts_external_token_style_start_tag_name = 2,
  ts_external_token_end_tag_name = 3,
  ts_external_token_erroneous_end_tag_name = 4,
  ts_external_token_SLASH_GT = 5,
  ts_external_token_implicit_end_tag = 6,
  ts_external_token_raw_text = 7,
  ts_external_token_comment = 8,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token_start_tag_name] = sym_start_tag_name,
  [ts_external_token_script_start_tag_name] = sym_script_start_tag_name,
  [ts_external_token_style_start_tag_name] = sym_style_start_tag_name,
  [ts_external_token_end_tag_name] = sym_end_tag_name,
  [ts_external_token_erroneous_end_tag_name] = sym_erroneous_end_tag_name,
  [ts_external_token_SLASH_GT] = anon_sym_SLASH_GT,
  [ts_external_token_implicit_end_tag] = sym_implicit_end_tag,
  [ts_external_token_raw_text] = sym_raw_text,
  [ts_external_token_comment] = sym_comment,
};

static const bool ts_external_scanner_states[11][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token_start_tag_name] = true,
    [ts_external_token_script_start_tag_name] = true,
    [ts_external_token_style_start_tag_name] = true,
    [ts_external_token_end_tag_name] = true,
    [ts_external_token_erroneous_end_tag_name] = true,
    [ts_external_token_SLASH_GT] = true,
    [ts_external_token_implicit_end_tag] = true,
    [ts_external_token_raw_text] = true,
    [ts_external_token_comment] = true,
  },
  [2] = {
    [ts_external_token_comment] = true,
  },
  [3] = {
    [ts_external_token_implicit_end_tag] = true,
    [ts_external_token_comment] = true,
  },
  [4] = {
    [ts_external_token_SLASH_GT] = true,
    [ts_external_token_comment] = true,
  },
  [5] = {
    [ts_external_token_raw_text] = true,
    [ts_external_token_comment] = true,
  },
  [6] = {
    [ts_external_token_start_tag_name] = true,
    [ts_external_token_script_start_tag_name] = true,
    [ts_external_token_style_start_tag_name] = true,
    [ts_external_token_comment] = true,
  },
  [7] = {
    [ts_external_token_end_tag_name] = true,
    [ts_external_token_erroneous_end_tag_name] = true,
    [ts_external_token_comment] = true,
  },
  [8] = {
    [ts_external_token_start_tag_name] = true,
    [ts_external_token_comment] = true,
  },
  [9] = {
    [ts_external_token_erroneous_end_tag_name] = true,
    [ts_external_token_comment] = true,
  },
  [10] = {
    [ts_external_token_end_tag_name] = true,
    [ts_external_token_comment] = true,
  },
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LT_BANG] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_LT_BANG_LBRACKCDATA_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK_RBRACK_GT] = ACTIONS(1),
    [sym__doctype] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_SLASH_GT] = ACTIONS(1),
    [anon_sym_LT_QMARK] = ACTIONS(1),
    [anon_sym_QMARK_GT] = ACTIONS(1),
    [anon_sym_LT_SLASH] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [sym_start_tag_name] = ACTIONS(1),
    [sym_script_start_tag_name] = ACTIONS(1),
    [sym_style_start_tag_name] = ACTIONS(1),
    [sym_end_tag_name] = ACTIONS(1),
    [sym_erroneous_end_tag_name] = ACTIONS(1),
    [sym_implicit_end_tag] = ACTIONS(1),
    [sym_raw_text] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
  },
  [1] = {
    [sym_fragment] = STATE(97),
    [sym_doctype] = STATE(8),
    [sym_cdata] = STATE(8),
    [sym__node] = STATE(8),
    [sym_markup_element] = STATE(8),
    [sym_element] = STATE(14),
    [sym_script_element] = STATE(14),
    [sym_style_element] = STATE(14),
    [sym_markup_opening_tag] = STATE(2),
    [sym_script_start_tag] = STATE(68),
    [sym_style_start_tag] = STATE(70),
    [sym_markup_singleton_tag] = STATE(16),
    [sym_declaration_tag] = STATE(16),
    [sym_erroneous_end_tag] = STATE(8),
    [aux_sym_fragment_repeat1] = STATE(8),
    [ts_builtin_sym_end] = ACTIONS(5),
    [anon_sym_LT_BANG] = ACTIONS(7),
    [anon_sym_LT_BANG_LBRACKCDATA_LBRACK] = ACTIONS(9),
    [anon_sym_LT] = ACTIONS(11),
    [anon_sym_LT_QMARK] = ACTIONS(13),
    [anon_sym_LT_SLASH] = ACTIONS(15),
    [sym_text_] = ACTIONS(17),
    [sym_comment] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 15,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(19), 1,
      anon_sym_LT_BANG,
    ACTIONS(21), 1,
      anon_sym_LT_BANG_LBRACKCDATA_LBRACK,
    ACTIONS(23), 1,
      anon_sym_LT,
    ACTIONS(25), 1,
      anon_sym_LT_QMARK,
    ACTIONS(27), 1,
      anon_sym_LT_SLASH,
    ACTIONS(29), 1,
      sym_text_,
    ACTIONS(31), 1,
      sym_implicit_end_tag,
    STATE(5), 1,
      sym_markup_opening_tag,
    STATE(23), 1,
      sym_markup_closing_tag,
    STATE(62), 1,
      sym_script_start_tag,
    STATE(72), 1,
      sym_style_start_tag,
    STATE(15), 2,
      sym_markup_singleton_tag,
      sym_declaration_tag,
    STATE(17), 3,
      sym_element,
      sym_script_element,
      sym_style_element,
    STATE(3), 6,
      sym_doctype,
      sym_cdata,
      sym__node,
      sym_markup_element,
      sym_erroneous_end_tag,
      aux_sym_fragment_repeat1,
  [54] = 15,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(19), 1,
      anon_sym_LT_BANG,
    ACTIONS(21), 1,
      anon_sym_LT_BANG_LBRACKCDATA_LBRACK,
    ACTIONS(23), 1,
      anon_sym_LT,
    ACTIONS(25), 1,
      anon_sym_LT_QMARK,
    ACTIONS(27), 1,
      anon_sym_LT_SLASH,
    ACTIONS(33), 1,
      sym_text_,
    ACTIONS(35), 1,
      sym_implicit_end_tag,
    STATE(5), 1,
      sym_markup_opening_tag,
    STATE(39), 1,
      sym_markup_closing_tag,
    STATE(62), 1,
      sym_script_start_tag,
    STATE(72), 1,
      sym_style_start_tag,
    STATE(15), 2,
      sym_markup_singleton_tag,
      sym_declaration_tag,
    STATE(17), 3,
      sym_element,
      sym_script_element,
      sym_style_element,
    STATE(6), 6,
      sym_doctype,
      sym_cdata,
      sym__node,
      sym_markup_element,
      sym_erroneous_end_tag,
      aux_sym_fragment_repeat1,
  [108] = 15,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(19), 1,
      anon_sym_LT_BANG,
    ACTIONS(21), 1,
      anon_sym_LT_BANG_LBRACKCDATA_LBRACK,
    ACTIONS(23), 1,
      anon_sym_LT,
    ACTIONS(25), 1,
      anon_sym_LT_QMARK,
    ACTIONS(33), 1,
      sym_text_,
    ACTIONS(37), 1,
      anon_sym_LT_SLASH,
    ACTIONS(39), 1,
      sym_implicit_end_tag,
    STATE(5), 1,
      sym_markup_opening_tag,
    STATE(38), 1,
      sym_markup_closing_tag,
    STATE(62), 1,
      sym_script_start_tag,
    STATE(72), 1,
      sym_style_start_tag,
    STATE(15), 2,
      sym_markup_singleton_tag,
      sym_declaration_tag,
    STATE(17), 3,
      sym_element,
      sym_script_element,
      sym_style_element,
    STATE(6), 6,
      sym_doctype,
      sym_cdata,
      sym__node,
      sym_markup_element,
      sym_erroneous_end_tag,
      aux_sym_fragment_repeat1,
  [162] = 15,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(19), 1,
      anon_sym_LT_BANG,
    ACTIONS(21), 1,
      anon_sym_LT_BANG_LBRACKCDATA_LBRACK,
    ACTIONS(23), 1,
      anon_sym_LT,
    ACTIONS(25), 1,
      anon_sym_LT_QMARK,
    ACTIONS(37), 1,
      anon_sym_LT_SLASH,
    ACTIONS(41), 1,
      sym_text_,
    ACTIONS(43), 1,
      sym_implicit_end_tag,
    STATE(5), 1,
      sym_markup_opening_tag,
    STATE(13), 1,
      sym_markup_closing_tag,
    STATE(62), 1,
      sym_script_start_tag,
    STATE(72), 1,
      sym_style_start_tag,
    STATE(15), 2,
      sym_markup_singleton_tag,
      sym_declaration_tag,
    STATE(17), 3,
      sym_element,
      sym_script_element,
      sym_style_element,
    STATE(4), 6,
      sym_doctype,
      sym_cdata,
      sym__node,
      sym_markup_element,
      sym_erroneous_end_tag,
      aux_sym_fragment_repeat1,
  [216] = 14,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(45), 1,
      anon_sym_LT_BANG,
    ACTIONS(48), 1,
      anon_sym_LT_BANG_LBRACKCDATA_LBRACK,
    ACTIONS(51), 1,
      anon_sym_LT,
    ACTIONS(54), 1,
      anon_sym_LT_QMARK,
    ACTIONS(57), 1,
      anon_sym_LT_SLASH,
    ACTIONS(60), 1,
      sym_text_,
    ACTIONS(63), 1,
      sym_implicit_end_tag,
    STATE(5), 1,
      sym_markup_opening_tag,
    STATE(62), 1,
      sym_script_start_tag,
    STATE(72), 1,
      sym_style_start_tag,
    STATE(15), 2,
      sym_markup_singleton_tag,
      sym_declaration_tag,
    STATE(17), 3,
      sym_element,
      sym_script_element,
      sym_style_element,
    STATE(6), 6,
      sym_doctype,
      sym_cdata,
      sym__node,
      sym_markup_element,
      sym_erroneous_end_tag,
      aux_sym_fragment_repeat1,
  [267] = 14,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(63), 1,
      ts_builtin_sym_end,
    ACTIONS(65), 1,
      anon_sym_LT_BANG,
    ACTIONS(68), 1,
      anon_sym_LT_BANG_LBRACKCDATA_LBRACK,
    ACTIONS(71), 1,
      anon_sym_LT,
    ACTIONS(74), 1,
      anon_sym_LT_QMARK,
    ACTIONS(77), 1,
      anon_sym_LT_SLASH,
    ACTIONS(80), 1,
      sym_text_,
    STATE(2), 1,
      sym_markup_opening_tag,
    STATE(68), 1,
      sym_script_start_tag,
    STATE(70), 1,
      sym_style_start_tag,
    STATE(16), 2,
      sym_markup_singleton_tag,
      sym_declaration_tag,
    STATE(14), 3,
      sym_element,
      sym_script_element,
      sym_style_element,
    STATE(7), 6,
      sym_doctype,
      sym_cdata,
      sym__node,
      sym_markup_element,
      sym_erroneous_end_tag,
      aux_sym_fragment_repeat1,
  [318] = 14,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_LT_BANG,
    ACTIONS(9), 1,
      anon_sym_LT_BANG_LBRACKCDATA_LBRACK,
    ACTIONS(11), 1,
      anon_sym_LT,
    ACTIONS(13), 1,
      anon_sym_LT_QMARK,
    ACTIONS(15), 1,
      anon_sym_LT_SLASH,
    ACTIONS(83), 1,
      ts_builtin_sym_end,
    ACTIONS(85), 1,
      sym_text_,
    STATE(2), 1,
      sym_markup_opening_tag,
    STATE(68), 1,
      sym_script_start_tag,
    STATE(70), 1,
      sym_style_start_tag,
    STATE(16), 2,
      sym_markup_singleton_tag,
      sym_declaration_tag,
    STATE(14), 3,
      sym_element,
      sym_script_element,
      sym_style_element,
    STATE(7), 6,
      sym_doctype,
      sym_cdata,
      sym__node,
      sym_markup_element,
      sym_erroneous_end_tag,
      aux_sym_fragment_repeat1,
  [369] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(87), 2,
      ts_builtin_sym_end,
      sym_text_,
    ACTIONS(89), 5,
      anon_sym_LT_BANG,
      anon_sym_LT_BANG_LBRACKCDATA_LBRACK,
      anon_sym_LT,
      anon_sym_LT_QMARK,
      anon_sym_LT_SLASH,
  [384] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(91), 2,
      ts_builtin_sym_end,
      sym_text_,
    ACTIONS(93), 5,
      anon_sym_LT_BANG,
      anon_sym_LT_BANG_LBRACKCDATA_LBRACK,
      anon_sym_LT,
      anon_sym_LT_QMARK,
      anon_sym_LT_SLASH,
  [399] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(97), 2,
      sym_implicit_end_tag,
      sym_text_,
    ACTIONS(95), 5,
      anon_sym_LT_BANG,
      anon_sym_LT_BANG_LBRACKCDATA_LBRACK,
      anon_sym_LT,
      anon_sym_LT_QMARK,
      anon_sym_LT_SLASH,
  [414] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(101), 2,
      sym_implicit_end_tag,
      sym_text_,
    ACTIONS(99), 5,
      anon_sym_LT_BANG,
      anon_sym_LT_BANG_LBRACKCDATA_LBRACK,
      anon_sym_LT,
      anon_sym_LT_QMARK,
      anon_sym_LT_SLASH,
  [429] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(105), 2,
      sym_implicit_end_tag,
      sym_text_,
    ACTIONS(103), 5,
      anon_sym_LT_BANG,
      anon_sym_LT_BANG_LBRACKCDATA_LBRACK,
      anon_sym_LT,
      anon_sym_LT_QMARK,
      anon_sym_LT_SLASH,
  [444] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(107), 2,
      ts_builtin_sym_end,
      sym_text_,
    ACTIONS(109), 5,
      anon_sym_LT_BANG,
      anon_sym_LT_BANG_LBRACKCDATA_LBRACK,
      anon_sym_LT,
      anon_sym_LT_QMARK,
      anon_sym_LT_SLASH,
  [459] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(113), 2,
      sym_implicit_end_tag,
      sym_text_,
    ACTIONS(111), 5,
      anon_sym_LT_BANG,
      anon_sym_LT_BANG_LBRACKCDATA_LBRACK,
      anon_sym_LT,
      anon_sym_LT_QMARK,
      anon_sym_LT_SLASH,
  [474] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(113), 2,
      ts_builtin_sym_end,
      sym_text_,
    ACTIONS(111), 5,
      anon_sym_LT_BANG,
      anon_sym_LT_BANG_LBRACKCDATA_LBRACK,
      anon_sym_LT,
      anon_sym_LT_QMARK,
      anon_sym_LT_SLASH,
  [489] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(107), 2,
      sym_implicit_end_tag,
      sym_text_,
    ACTIONS(109), 5,
      anon_sym_LT_BANG,
      anon_sym_LT_BANG_LBRACKCDATA_LBRACK,
      anon_sym_LT,
      anon_sym_LT_QMARK,
      anon_sym_LT_SLASH,
  [504] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(115), 2,
      ts_builtin_sym_end,
      sym_text_,
    ACTIONS(117), 5,
      anon_sym_LT_BANG,
      anon_sym_LT_BANG_LBRACKCDATA_LBRACK,
      anon_sym_LT,
      anon_sym_LT_QMARK,
      anon_sym_LT_SLASH,
  [519] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(119), 2,
      ts_builtin_sym_end,
      sym_text_,
    ACTIONS(121), 5,
      anon_sym_LT_BANG,
      anon_sym_LT_BANG_LBRACKCDATA_LBRACK,
      anon_sym_LT,
      anon_sym_LT_QMARK,
      anon_sym_LT_SLASH,
  [534] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(125), 2,
      sym_implicit_end_tag,
      sym_text_,
    ACTIONS(123), 5,
      anon_sym_LT_BANG,
      anon_sym_LT_BANG_LBRACKCDATA_LBRACK,
      anon_sym_LT,
      anon_sym_LT_QMARK,
      anon_sym_LT_SLASH,
  [549] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(129), 2,
      sym_implicit_end_tag,
      sym_text_,
    ACTIONS(127), 5,
      anon_sym_LT_BANG,
      anon_sym_LT_BANG_LBRACKCDATA_LBRACK,
      anon_sym_LT,
      anon_sym_LT_QMARK,
      anon_sym_LT_SLASH,
  [564] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(115), 2,
      sym_implicit_end_tag,
      sym_text_,
    ACTIONS(117), 5,
      anon_sym_LT_BANG,
      anon_sym_LT_BANG_LBRACKCDATA_LBRACK,
      anon_sym_LT,
      anon_sym_LT_QMARK,
      anon_sym_LT_SLASH,
  [579] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(105), 2,
      ts_builtin_sym_end,
      sym_text_,
    ACTIONS(103), 5,
      anon_sym_LT_BANG,
      anon_sym_LT_BANG_LBRACKCDATA_LBRACK,
      anon_sym_LT,
      anon_sym_LT_QMARK,
      anon_sym_LT_SLASH,
  [594] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(119), 2,
      sym_implicit_end_tag,
      sym_text_,
    ACTIONS(121), 5,
      anon_sym_LT_BANG,
      anon_sym_LT_BANG_LBRACKCDATA_LBRACK,
      anon_sym_LT,
      anon_sym_LT_QMARK,
      anon_sym_LT_SLASH,
  [609] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(133), 2,
      sym_implicit_end_tag,
      sym_text_,
    ACTIONS(131), 5,
      anon_sym_LT_BANG,
      anon_sym_LT_BANG_LBRACKCDATA_LBRACK,
      anon_sym_LT,
      anon_sym_LT_QMARK,
      anon_sym_LT_SLASH,
  [624] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(91), 2,
      sym_implicit_end_tag,
      sym_text_,
    ACTIONS(93), 5,
      anon_sym_LT_BANG,
      anon_sym_LT_BANG_LBRACKCDATA_LBRACK,
      anon_sym_LT,
      anon_sym_LT_QMARK,
      anon_sym_LT_SLASH,
  [639] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(101), 2,
      ts_builtin_sym_end,
      sym_text_,
    ACTIONS(99), 5,
      anon_sym_LT_BANG,
      anon_sym_LT_BANG_LBRACKCDATA_LBRACK,
      anon_sym_LT,
      anon_sym_LT_QMARK,
      anon_sym_LT_SLASH,
  [654] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(137), 2,
      sym_implicit_end_tag,
      sym_text_,
    ACTIONS(135), 5,
      anon_sym_LT_BANG,
      anon_sym_LT_BANG_LBRACKCDATA_LBRACK,
      anon_sym_LT,
      anon_sym_LT_QMARK,
      anon_sym_LT_SLASH,
  [669] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(97), 2,
      ts_builtin_sym_end,
      sym_text_,
    ACTIONS(95), 5,
      anon_sym_LT_BANG,
      anon_sym_LT_BANG_LBRACKCDATA_LBRACK,
      anon_sym_LT,
      anon_sym_LT_QMARK,
      anon_sym_LT_SLASH,
  [684] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(141), 2,
      sym_implicit_end_tag,
      sym_text_,
    ACTIONS(139), 5,
      anon_sym_LT_BANG,
      anon_sym_LT_BANG_LBRACKCDATA_LBRACK,
      anon_sym_LT,
      anon_sym_LT_QMARK,
      anon_sym_LT_SLASH,
  [699] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(143), 2,
      ts_builtin_sym_end,
      sym_text_,
    ACTIONS(145), 5,
      anon_sym_LT_BANG,
      anon_sym_LT_BANG_LBRACKCDATA_LBRACK,
      anon_sym_LT,
      anon_sym_LT_QMARK,
      anon_sym_LT_SLASH,
  [714] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(149), 2,
      sym_implicit_end_tag,
      sym_text_,
    ACTIONS(147), 5,
      anon_sym_LT_BANG,
      anon_sym_LT_BANG_LBRACKCDATA_LBRACK,
      anon_sym_LT,
      anon_sym_LT_QMARK,
      anon_sym_LT_SLASH,
  [729] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(125), 2,
      ts_builtin_sym_end,
      sym_text_,
    ACTIONS(123), 5,
      anon_sym_LT_BANG,
      anon_sym_LT_BANG_LBRACKCDATA_LBRACK,
      anon_sym_LT,
      anon_sym_LT_QMARK,
      anon_sym_LT_SLASH,
  [744] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(137), 2,
      ts_builtin_sym_end,
      sym_text_,
    ACTIONS(135), 5,
      anon_sym_LT_BANG,
      anon_sym_LT_BANG_LBRACKCDATA_LBRACK,
      anon_sym_LT,
      anon_sym_LT_QMARK,
      anon_sym_LT_SLASH,
  [759] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(141), 2,
      ts_builtin_sym_end,
      sym_text_,
    ACTIONS(139), 5,
      anon_sym_LT_BANG,
      anon_sym_LT_BANG_LBRACKCDATA_LBRACK,
      anon_sym_LT,
      anon_sym_LT_QMARK,
      anon_sym_LT_SLASH,
  [774] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(87), 2,
      sym_implicit_end_tag,
      sym_text_,
    ACTIONS(89), 5,
      anon_sym_LT_BANG,
      anon_sym_LT_BANG_LBRACKCDATA_LBRACK,
      anon_sym_LT,
      anon_sym_LT_QMARK,
      anon_sym_LT_SLASH,
  [789] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(143), 2,
      sym_implicit_end_tag,
      sym_text_,
    ACTIONS(145), 5,
      anon_sym_LT_BANG,
      anon_sym_LT_BANG_LBRACKCDATA_LBRACK,
      anon_sym_LT,
      anon_sym_LT_QMARK,
      anon_sym_LT_SLASH,
  [804] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(153), 2,
      sym_implicit_end_tag,
      sym_text_,
    ACTIONS(151), 5,
      anon_sym_LT_BANG,
      anon_sym_LT_BANG_LBRACKCDATA_LBRACK,
      anon_sym_LT,
      anon_sym_LT_QMARK,
      anon_sym_LT_SLASH,
  [819] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(153), 2,
      ts_builtin_sym_end,
      sym_text_,
    ACTIONS(151), 5,
      anon_sym_LT_BANG,
      anon_sym_LT_BANG_LBRACKCDATA_LBRACK,
      anon_sym_LT,
      anon_sym_LT_QMARK,
      anon_sym_LT_SLASH,
  [834] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(129), 2,
      ts_builtin_sym_end,
      sym_text_,
    ACTIONS(127), 5,
      anon_sym_LT_BANG,
      anon_sym_LT_BANG_LBRACKCDATA_LBRACK,
      anon_sym_LT,
      anon_sym_LT_QMARK,
      anon_sym_LT_SLASH,
  [849] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(157), 2,
      sym_implicit_end_tag,
      sym_text_,
    ACTIONS(155), 5,
      anon_sym_LT_BANG,
      anon_sym_LT_BANG_LBRACKCDATA_LBRACK,
      anon_sym_LT,
      anon_sym_LT_QMARK,
      anon_sym_LT_SLASH,
  [864] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(157), 2,
      ts_builtin_sym_end,
      sym_text_,
    ACTIONS(155), 5,
      anon_sym_LT_BANG,
      anon_sym_LT_BANG_LBRACKCDATA_LBRACK,
      anon_sym_LT,
      anon_sym_LT_QMARK,
      anon_sym_LT_SLASH,
  [879] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(159), 1,
      anon_sym_GT,
    ACTIONS(161), 1,
      anon_sym_SLASH_GT,
    ACTIONS(163), 1,
      sym_markup_attribute_name,
    STATE(44), 2,
      sym_markup_attribute,
      aux_sym_markup_opening_tag_repeat1,
  [896] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(167), 1,
      sym_markup_attribute_name,
    ACTIONS(165), 2,
      anon_sym_GT,
      anon_sym_SLASH_GT,
    STATE(44), 2,
      sym_markup_attribute,
      aux_sym_markup_opening_tag_repeat1,
  [911] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(163), 1,
      sym_markup_attribute_name,
    ACTIONS(170), 1,
      anon_sym_GT,
    ACTIONS(172), 1,
      anon_sym_SLASH_GT,
    STATE(43), 2,
      sym_markup_attribute,
      aux_sym_markup_opening_tag_repeat1,
  [928] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(163), 1,
      sym_markup_attribute_name,
    ACTIONS(170), 1,
      anon_sym_GT,
    ACTIONS(174), 1,
      anon_sym_SLASH_GT,
    STATE(47), 2,
      sym_markup_attribute,
      aux_sym_markup_opening_tag_repeat1,
  [945] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(159), 1,
      anon_sym_GT,
    ACTIONS(163), 1,
      sym_markup_attribute_name,
    ACTIONS(176), 1,
      anon_sym_SLASH_GT,
    STATE(44), 2,
      sym_markup_attribute,
      aux_sym_markup_opening_tag_repeat1,
  [962] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(178), 1,
      anon_sym_QMARK_GT,
    ACTIONS(180), 1,
      sym_markup_attribute_name,
    STATE(58), 2,
      sym_markup_attribute,
      aux_sym_markup_opening_tag_repeat1,
  [976] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(182), 1,
      anon_sym_GT,
    ACTIONS(184), 1,
      sym_markup_attribute_name,
    STATE(53), 2,
      sym_markup_attribute,
      aux_sym_markup_opening_tag_repeat1,
  [990] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(184), 1,
      sym_markup_attribute_name,
    ACTIONS(186), 1,
      anon_sym_GT,
    STATE(53), 2,
      sym_markup_attribute,
      aux_sym_markup_opening_tag_repeat1,
  [1004] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(190), 1,
      anon_sym_EQ,
    ACTIONS(188), 3,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      sym_markup_attribute_name,
  [1016] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(192), 1,
      sym_attribute_value,
    ACTIONS(194), 1,
      anon_sym_SQUOTE,
    ACTIONS(196), 1,
      anon_sym_DQUOTE,
    STATE(65), 1,
      sym_quoted_attribute_value,
  [1032] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(165), 1,
      anon_sym_GT,
    ACTIONS(198), 1,
      sym_markup_attribute_name,
    STATE(53), 2,
      sym_markup_attribute,
      aux_sym_markup_opening_tag_repeat1,
  [1046] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(201), 1,
      sym_attribute_value,
    ACTIONS(203), 1,
      anon_sym_SQUOTE,
    ACTIONS(205), 1,
      anon_sym_DQUOTE,
    STATE(83), 1,
      sym_quoted_attribute_value,
  [1062] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(180), 1,
      sym_markup_attribute_name,
    ACTIONS(207), 1,
      anon_sym_QMARK_GT,
    STATE(48), 2,
      sym_markup_attribute,
      aux_sym_markup_opening_tag_repeat1,
  [1076] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(184), 1,
      sym_markup_attribute_name,
    ACTIONS(209), 1,
      anon_sym_GT,
    STATE(49), 2,
      sym_markup_attribute,
      aux_sym_markup_opening_tag_repeat1,
  [1090] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(184), 1,
      sym_markup_attribute_name,
    ACTIONS(211), 1,
      anon_sym_GT,
    STATE(50), 2,
      sym_markup_attribute,
      aux_sym_markup_opening_tag_repeat1,
  [1104] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(165), 1,
      anon_sym_QMARK_GT,
    ACTIONS(213), 1,
      sym_markup_attribute_name,
    STATE(58), 2,
      sym_markup_attribute,
      aux_sym_markup_opening_tag_repeat1,
  [1118] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(180), 1,
      sym_markup_attribute_name,
    ACTIONS(216), 1,
      anon_sym_QMARK_GT,
    STATE(60), 2,
      sym_markup_attribute,
      aux_sym_markup_opening_tag_repeat1,
  [1132] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(180), 1,
      sym_markup_attribute_name,
    ACTIONS(218), 1,
      anon_sym_QMARK_GT,
    STATE(58), 2,
      sym_markup_attribute,
      aux_sym_markup_opening_tag_repeat1,
  [1146] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(220), 1,
      sym_attribute_value,
    ACTIONS(222), 1,
      anon_sym_SQUOTE,
    ACTIONS(224), 1,
      anon_sym_DQUOTE,
    STATE(87), 1,
      sym_quoted_attribute_value,
  [1162] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(226), 1,
      anon_sym_LT_SLASH,
    ACTIONS(228), 1,
      sym_raw_text,
    STATE(12), 1,
      sym_markup_closing_tag,
  [1175] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(188), 1,
      anon_sym_QMARK_GT,
    ACTIONS(230), 1,
      anon_sym_EQ,
    ACTIONS(232), 1,
      sym_markup_attribute_name,
  [1188] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(234), 1,
      sym_start_tag_name,
    ACTIONS(236), 1,
      sym_script_start_tag_name,
    ACTIONS(238), 1,
      sym_style_start_tag_name,
  [1201] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(240), 3,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      sym_markup_attribute_name,
  [1210] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(242), 3,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      sym_markup_attribute_name,
  [1219] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(236), 1,
      sym_script_start_tag_name,
    ACTIONS(238), 1,
      sym_style_start_tag_name,
    ACTIONS(244), 1,
      sym_start_tag_name,
  [1232] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(246), 1,
      anon_sym_LT_SLASH,
    ACTIONS(248), 1,
      sym_raw_text,
    STATE(27), 1,
      sym_markup_closing_tag,
  [1245] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(250), 3,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      sym_markup_attribute_name,
  [1254] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(246), 1,
      anon_sym_LT_SLASH,
    ACTIONS(252), 1,
      sym_raw_text,
    STATE(29), 1,
      sym_markup_closing_tag,
  [1267] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(254), 1,
      anon_sym_EQ,
    ACTIONS(188), 2,
      anon_sym_GT,
      sym_markup_attribute_name,
  [1278] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(226), 1,
      anon_sym_LT_SLASH,
    ACTIONS(256), 1,
      sym_raw_text,
    STATE(11), 1,
      sym_markup_closing_tag,
  [1291] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(258), 1,
      anon_sym_SQUOTE,
    ACTIONS(260), 1,
      aux_sym_quoted_attribute_value_token1,
  [1301] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(262), 1,
      anon_sym_SQUOTE,
    ACTIONS(264), 1,
      aux_sym_quoted_attribute_value_token1,
  [1311] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(266), 1,
      sym_end_tag_name,
    ACTIONS(268), 1,
      sym_erroneous_end_tag_name,
  [1321] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(270), 2,
      sym_raw_text,
      anon_sym_LT_SLASH,
  [1329] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(272), 2,
      sym_raw_text,
      anon_sym_LT_SLASH,
  [1337] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(274), 1,
      anon_sym_DQUOTE,
    ACTIONS(276), 1,
      aux_sym_quoted_attribute_value_token2,
  [1347] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(246), 1,
      anon_sym_LT_SLASH,
    STATE(35), 1,
      sym_markup_closing_tag,
  [1357] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(262), 1,
      anon_sym_DQUOTE,
    ACTIONS(278), 1,
      aux_sym_quoted_attribute_value_token2,
  [1367] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(246), 1,
      anon_sym_LT_SLASH,
    STATE(9), 1,
      sym_markup_closing_tag,
  [1377] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(268), 1,
      sym_erroneous_end_tag_name,
    ACTIONS(280), 1,
      sym_end_tag_name,
  [1387] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(240), 2,
      anon_sym_GT,
      sym_markup_attribute_name,
  [1395] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(242), 2,
      anon_sym_GT,
      sym_markup_attribute_name,
  [1403] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(250), 2,
      anon_sym_GT,
      sym_markup_attribute_name,
  [1411] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(282), 2,
      sym_raw_text,
      anon_sym_LT_SLASH,
  [1419] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(240), 1,
      anon_sym_QMARK_GT,
    ACTIONS(284), 1,
      sym_markup_attribute_name,
  [1429] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(242), 1,
      anon_sym_QMARK_GT,
    ACTIONS(286), 1,
      sym_markup_attribute_name,
  [1439] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(250), 1,
      anon_sym_QMARK_GT,
    ACTIONS(288), 1,
      sym_markup_attribute_name,
  [1449] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(258), 1,
      anon_sym_DQUOTE,
    ACTIONS(290), 1,
      aux_sym_quoted_attribute_value_token2,
  [1459] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(226), 1,
      anon_sym_LT_SLASH,
    STATE(30), 1,
      sym_markup_closing_tag,
  [1469] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(274), 1,
      anon_sym_SQUOTE,
    ACTIONS(292), 1,
      aux_sym_quoted_attribute_value_token1,
  [1479] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(226), 1,
      anon_sym_LT_SLASH,
    STATE(36), 1,
      sym_markup_closing_tag,
  [1489] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(294), 2,
      sym_raw_text,
      anon_sym_LT_SLASH,
  [1497] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(296), 1,
      anon_sym_SQUOTE,
  [1504] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(298), 1,
      sym_start_tag_name,
  [1511] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(300), 1,
      ts_builtin_sym_end,
  [1518] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(302), 1,
      anon_sym_RBRACK_RBRACK_GT,
  [1525] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(304), 1,
      aux_sym_doctype_token1,
  [1532] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(306), 1,
      anon_sym_GT,
  [1539] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(308), 1,
      sym_erroneous_end_tag_name,
  [1546] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(296), 1,
      anon_sym_DQUOTE,
  [1553] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(310), 1,
      anon_sym_GT,
  [1560] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(312), 1,
      anon_sym_DQUOTE,
  [1567] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(312), 1,
      anon_sym_SQUOTE,
  [1574] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(314), 1,
      anon_sym_RBRACK_RBRACK_GT,
  [1581] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(316), 1,
      aux_sym_cdata_token1,
  [1588] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(318), 1,
      anon_sym_GT,
  [1595] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(320), 1,
      sym__doctype,
  [1602] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(322), 1,
      anon_sym_GT,
  [1609] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(280), 1,
      sym_end_tag_name,
  [1616] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(324), 1,
      anon_sym_SQUOTE,
  [1623] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(324), 1,
      anon_sym_DQUOTE,
  [1630] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(326), 1,
      aux_sym_cdata_token1,
  [1637] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(328), 1,
      anon_sym_GT,
  [1644] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(330), 1,
      sym_start_tag_name,
  [1651] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(268), 1,
      sym_erroneous_end_tag_name,
  [1658] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(332), 1,
      aux_sym_doctype_token1,
  [1665] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(334), 1,
      anon_sym_GT,
  [1672] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(266), 1,
      sym_end_tag_name,
  [1679] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(336), 1,
      sym__doctype,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 54,
  [SMALL_STATE(4)] = 108,
  [SMALL_STATE(5)] = 162,
  [SMALL_STATE(6)] = 216,
  [SMALL_STATE(7)] = 267,
  [SMALL_STATE(8)] = 318,
  [SMALL_STATE(9)] = 369,
  [SMALL_STATE(10)] = 384,
  [SMALL_STATE(11)] = 399,
  [SMALL_STATE(12)] = 414,
  [SMALL_STATE(13)] = 429,
  [SMALL_STATE(14)] = 444,
  [SMALL_STATE(15)] = 459,
  [SMALL_STATE(16)] = 474,
  [SMALL_STATE(17)] = 489,
  [SMALL_STATE(18)] = 504,
  [SMALL_STATE(19)] = 519,
  [SMALL_STATE(20)] = 534,
  [SMALL_STATE(21)] = 549,
  [SMALL_STATE(22)] = 564,
  [SMALL_STATE(23)] = 579,
  [SMALL_STATE(24)] = 594,
  [SMALL_STATE(25)] = 609,
  [SMALL_STATE(26)] = 624,
  [SMALL_STATE(27)] = 639,
  [SMALL_STATE(28)] = 654,
  [SMALL_STATE(29)] = 669,
  [SMALL_STATE(30)] = 684,
  [SMALL_STATE(31)] = 699,
  [SMALL_STATE(32)] = 714,
  [SMALL_STATE(33)] = 729,
  [SMALL_STATE(34)] = 744,
  [SMALL_STATE(35)] = 759,
  [SMALL_STATE(36)] = 774,
  [SMALL_STATE(37)] = 789,
  [SMALL_STATE(38)] = 804,
  [SMALL_STATE(39)] = 819,
  [SMALL_STATE(40)] = 834,
  [SMALL_STATE(41)] = 849,
  [SMALL_STATE(42)] = 864,
  [SMALL_STATE(43)] = 879,
  [SMALL_STATE(44)] = 896,
  [SMALL_STATE(45)] = 911,
  [SMALL_STATE(46)] = 928,
  [SMALL_STATE(47)] = 945,
  [SMALL_STATE(48)] = 962,
  [SMALL_STATE(49)] = 976,
  [SMALL_STATE(50)] = 990,
  [SMALL_STATE(51)] = 1004,
  [SMALL_STATE(52)] = 1016,
  [SMALL_STATE(53)] = 1032,
  [SMALL_STATE(54)] = 1046,
  [SMALL_STATE(55)] = 1062,
  [SMALL_STATE(56)] = 1076,
  [SMALL_STATE(57)] = 1090,
  [SMALL_STATE(58)] = 1104,
  [SMALL_STATE(59)] = 1118,
  [SMALL_STATE(60)] = 1132,
  [SMALL_STATE(61)] = 1146,
  [SMALL_STATE(62)] = 1162,
  [SMALL_STATE(63)] = 1175,
  [SMALL_STATE(64)] = 1188,
  [SMALL_STATE(65)] = 1201,
  [SMALL_STATE(66)] = 1210,
  [SMALL_STATE(67)] = 1219,
  [SMALL_STATE(68)] = 1232,
  [SMALL_STATE(69)] = 1245,
  [SMALL_STATE(70)] = 1254,
  [SMALL_STATE(71)] = 1267,
  [SMALL_STATE(72)] = 1278,
  [SMALL_STATE(73)] = 1291,
  [SMALL_STATE(74)] = 1301,
  [SMALL_STATE(75)] = 1311,
  [SMALL_STATE(76)] = 1321,
  [SMALL_STATE(77)] = 1329,
  [SMALL_STATE(78)] = 1337,
  [SMALL_STATE(79)] = 1347,
  [SMALL_STATE(80)] = 1357,
  [SMALL_STATE(81)] = 1367,
  [SMALL_STATE(82)] = 1377,
  [SMALL_STATE(83)] = 1387,
  [SMALL_STATE(84)] = 1395,
  [SMALL_STATE(85)] = 1403,
  [SMALL_STATE(86)] = 1411,
  [SMALL_STATE(87)] = 1419,
  [SMALL_STATE(88)] = 1429,
  [SMALL_STATE(89)] = 1439,
  [SMALL_STATE(90)] = 1449,
  [SMALL_STATE(91)] = 1459,
  [SMALL_STATE(92)] = 1469,
  [SMALL_STATE(93)] = 1479,
  [SMALL_STATE(94)] = 1489,
  [SMALL_STATE(95)] = 1497,
  [SMALL_STATE(96)] = 1504,
  [SMALL_STATE(97)] = 1511,
  [SMALL_STATE(98)] = 1518,
  [SMALL_STATE(99)] = 1525,
  [SMALL_STATE(100)] = 1532,
  [SMALL_STATE(101)] = 1539,
  [SMALL_STATE(102)] = 1546,
  [SMALL_STATE(103)] = 1553,
  [SMALL_STATE(104)] = 1560,
  [SMALL_STATE(105)] = 1567,
  [SMALL_STATE(106)] = 1574,
  [SMALL_STATE(107)] = 1581,
  [SMALL_STATE(108)] = 1588,
  [SMALL_STATE(109)] = 1595,
  [SMALL_STATE(110)] = 1602,
  [SMALL_STATE(111)] = 1609,
  [SMALL_STATE(112)] = 1616,
  [SMALL_STATE(113)] = 1623,
  [SMALL_STATE(114)] = 1630,
  [SMALL_STATE(115)] = 1637,
  [SMALL_STATE(116)] = 1644,
  [SMALL_STATE(117)] = 1651,
  [SMALL_STATE(118)] = 1658,
  [SMALL_STATE(119)] = 1665,
  [SMALL_STATE(120)] = 1672,
  [SMALL_STATE(121)] = 1679,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fragment, 0),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(121),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(107),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(67),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(96),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(101),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(109),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(114),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(64),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(116),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(82),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [37] = {.entry = {.count = 1, .reusable = false}}, SHIFT(75),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [45] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_fragment_repeat1, 2), SHIFT_REPEAT(109),
  [48] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_fragment_repeat1, 2), SHIFT_REPEAT(114),
  [51] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_fragment_repeat1, 2), SHIFT_REPEAT(64),
  [54] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_fragment_repeat1, 2), SHIFT_REPEAT(116),
  [57] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_fragment_repeat1, 2), SHIFT_REPEAT(117),
  [60] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_fragment_repeat1, 2), SHIFT_REPEAT(6),
  [63] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_fragment_repeat1, 2),
  [65] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_fragment_repeat1, 2), SHIFT_REPEAT(121),
  [68] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_fragment_repeat1, 2), SHIFT_REPEAT(107),
  [71] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_fragment_repeat1, 2), SHIFT_REPEAT(67),
  [74] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_fragment_repeat1, 2), SHIFT_REPEAT(96),
  [77] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_fragment_repeat1, 2), SHIFT_REPEAT(101),
  [80] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_fragment_repeat1, 2), SHIFT_REPEAT(7),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fragment, 1),
  [85] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_script_element, 3, .production_id = 3),
  [89] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_script_element, 3, .production_id = 3),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_markup_singleton_tag, 4, .production_id = 4),
  [93] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_markup_singleton_tag, 4, .production_id = 4),
  [95] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_style_element, 2),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_style_element, 2),
  [99] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_script_element, 2),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_script_element, 2),
  [103] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_element, 2),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_element, 2),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_markup_element, 1),
  [109] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_markup_element, 1),
  [111] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_element, 1),
  [113] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_element, 1),
  [115] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_markup_closing_tag, 3, .production_id = 1),
  [117] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_markup_closing_tag, 3, .production_id = 1),
  [119] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_declaration_tag, 4, .production_id = 4),
  [121] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_declaration_tag, 4, .production_id = 4),
  [123] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_markup_singleton_tag, 3, .production_id = 1),
  [125] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_markup_singleton_tag, 3, .production_id = 1),
  [127] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_declaration_tag, 3, .production_id = 1),
  [129] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_declaration_tag, 3, .production_id = 1),
  [131] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_markup_opening_tag, 4, .production_id = 4),
  [133] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_markup_opening_tag, 4, .production_id = 4),
  [135] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_doctype, 4),
  [137] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_doctype, 4),
  [139] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_style_element, 3, .production_id = 3),
  [141] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_style_element, 3, .production_id = 3),
  [143] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_cdata, 3),
  [145] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_cdata, 3),
  [147] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_markup_opening_tag, 3, .production_id = 1),
  [149] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_markup_opening_tag, 3, .production_id = 1),
  [151] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_element, 3, .production_id = 3),
  [153] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_element, 3, .production_id = 3),
  [155] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_erroneous_end_tag, 3, .production_id = 2),
  [157] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_erroneous_end_tag, 3, .production_id = 2),
  [159] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [161] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [163] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [165] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_markup_opening_tag_repeat1, 2),
  [167] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_markup_opening_tag_repeat1, 2), SHIFT_REPEAT(51),
  [170] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [172] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [174] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [176] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [178] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [180] = {.entry = {.count = 1, .reusable = false}}, SHIFT(63),
  [182] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [184] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [186] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [188] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_markup_attribute, 1),
  [190] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [192] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [194] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [196] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [198] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_markup_opening_tag_repeat1, 2), SHIFT_REPEAT(71),
  [201] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [203] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [205] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [207] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [209] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [211] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [213] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_markup_opening_tag_repeat1, 2), SHIFT_REPEAT(63),
  [216] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [218] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [220] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [222] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [224] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [226] = {.entry = {.count = 1, .reusable = true}}, SHIFT(120),
  [228] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [230] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [232] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_markup_attribute, 1),
  [234] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [236] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [238] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [240] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_markup_attribute, 3, .production_id = 5),
  [242] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_attribute_value, 2),
  [244] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [246] = {.entry = {.count = 1, .reusable = true}}, SHIFT(111),
  [248] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [250] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_attribute_value, 3),
  [252] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [254] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [256] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [258] = {.entry = {.count = 1, .reusable = false}}, SHIFT(84),
  [260] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [262] = {.entry = {.count = 1, .reusable = false}}, SHIFT(88),
  [264] = {.entry = {.count = 1, .reusable = true}}, SHIFT(112),
  [266] = {.entry = {.count = 1, .reusable = true}}, SHIFT(103),
  [268] = {.entry = {.count = 1, .reusable = true}}, SHIFT(108),
  [270] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_style_start_tag, 3, .production_id = 1),
  [272] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_script_start_tag, 3, .production_id = 1),
  [274] = {.entry = {.count = 1, .reusable = false}}, SHIFT(66),
  [276] = {.entry = {.count = 1, .reusable = true}}, SHIFT(104),
  [278] = {.entry = {.count = 1, .reusable = true}}, SHIFT(113),
  [280] = {.entry = {.count = 1, .reusable = true}}, SHIFT(119),
  [282] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_script_start_tag, 4, .production_id = 4),
  [284] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_markup_attribute, 3, .production_id = 5),
  [286] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_quoted_attribute_value, 2),
  [288] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_quoted_attribute_value, 3),
  [290] = {.entry = {.count = 1, .reusable = true}}, SHIFT(102),
  [292] = {.entry = {.count = 1, .reusable = true}}, SHIFT(105),
  [294] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_style_start_tag, 4, .production_id = 4),
  [296] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [298] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [300] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [302] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [304] = {.entry = {.count = 1, .reusable = true}}, SHIFT(115),
  [306] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [308] = {.entry = {.count = 1, .reusable = true}}, SHIFT(110),
  [310] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [312] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [314] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [316] = {.entry = {.count = 1, .reusable = true}}, SHIFT(106),
  [318] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [320] = {.entry = {.count = 1, .reusable = true}}, SHIFT(118),
  [322] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [324] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [326] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [328] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [330] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [332] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [334] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [336] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_html_external_scanner_create(void);
void tree_sitter_html_external_scanner_destroy(void *);
bool tree_sitter_html_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_html_external_scanner_serialize(void *, char *);
void tree_sitter_html_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_html(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_html_external_scanner_create,
      tree_sitter_html_external_scanner_destroy,
      tree_sitter_html_external_scanner_scan,
      tree_sitter_html_external_scanner_serialize,
      tree_sitter_html_external_scanner_deserialize,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
